#! /usr/bin/env python
#
# Copyright (c) 2008, Nicolas Rougier
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of the University of California, Berkeley nor the
#       names of its contributors may be used to endorse or promote products
#       derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE AUTHOR AND CONTRIBUTORS BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

""" Interactive Python/IPython/Pylab console

This console implements a python (or ipython) shell within a GTK window and
handles python stdin/stderr/stdout redirection and system wide stdout/stderr
redirection (using a pipe), provides history based on the GNU readline package
and automatic completion. It is also able to display matplotlib figures
inline. Each call to the show functions actually produces a FigureCanvasGTK4Agg
that is inserted within the console.

Usage: ./pycons [--ipython] [--pylab] [--toolbar] file

You can refresh all active figures by calling the refresh() method and replot
the last figures using the replot() method. You can also zoom(), pan(), home(),
back(), forward() and save() active figure.
"""

import os
import sys
import gi
gi.require_version('Gtk', '4.0')
from gi.repository import GdkPixbuf, GLib, Gtk

pylab_available = True
try:
    import matplotlib
    matplotlib.use('GTK4Agg')
    from matplotlib.backends.backend_gtk4agg \
        import FigureCanvasGTK4Agg as Canvas
    from matplotlib.backends.backend_gtk4 \
        import NavigationToolbar2GTK4 as NavigationToolbar
    import matplotlib.backends.backend_gtk4agg as backend_gtk4agg
    def draw_if_interactive():
        """ Is called after every pylab drawing command """
        show(console)
    backend_gtk4agg.draw_if_interactive = draw_if_interactive
    import pylab
    import matplotlib.pylab
    from matplotlib._pylab_helpers import Gcf
except:
    pylab_available = False

ipython_available = True
try:
    import IPython
except:
    ipython_available = False

try:
    from functools import partial
except ImportError:
    def partial(func, *args, **keywords):
        def newfunc(*fargs, **fkeywords):
            newkeywords = keywords.copy()
            newkeywords.update(fkeywords)
            return func(*(args + fargs), **newkeywords)
        newfunc.func = func
        newfunc.args = args
        newfunc.keywords = keywords
        return newfunc

import pycons.console as cons


# ---------------------------------------------------------------------- replace
def replace (console, canvas, anchor):
    """ Replaces a given canvas with a static image replica """

    figures = console.figures
    view = console.view
    canvas.draw()
    w, h = canvas.get_width(), canvas.get_height()
    pixels = GLib.Bytes.new(bytes(canvas.buffer_rgba()))
    pixbuf = GdkPixbuf.Pixbuf.new_from_bytes(
        pixels, GdkPixbuf.Colorspace.RGB, True, 8, w, h, w * 4)
    image = Gtk.Picture.new_for_pixbuf(pixbuf)
    for widget in anchor.get_widgets():
        view.remove(widget)
    view.add_child_at_anchor(image, anchor)
    return image

# ----------------------------------------------------------------------- refresh
def refresh(console):
    """ Refreshes all active canvas  """

    figures = console.figures
    for fig in figures:
        figure, canvas, anchor = fig
        canvas.draw()
    context = GLib.MainContext.default()
    while context.pending():
        context.iteration(False)

# ----------------------------------------------------------------------- refresh
def figure_enter(controller, x, y, canvas, console):
    """ Change cursor to an arrow """

    canvas.grab_focus()
    console.active_canvas = canvas

# ----------------------------------------------------------------------- refresh
def figure_leave(controller, canvas, console):
    """ Change cursor to text cursor """

    console.view.grab_focus()
    console.active_canvas = None

# ----------------------------------------------------------------------- insert
def insert (console, figure):
    """  Inserts a new canvas for the given figure """

    figures = console.figures
    last_figure = console.last_figure
    figure.set_facecolor ('w')
    view = console.view
    buffer = console.buffer

    # Compute size of the canvas according to current console visible area
    width, height = console.get_width(), console.get_height()
    dpi = figure.get_dpi()
    figwidth = figure.get_figwidth() * dpi
    figheight = figure.get_figheight() * dpi
    w = int (width*.75)
    h = int ( (w/figwidth)*figheight)
    if h > height*.75:
        h = int (height*.75)
        w = int ( (h/figheight)*figwidth)
    figure.set_figwidth  (w/dpi)
    figure.set_figheight (h/dpi)
    canvas = Canvas(figure)
    for s,func in console.callbacks:
        canvas.mpl_connect(s,func)
    canvas.set_size_request (w,h)
    console.write ('\n')
    console.write (' ', 'center')
    iter = buffer.get_iter_at_mark(buffer.get_mark('insert'))
    anchor = buffer.create_child_anchor(iter)
    console.write (' ', 'center')

    vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
    vbox.append(canvas)
    motion = Gtk.EventControllerMotion()
    motion.connect('enter', figure_enter, canvas, console)
    motion.connect('leave', figure_leave, canvas, console)
    canvas.add_controller(motion)
    toolbar = NavigationToolbar(canvas)
    toolbar.set_visible(console.use_toolbar)
    vbox.append(toolbar)
    view.add_child_at_anchor(vbox, anchor)

    console.shell.namespace()['pan'] = toolbar.pan
    console.shell.namespace()['zoom'] = toolbar.zoom
    console.shell.namespace()['back'] = toolbar.back
    console.shell.namespace()['forward'] = toolbar.forward
    console.shell.namespace()['home'] = toolbar.forward
    console.shell.namespace()['save'] = partial(toolbar.save_figure,1)
    console.write ('\n')
    figures.append ( (figure, canvas, anchor) )
    console.last_figure = figure

# ----------------------------------------------------------------------- refresh
def refresh(console):
    """ Refreshes all active canvas  """
    figures = console.figures
    for fig in figures:
        figure, canvas, anchor = fig
        canvas.draw()

# ----------------------------------------------------------------------- replot
def replot (console):
    """
    Produces a replot of the last figure and insert it within console. Previous
    figure, if it exists, is transformed into a static image replica and
    inserted in place of the previous figure.
    """

    figures = console.figures
    last_figure = console.last_figure
    if not figures:
        if last_figure:
            insert (console, last_figure)
            return
        else:
            return
    figure, canvas, anchor = figures[-1]
    if not anchor.get_deleted():
        replace (console, canvas, anchor)
        figures.remove ( (figure, canvas, anchor) )
        #        insert (console, figure, canvas)
        insert (console, figure)
    else:
        console.figures = console.figures[0:-1]
        insert (console, figure)
    console.view.scroll_mark_onscreen(console.buffer.get_insert())
    context = GLib.MainContext.default()
    while context.pending():
        context.iteration(False)


# ---------------------------------------------------------------------- connect
def connect (console, s, func):
    """ Append callback to the list of callbacks (to be connected later) """

    console.callbacks.append([s,func])


# ------------------------------------------------------------------------- show
def show (console):
    """ Insert pending figures within console """

    figures = console.figures
    last_figure = console.last_figure
    for manager in Gcf.get_all_fig_managers():
        found = False
        for fig in figures:
            figure, canvas, anchor = fig
            if figure == manager.canvas.figure:
                canvas.draw()
                found = True
                break
        if not found:
            insert (console, manager.canvas.figure)

# ---------------------------------------------------------------- class Console
class Console (cons.Console):
    """ GTK python console """

    def __init__(self, argv=[], shelltype='python', banner=[],
                 filename=None, size=100):
        cons.Console.__init__(self, argv, shelltype, banner, filename, size)
        self.buffer.create_tag('center',
                               justification=Gtk.Justification.CENTER,
                               font='Mono 4')
        self.figures = []
        self.callbacks = []
        self.last_figure = None
        self.active_canvas = None


    def key_press_event (self, controller, keyval, keycode, state):
        """ Handle key press event """
        return cons.Console.key_press_event (self, controller, keyval,
                                             keycode, state)

    def refresh (self):
        """ Refresh drawing """
        for fig in self.figures:
            figure, canvas, anchor = fig
            canvas.draw()
        return False


if __name__ == "__main__":
    from optparse import OptionParser
    try:
        import IPython
    except:
        pass

    usage = "Usage: %pycons [options] file"
    parser = OptionParser(usage=usage, version="%prog 1.0")
    parser.add_option("", "--ipython", action="store_true", dest="ipython",
                      help="Use IPython as shell (if available)")
    parser.add_option("", "--pylab",   action="store_true", dest="pylab",
                      help="Use Pylab integration (if available)")
    parser.add_option("", "--toolbar",  action="store_true", dest="toolbar",
                      help="Use Pylab toolbar")
    (options, args) = parser.parse_args()

    filename = os.path.expanduser("~/.pyhistory")
    p = 'Python %s' % sys.version.split(' ')[0]
    l = 'matplotlib %s' % matplotlib.__version__ if pylab_available else ''
    shelltype = 'python'
    if (options.ipython and ipython_available) is True:
        p = 'IPython %s' % IPython.__version__
        shelltype = 'ipython'
    if not pylab_available or not options.pylab:
        banner = [
            ['GTK Python console\n', 'title'],
            [' Using %s\n' % p,'subtitle'],
            [' Type "help", "copyright", "credits" or "license" for more information.\n',
             'subtitle']
            ]
    else:
        banner = [
            ['GTK Pylab console\n', 'title'],
            [' Using %s and %s\n' % (p,l),'subtitle'],
            [' Extra commands: "replot", "refresh", "pan", "zoom", "back", "forward", "home"\n',
             'subtitle']
            ]
    application = Gtk.Application(application_id='org.gnucash.PyCons')

    def activate(app):
        global console
        console = Console(argv=args, shelltype=shelltype,
                          banner=banner, filename=filename, size=100)
        console.use_toolbar = options.toolbar

        window = Gtk.ApplicationWindow(application=app)
        window.set_default_size(800, 600)
        window.set_child(console)

        def close_requested(widget):
            console.quit()
            app.quit()
            return False

        window.connect('close-request', close_requested)

        if pylab_available and options.pylab:
            console.write ("from pylab import *")
            console.execute()
            pylab.show = partial (show, console)
            matplotlib.pylab.show = pylab.show
            matplotlib.pyplot.show = pylab.show
            pylab.connect = partial (connect, console)
            matplotlib.pylab.connect = pylab.connect
            console.shell.namespace()['replot'] = partial (replot, console)
            console.shell.namespace()['refresh'] = partial (refresh, console)

        def execfiles(console):
            console.write ('exec(open("%s").read())' % args[0])
            console.execute()
            return False

        if len(args):
            GLib.timeout_add(50, execfiles, console)

        def quit_when_done():
            if console.do_quit:
                app.quit()
                return False
            return True

        GLib.timeout_add(50, quit_when_done)
        window.present()
        console.view.grab_focus()

    application.connect('activate', activate)
    application.run([sys.argv[0]])

