/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "glade-cb-gnc-dialogs.h"
#include "glade-gnc-dialogs.h"
#include "glade-support-gnc-dialogs.h"

GtkWidget*
create_QIF_File_Import_Dialog (void)
{
  GtkWidget *QIF_File_Import_Dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *notebook1;
  GtkWidget *hbox1;
  GtkWidget *frame2;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *selected_file_list;
  GtkWidget *frame3;
  GtkWidget *vbox2;
  GtkWidget *hbox10;
  GtkWidget *vbox3;
  GtkWidget *label1;
  GtkWidget *label679;
  GtkWidget *currency_label;
  GtkWidget *radix_format_label;
  GtkWidget *date_format_label;
  GtkWidget *vbox4;
  GtkWidget *qif_filename_entry;
  GtkWidget *hbox11;
  GtkWidget *qif_account_auto_check;
  GtkWidget *qif_account_entry;
  GtkWidget *qif_currency_entry;
  GtkWidget *qif_radix_picker;
  GtkWidget *qif_radix_picker_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *qif_date_picker;
  GtkWidget *qif_date_picker_menu;
  GtkWidget *hbox9;
  GtkWidget *file_select_btn;
  GtkWidget *add_file_button;
  GtkWidget *label69;
  GtkWidget *scrolledwindow2;
  GtkWidget *account_page_list;
  GtkWidget *label682;
  GtkWidget *label683;
  GtkWidget *label684;
  GtkWidget *label685;
  GtkWidget *label2;
  GtkWidget *scrolledwindow3;
  GtkWidget *category_page_list;
  GtkWidget *label686;
  GtkWidget *label687;
  GtkWidget *label688;
  GtkWidget *label689;
  GtkWidget *foo6868;
  GtkWidget *dialog_action_area2;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;

  QIF_File_Import_Dialog = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (QIF_File_Import_Dialog), "QIF_File_Import_Dialog", QIF_File_Import_Dialog);
  gtk_window_set_policy (GTK_WINDOW (QIF_File_Import_Dialog), TRUE, TRUE, TRUE);

  dialog_vbox2 = GNOME_DIALOG (QIF_File_Import_Dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (QIF_File_Import_Dialog), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), notebook1, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox1);

  frame2 = gtk_frame_new (_("Loaded Files"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox1), frame2, TRUE, TRUE, 0);
  gtk_widget_set_usize (frame2, 200, -2);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame2), scrolledwindow1);
  gtk_widget_set_usize (scrolledwindow1, -2, 150);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  selected_file_list = gtk_list_new ();
  gtk_widget_ref (selected_file_list);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "selected_file_list", selected_file_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (selected_file_list);
  gtk_container_add (GTK_CONTAINER (viewport1), selected_file_list);

  frame3 = gtk_frame_new (_("File Info"));
  gtk_widget_ref (frame3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "frame3", frame3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame3);
  gtk_box_pack_start (GTK_BOX (hbox1), frame3, TRUE, TRUE, 0);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (frame3), vbox2);

  hbox10 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox10);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox10", hbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox10);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox10, TRUE, TRUE, 0);

  vbox3 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "vbox3", vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox3);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox3, TRUE, TRUE, 5);

  label1 = gtk_label_new (_("QIF Filename:"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox3), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);

  label679 = gtk_label_new (_("QIF Account:"));
  gtk_widget_ref (label679);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label679", label679,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label679);
  gtk_box_pack_start (GTK_BOX (vbox3), label679, FALSE, FALSE, 5);
  gtk_label_set_justify (GTK_LABEL (label679), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label679), 1, 0.5);

  currency_label = gtk_label_new (_("Currency:"));
  gtk_widget_ref (currency_label);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "currency_label", currency_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (currency_label);
  gtk_box_pack_start (GTK_BOX (vbox3), currency_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (currency_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (currency_label), 1, 0.5);

  radix_format_label = gtk_label_new (_("Radix format:"));
  gtk_widget_ref (radix_format_label);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "radix_format_label", radix_format_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radix_format_label);
  gtk_box_pack_start (GTK_BOX (vbox3), radix_format_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (radix_format_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (radix_format_label), 1, 0.5);

  date_format_label = gtk_label_new (_("Date format:"));
  gtk_widget_ref (date_format_label);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "date_format_label", date_format_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_format_label);
  gtk_box_pack_start (GTK_BOX (vbox3), date_format_label, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (date_format_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (date_format_label), 1, 0.5);

  vbox4 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox10), vbox4, TRUE, TRUE, 5);

  qif_filename_entry = gtk_entry_new ();
  gtk_widget_ref (qif_filename_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_filename_entry", qif_filename_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_filename_entry);
  gtk_box_pack_start (GTK_BOX (vbox4), qif_filename_entry, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (qif_filename_entry, GTK_CAN_DEFAULT);

  hbox11 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox11);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox11", hbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox11);
  gtk_box_pack_start (GTK_BOX (vbox4), hbox11, TRUE, TRUE, 0);

  qif_account_auto_check = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (qif_account_auto_check);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_account_auto_check", qif_account_auto_check,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_account_auto_check);
  gtk_box_pack_start (GTK_BOX (hbox11), qif_account_auto_check, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (qif_account_auto_check), TRUE);

  qif_account_entry = gtk_entry_new ();
  gtk_widget_ref (qif_account_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_account_entry", qif_account_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_account_entry);
  gtk_box_pack_start (GTK_BOX (hbox11), qif_account_entry, TRUE, TRUE, 0);

  qif_currency_entry = gtk_entry_new ();
  gtk_widget_ref (qif_currency_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_currency_entry", qif_currency_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_currency_entry);
  gtk_box_pack_start (GTK_BOX (vbox4), qif_currency_entry, FALSE, FALSE, 0);

  qif_radix_picker = gtk_option_menu_new ();
  gtk_widget_ref (qif_radix_picker);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_radix_picker", qif_radix_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_radix_picker);
  gtk_box_pack_start (GTK_BOX (vbox4), qif_radix_picker, FALSE, FALSE, 0);
  qif_radix_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Autodetect"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_radix_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Decimal (1,000.00)"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_radix_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Comma (1.000,00)"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_radix_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (qif_radix_picker), qif_radix_picker_menu);

  qif_date_picker = gtk_option_menu_new ();
  gtk_widget_ref (qif_date_picker);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_date_picker", qif_date_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_date_picker);
  gtk_box_pack_start (GTK_BOX (vbox4), qif_date_picker, FALSE, FALSE, 0);
  qif_date_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Autodetect           "));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("MM/DD/YYYY"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("DD/MM/YYYY"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("YYYY/MM/DD"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("YYYY/DD/MM"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (qif_date_picker), qif_date_picker_menu);

  hbox9 = gtk_hbox_new (TRUE, 0);
  gtk_widget_ref (hbox9);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox9", hbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox9);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox9, FALSE, FALSE, 5);

  file_select_btn = gtk_button_new_with_label (_("Select file"));
  gtk_widget_ref (file_select_btn);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "file_select_btn", file_select_btn,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_select_btn);
  gtk_box_pack_start (GTK_BOX (hbox9), file_select_btn, TRUE, TRUE, 5);

  add_file_button = gtk_button_new_with_label (_("Load file"));
  gtk_widget_ref (add_file_button);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "add_file_button", add_file_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_file_button);
  gtk_box_pack_start (GTK_BOX (hbox9), add_file_button, TRUE, TRUE, 5);

  label69 = gtk_label_new (_("Files"));
  gtk_widget_ref (label69);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label69", label69,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label69);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label69);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);

  account_page_list = gtk_clist_new (4);
  gtk_widget_ref (account_page_list);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "account_page_list", account_page_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (account_page_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), account_page_list);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 0, 116);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 2, 204);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (account_page_list));

  label682 = gtk_label_new (_("QIF Account"));
  gtk_widget_ref (label682);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label682", label682,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label682);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 0, label682);

  label683 = gtk_label_new (_("Transactions"));
  gtk_widget_ref (label683);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label683", label683,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label683);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 1, label683);

  label684 = gtk_label_new (_("GNUCash Account Name"));
  gtk_widget_ref (label684);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label684", label684,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label684);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 2, label684);

  label685 = gtk_label_new (_("Type"));
  gtk_widget_ref (label685);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label685", label685,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label685);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 3, label685);

  label2 = gtk_label_new (_("Accounts"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);

  category_page_list = gtk_clist_new (4);
  gtk_widget_ref (category_page_list);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "category_page_list", category_page_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (category_page_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), category_page_list);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 0, 117);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 2, 204);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (category_page_list));

  label686 = gtk_label_new (_("QIF Category"));
  gtk_widget_ref (label686);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label686", label686,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label686);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 0, label686);

  label687 = gtk_label_new (_("Transactions"));
  gtk_widget_ref (label687);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label687", label687,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label687);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 1, label687);

  label688 = gtk_label_new (_("GNUCash Account Name"));
  gtk_widget_ref (label688);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label688", label688,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label688);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 2, label688);

  label689 = gtk_label_new (_("Type"));
  gtk_widget_ref (label689);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label689", label689,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label689);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 3, label689);

  foo6868 = gtk_label_new (_("Categories"));
  gtk_widget_ref (foo6868);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "foo6868", foo6868,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (foo6868);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), foo6868);

  dialog_action_area2 = GNOME_DIALOG (QIF_File_Import_Dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (QIF_File_Import_Dialog), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area2), 8);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_File_Import_Dialog), GNOME_STOCK_BUTTON_OK);
  button2 = g_list_last (GNOME_DIALOG (QIF_File_Import_Dialog)->buttons)->data;
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_File_Import_Dialog), GNOME_STOCK_BUTTON_CANCEL);
  button3 = g_list_last (GNOME_DIALOG (QIF_File_Import_Dialog)->buttons)->data;
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_File_Import_Dialog), GNOME_STOCK_BUTTON_HELP);
  button4 = g_list_last (GNOME_DIALOG (QIF_File_Import_Dialog)->buttons)->data;
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (selected_file_list), "select_child",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_select_loaded_file_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (file_select_btn), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_select_file_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (add_file_button), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_load_file_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (account_page_list), "select_row",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_account_line_select_cb),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (category_page_list), "select_row",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_category_line_select_cb),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_ok_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_cancel_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_help_cb),
                      QIF_File_Import_Dialog);

  gtk_widget_grab_default (qif_filename_entry);
  return QIF_File_Import_Dialog;
}

GtkWidget*
create_QIF_Import_Account_Picker (void)
{
  GtkWidget *QIF_Import_Account_Picker;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *account_tree;
  GtkWidget *hbox5;
  GtkWidget *vbox4;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *vbox5;
  GtkWidget *acct_entry;
  GtkWidget *acct_description_entry;
  GtkWidget *acct_type_picker;
  GtkWidget *acct_type_picker_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;

  QIF_Import_Account_Picker = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (QIF_Import_Account_Picker), "QIF_Import_Account_Picker", QIF_Import_Account_Picker);
  gtk_window_set_policy (GTK_WINDOW (QIF_Import_Account_Picker), TRUE, TRUE, FALSE);

  vbox1 = GNOME_DIALOG (QIF_Import_Account_Picker)->vbox;
  gtk_object_set_data (GTK_OBJECT (QIF_Import_Account_Picker), "vbox1", vbox1);
  gtk_widget_show (vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (_("Accounts"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox2), frame1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow1);
  gtk_widget_set_usize (scrolledwindow1, 250, 200);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  account_tree = gtk_tree_new ();
  gtk_widget_ref (account_tree);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "account_tree", account_tree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (account_tree);
  gtk_container_add (GTK_CONTAINER (viewport1), account_tree);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, FALSE, 0);

  vbox4 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox4, TRUE, TRUE, 5);

  label1 = gtk_label_new (_("Selected account:"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (vbox4), label1, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label1), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);

  label2 = gtk_label_new (_("Description:"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (vbox4), label2, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label2), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label2), 1, 0.5);

  label3 = gtk_label_new (_("Account type:"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (vbox4), label3, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label3), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);

  vbox5 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox5), vbox5, TRUE, TRUE, 0);

  acct_entry = gtk_entry_new ();
  gtk_widget_ref (acct_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "acct_entry", acct_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (acct_entry);
  gtk_box_pack_start (GTK_BOX (vbox5), acct_entry, FALSE, FALSE, 0);

  acct_description_entry = gtk_entry_new ();
  gtk_widget_ref (acct_description_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "acct_description_entry", acct_description_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (acct_description_entry);
  gtk_box_pack_start (GTK_BOX (vbox5), acct_description_entry, FALSE, FALSE, 0);

  acct_type_picker = gtk_option_menu_new ();
  gtk_widget_ref (acct_type_picker);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "acct_type_picker", acct_type_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (acct_type_picker);
  gtk_box_pack_start (GTK_BOX (vbox5), acct_type_picker, FALSE, FALSE, 0);
  gtk_widget_set_usize (acct_type_picker, 150, 30);
  acct_type_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Bank"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Cash"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Asset"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Credit"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Liability"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Stock"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Mutual"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Currency"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Income"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Expense"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Equity"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (acct_type_picker), acct_type_picker_menu);

  hbuttonbox1 = GNOME_DIALOG (QIF_Import_Account_Picker)->action_area;
  gtk_object_set_data (GTK_OBJECT (QIF_Import_Account_Picker), "hbuttonbox1", hbuttonbox1);
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 8);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_Import_Account_Picker), GNOME_STOCK_BUTTON_OK);
  button1 = g_list_last (GNOME_DIALOG (QIF_Import_Account_Picker)->buttons)->data;
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_Import_Account_Picker), GNOME_STOCK_BUTTON_CANCEL);
  button2 = g_list_last (GNOME_DIALOG (QIF_Import_Account_Picker)->buttons)->data;
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (account_tree), "select_child",
                      GTK_SIGNAL_FUNC (gnc_ui_account_picker_select_cb),
                      QIF_Import_Account_Picker);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_account_picker_ok_cb),
                      QIF_Import_Account_Picker);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_account_picker_cancel_cb),
                      QIF_Import_Account_Picker);

  return QIF_Import_Account_Picker;
}

GtkWidget*
create_Print_Preview_Dialog (void)
{
  GtkWidget *Print_Preview_Dialog;
  GtkWidget *dialog_vbox3;
  GtkWidget *scrolledwindow4;
  GtkWidget *preview_canvas;
  GtkWidget *dialog_action_area3;
  GtkWidget *button5;

  Print_Preview_Dialog = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (Print_Preview_Dialog), "Print_Preview_Dialog", Print_Preview_Dialog);
  gtk_window_set_policy (GTK_WINDOW (Print_Preview_Dialog), TRUE, TRUE, FALSE);

  dialog_vbox3 = GNOME_DIALOG (Print_Preview_Dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (Print_Preview_Dialog), "dialog_vbox3", dialog_vbox3);
  gtk_widget_show (dialog_vbox3);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (Print_Preview_Dialog), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox3), scrolledwindow4, TRUE, TRUE, 0);
  gtk_widget_set_usize (scrolledwindow4, 500, 250);
  gtk_container_set_border_width (GTK_CONTAINER (scrolledwindow4), 1);

  gdk_rgb_init ();
  gtk_widget_push_visual (gdk_rgb_get_visual ());
  gtk_widget_push_colormap (gdk_rgb_get_cmap ());
  preview_canvas = gnome_canvas_new_aa ();
  gtk_widget_pop_colormap ();
  gtk_widget_pop_visual ();
  gtk_widget_ref (preview_canvas);
  gtk_object_set_data_full (GTK_OBJECT (Print_Preview_Dialog), "preview_canvas", preview_canvas,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (preview_canvas);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), preview_canvas);
  gnome_canvas_set_scroll_region (GNOME_CANVAS (preview_canvas), 0, 0, 100, 100);

  dialog_action_area3 = GNOME_DIALOG (Print_Preview_Dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (Print_Preview_Dialog), "dialog_action_area3", dialog_action_area3);
  gtk_widget_show (dialog_action_area3);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area3), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area3), 8);

  gnome_dialog_append_button (GNOME_DIALOG (Print_Preview_Dialog), GNOME_STOCK_BUTTON_OK);
  button5 = g_list_last (GNOME_DIALOG (Print_Preview_Dialog)->buttons)->data;
  gtk_widget_ref (button5);
  gtk_object_set_data_full (GTK_OBJECT (Print_Preview_Dialog), "button5", button5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button5);
  GTK_WIDGET_SET_FLAGS (button5, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button5), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_preview_OK_cb),
                      Print_Preview_Dialog);

  return Print_Preview_Dialog;
}

GtkWidget*
create_Print_Dialog (void)
{
  GtkWidget *Print_Dialog;
  GtkWidget *dialog_vbox4;
  GtkWidget *frame4;
  GtkWidget *hbox12;
  GtkWidget *vbox7;
  GtkWidget *label690;
  GtkWidget *label691;
  GtkWidget *label692;
  GtkWidget *label695;
  GtkWidget *vbox8;
  GtkWidget *printer_entry;
  GtkWidget *paper_entry;
  GtkWidget *hbox13;
  GSList *hbox13_group = NULL;
  GtkWidget *radiobutton1;
  GtkWidget *radiobutton2;
  GtkWidget *label693;
  GtkWidget *hbox14;
  GtkWidget *label696;
  GtkWidget *entry3;
  GtkWidget *label697;
  GtkWidget *entry4;
  GtkWidget *vbox9;
  GtkWidget *button12;
  GtkWidget *button17;
  GtkWidget *label694;
  GtkWidget *label698;
  GtkWidget *dialog_action_area4;
  GtkWidget *button9;
  GtkWidget *button13;
  GtkWidget *button11;

  Print_Dialog = gnome_dialog_new (_("Print Dialog"), NULL);
  gtk_object_set_data (GTK_OBJECT (Print_Dialog), "Print_Dialog", Print_Dialog);
  gtk_window_set_policy (GTK_WINDOW (Print_Dialog), TRUE, TRUE, FALSE);

  dialog_vbox4 = GNOME_DIALOG (Print_Dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (Print_Dialog), "dialog_vbox4", dialog_vbox4);
  gtk_widget_show (dialog_vbox4);

  frame4 = gtk_frame_new (_("Print Setup"));
  gtk_widget_ref (frame4);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "frame4", frame4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox4), frame4, TRUE, TRUE, 0);

  hbox12 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox12);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "hbox12", hbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox12);
  gtk_container_add (GTK_CONTAINER (frame4), hbox12);

  vbox7 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox7);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "vbox7", vbox7,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox7);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox7, TRUE, TRUE, 5);

  label690 = gtk_label_new (_("Printer:"));
  gtk_widget_ref (label690);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label690", label690,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label690);
  gtk_box_pack_start (GTK_BOX (vbox7), label690, FALSE, FALSE, 5);
  gtk_misc_set_alignment (GTK_MISC (label690), 1, 0.5);

  label691 = gtk_label_new (_("Paper size:"));
  gtk_widget_ref (label691);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label691", label691,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label691);
  gtk_box_pack_start (GTK_BOX (vbox7), label691, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label691), 1, 0.5);

  label692 = gtk_label_new (_("Pages to print:"));
  gtk_widget_ref (label692);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label692", label692,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label692);
  gtk_box_pack_start (GTK_BOX (vbox7), label692, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label692), 1, 0.5);

  label695 = gtk_label_new ("");
  gtk_widget_ref (label695);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label695", label695,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label695);
  gtk_box_pack_start (GTK_BOX (vbox7), label695, FALSE, FALSE, 0);

  vbox8 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox8);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "vbox8", vbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox8);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox8, TRUE, TRUE, 0);

  printer_entry = gtk_entry_new ();
  gtk_widget_ref (printer_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "printer_entry", printer_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (printer_entry);
  gtk_box_pack_start (GTK_BOX (vbox8), printer_entry, FALSE, FALSE, 5);
  gtk_entry_set_editable (GTK_ENTRY (printer_entry), FALSE);

  paper_entry = gtk_entry_new ();
  gtk_widget_ref (paper_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "paper_entry", paper_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (paper_entry);
  gtk_box_pack_start (GTK_BOX (vbox8), paper_entry, FALSE, FALSE, 0);
  gtk_entry_set_editable (GTK_ENTRY (paper_entry), FALSE);

  hbox13 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox13);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "hbox13", hbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox13, TRUE, TRUE, 0);

  radiobutton1 = gtk_radio_button_new_with_label (hbox13_group, _("All"));
  hbox13_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton1));
  gtk_widget_ref (radiobutton1);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "radiobutton1", radiobutton1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton1);
  gtk_box_pack_start (GTK_BOX (hbox13), radiobutton1, FALSE, FALSE, 0);

  radiobutton2 = gtk_radio_button_new_with_label (hbox13_group, _("Selected"));
  hbox13_group = gtk_radio_button_group (GTK_RADIO_BUTTON (radiobutton2));
  gtk_widget_ref (radiobutton2);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "radiobutton2", radiobutton2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radiobutton2);
  gtk_box_pack_start (GTK_BOX (hbox13), radiobutton2, FALSE, FALSE, 0);

  label693 = gtk_label_new ("");
  gtk_widget_ref (label693);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label693", label693,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label693);
  gtk_box_pack_start (GTK_BOX (hbox13), label693, FALSE, FALSE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox14);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "hbox14", hbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox8), hbox14, TRUE, TRUE, 0);

  label696 = gtk_label_new (_("From:"));
  gtk_widget_ref (label696);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label696", label696,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label696);
  gtk_box_pack_start (GTK_BOX (hbox14), label696, FALSE, FALSE, 5);

  entry3 = gtk_entry_new_with_max_length (5);
  gtk_widget_ref (entry3);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "entry3", entry3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry3);
  gtk_box_pack_start (GTK_BOX (hbox14), entry3, FALSE, FALSE, 0);
  gtk_widget_set_usize (entry3, 80, -2);

  label697 = gtk_label_new (_("To:"));
  gtk_widget_ref (label697);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label697", label697,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label697);
  gtk_box_pack_start (GTK_BOX (hbox14), label697, FALSE, FALSE, 5);

  entry4 = gtk_entry_new_with_max_length (5);
  gtk_widget_ref (entry4);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "entry4", entry4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (entry4);
  gtk_box_pack_start (GTK_BOX (hbox14), entry4, FALSE, FALSE, 0);
  gtk_widget_set_usize (entry4, 80, -2);

  vbox9 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox9);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "vbox9", vbox9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox9);
  gtk_box_pack_start (GTK_BOX (hbox12), vbox9, TRUE, TRUE, 5);

  button12 = gtk_button_new_with_label (_("Select..."));
  gtk_widget_ref (button12);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "button12", button12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button12);
  gtk_box_pack_start (GTK_BOX (vbox9), button12, TRUE, FALSE, 5);

  button17 = gtk_button_new_with_label (_("Select..."));
  gtk_widget_ref (button17);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "button17", button17,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button17);
  gtk_box_pack_start (GTK_BOX (vbox9), button17, FALSE, FALSE, 0);

  label694 = gtk_label_new ("");
  gtk_widget_ref (label694);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label694", label694,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label694);
  gtk_box_pack_start (GTK_BOX (vbox9), label694, FALSE, FALSE, 0);

  label698 = gtk_label_new ("");
  gtk_widget_ref (label698);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "label698", label698,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label698);
  gtk_box_pack_start (GTK_BOX (vbox9), label698, FALSE, FALSE, 0);

  dialog_action_area4 = GNOME_DIALOG (Print_Dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (Print_Dialog), "dialog_action_area4", dialog_action_area4);
  gtk_widget_show (dialog_action_area4);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area4), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area4), 8);

  gnome_dialog_append_button_with_pixmap (GNOME_DIALOG (Print_Dialog),
                                          _("Print"), GNOME_STOCK_PIXMAP_PRINT);
  button9 = g_list_last (GNOME_DIALOG (Print_Dialog)->buttons)->data;
  gtk_widget_ref (button9);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "button9", button9,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button9);
  GTK_WIDGET_SET_FLAGS (button9, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Print_Dialog), _("Preview"));
  button13 = g_list_last (GNOME_DIALOG (Print_Dialog)->buttons)->data;
  gtk_widget_ref (button13);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "button13", button13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button13);
  GTK_WIDGET_SET_FLAGS (button13, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Print_Dialog), GNOME_STOCK_BUTTON_CANCEL);
  button11 = g_list_last (GNOME_DIALOG (Print_Dialog)->buttons)->data;
  gtk_widget_ref (button11);
  gtk_object_set_data_full (GTK_OBJECT (Print_Dialog), "button11", button11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button11);
  GTK_WIDGET_SET_FLAGS (button11, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button12), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_dialog_select_printer_cb),
                      Print_Dialog);
  gtk_signal_connect (GTK_OBJECT (button17), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_dialog_select_paper_cb),
                      Print_Dialog);
  gtk_signal_connect (GTK_OBJECT (button9), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_dialog_ok_cb),
                      Print_Dialog);
  gtk_signal_connect (GTK_OBJECT (button13), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_dialog_preview_cb),
                      Print_Dialog);
  gtk_signal_connect (GTK_OBJECT (button11), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_dialog_cancel_cb),
                      Print_Dialog);

  return Print_Dialog;
}

GtkWidget*
create_Paper_Size_Selector_Dialog (void)
{
  GtkWidget *Paper_Size_Selector_Dialog;
  GtkWidget *dialog_vbox5;
  GtkWidget *paperselector1;
  GtkWidget *dialog_action_area5;
  GtkWidget *button18;
  GtkWidget *button19;
  GtkWidget *button20;

  Paper_Size_Selector_Dialog = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (Paper_Size_Selector_Dialog), "Paper_Size_Selector_Dialog", Paper_Size_Selector_Dialog);
  gtk_window_set_policy (GTK_WINDOW (Paper_Size_Selector_Dialog), FALSE, FALSE, FALSE);

  dialog_vbox5 = GNOME_DIALOG (Paper_Size_Selector_Dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (Paper_Size_Selector_Dialog), "dialog_vbox5", dialog_vbox5);
  gtk_widget_show (dialog_vbox5);

  paperselector1 = gnome_paper_selector_new ();
  gtk_widget_ref (paperselector1);
  gtk_object_set_data_full (GTK_OBJECT (Paper_Size_Selector_Dialog), "paperselector1", paperselector1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (paperselector1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox5), paperselector1, TRUE, TRUE, 0);

  dialog_action_area5 = GNOME_DIALOG (Paper_Size_Selector_Dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (Paper_Size_Selector_Dialog), "dialog_action_area5", dialog_action_area5);
  gtk_widget_show (dialog_action_area5);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area5), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area5), 8);

  gnome_dialog_append_button (GNOME_DIALOG (Paper_Size_Selector_Dialog), GNOME_STOCK_BUTTON_OK);
  button18 = g_list_last (GNOME_DIALOG (Paper_Size_Selector_Dialog)->buttons)->data;
  gtk_widget_ref (button18);
  gtk_object_set_data_full (GTK_OBJECT (Paper_Size_Selector_Dialog), "button18", button18,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button18);
  GTK_WIDGET_SET_FLAGS (button18, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Paper_Size_Selector_Dialog), GNOME_STOCK_BUTTON_APPLY);
  button19 = g_list_last (GNOME_DIALOG (Paper_Size_Selector_Dialog)->buttons)->data;
  gtk_widget_ref (button19);
  gtk_object_set_data_full (GTK_OBJECT (Paper_Size_Selector_Dialog), "button19", button19,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button19);
  GTK_WIDGET_SET_FLAGS (button19, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Paper_Size_Selector_Dialog), GNOME_STOCK_BUTTON_CANCEL);
  button20 = g_list_last (GNOME_DIALOG (Paper_Size_Selector_Dialog)->buttons)->data;
  gtk_widget_ref (button20);
  gtk_object_set_data_full (GTK_OBJECT (Paper_Size_Selector_Dialog), "button20", button20,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button20);
  GTK_WIDGET_SET_FLAGS (button20, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button18), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_paper_dialog_ok_cb),
                      Paper_Size_Selector_Dialog);
  gtk_signal_connect (GTK_OBJECT (button20), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_paper_dialog_cancel_cb),
                      Paper_Size_Selector_Dialog);

  return Paper_Size_Selector_Dialog;
}

