/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "glade-cb-gnc-dialogs.h"
#include "glade-gnc-dialogs.h"
#include "glade-support.h"

GtkWidget*
create_QIF_Import_Account_Picker (void)
{
  GtkWidget *QIF_Import_Account_Picker;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow24;
  GtkWidget *account_tree;
  GtkWidget *label847711;
  GtkWidget *label847712;
  GtkWidget *button78;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;

  QIF_Import_Account_Picker = gnome_dialog_new (_("Select Account"), NULL);
  gtk_object_set_data (GTK_OBJECT (QIF_Import_Account_Picker), "QIF_Import_Account_Picker", QIF_Import_Account_Picker);
  gtk_window_set_default_size (GTK_WINDOW (QIF_Import_Account_Picker), 300, 400);
  gtk_window_set_policy (GTK_WINDOW (QIF_Import_Account_Picker), TRUE, TRUE, TRUE);

  vbox1 = GNOME_DIALOG (QIF_Import_Account_Picker)->vbox;
  gtk_object_set_data (GTK_OBJECT (QIF_Import_Account_Picker), "vbox1", vbox1);
  gtk_widget_show (vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (_("Select or add a GnuCash account"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (vbox2), frame1, TRUE, TRUE, 0);

  scrolledwindow24 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow24);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "scrolledwindow24", scrolledwindow24,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow24);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow24);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow24), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  account_tree = gtk_ctree_new (2, 0);
  gtk_widget_ref (account_tree);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "account_tree", account_tree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (account_tree);
  gtk_container_add (GTK_CONTAINER (scrolledwindow24), account_tree);
  gtk_clist_set_column_width (GTK_CLIST (account_tree), 0, 214);
  gtk_clist_set_column_width (GTK_CLIST (account_tree), 1, 48);
  gtk_clist_column_titles_show (GTK_CLIST (account_tree));

  label847711 = gtk_label_new (_("Account"));
  gtk_widget_ref (label847711);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "label847711", label847711,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label847711);
  gtk_clist_set_column_widget (GTK_CLIST (account_tree), 0, label847711);

  label847712 = gtk_label_new (_("New?"));
  gtk_widget_ref (label847712);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "label847712", label847712,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label847712);
  gtk_clist_set_column_widget (GTK_CLIST (account_tree), 1, label847712);

  button78 = gtk_button_new_with_label (_("New Account (child of selected) ..."));
  gtk_widget_ref (button78);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "button78", button78,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button78);
  gtk_box_pack_start (GTK_BOX (vbox1), button78, FALSE, FALSE, 0);

  hbuttonbox1 = GNOME_DIALOG (QIF_Import_Account_Picker)->action_area;
  gtk_object_set_data (GTK_OBJECT (QIF_Import_Account_Picker), "hbuttonbox1", hbuttonbox1);
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 8);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_Import_Account_Picker), GNOME_STOCK_BUTTON_OK);
  button1 = g_list_last (GNOME_DIALOG (QIF_Import_Account_Picker)->buttons)->data;
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_Import_Account_Picker), GNOME_STOCK_BUTTON_CANCEL);
  button2 = g_list_last (GNOME_DIALOG (QIF_Import_Account_Picker)->buttons)->data;
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_Import_Account_Picker), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button78), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_account_picker_new_cb),
                      QIF_Import_Account_Picker);

  return QIF_Import_Account_Picker;
}

GtkWidget*
create_Print_Check_Dialog (void)
{
  GtkWidget *Print_Check_Dialog;
  GtkWidget *dialog_vbox6;
  GtkWidget *notebook4;
  GtkWidget *vbox10;
  GtkWidget *hbox15;
  GtkWidget *vbox11;
  GtkWidget *label699;
  GtkWidget *label700;
  GtkWidget *label713;
  GtkWidget *vbox12;
  GtkWidget *check_format_picker;
  GtkWidget *check_format_picker_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *check_position_picker;
  GtkWidget *check_position_picker_menu;
  GtkWidget *date_format_picker;
  GtkWidget *date_format_picker_menu;
  GtkWidget *label847675;
  GtkWidget *frame5;
  GtkWidget *vbox1x6;
  GtkWidget *hbox16;
  GtkWidget *vbox13;
  GtkWidget *label702;
  GtkWidget *label701;
  GtkWidget *label705;
  GtkWidget *label706;
  GtkWidget *label707;
  GtkWidget *label708;
  GtkWidget *label711;
  GtkWidget *label714;
  GtkWidget *label709;
  GtkWidget *vbox14;
  GtkWidget *label703;
  GtkObject *payee_x_entry_adj;
  GtkWidget *payee_x_entry;
  GtkObject *date_x_entry_adj;
  GtkWidget *date_x_entry;
  GtkObject *amount_words_x_entry_adj;
  GtkWidget *amount_words_x_entry;
  GtkObject *amount_numbers_x_entry_adj;
  GtkWidget *amount_numbers_x_entry;
  GtkObject *memo_x_entry_adj;
  GtkWidget *memo_x_entry;
  GtkObject *check_position_entry_adj;
  GtkWidget *check_position_entry;
  GtkObject *date_format_entry_adj;
  GtkWidget *date_format_entry;
  GtkWidget *units_picker;
  GtkWidget *units_picker_menu;
  GtkWidget *vbox38;
  GtkWidget *label744;
  GtkObject *payee_y_entry_adj;
  GtkWidget *payee_y_entry;
  GtkObject *date_y_entry_adj;
  GtkWidget *date_y_entry;
  GtkObject *amount_words_y_entry_adj;
  GtkWidget *amount_words_y_entry;
  GtkObject *amount_numbers_y_entry_adj;
  GtkWidget *amount_numbers_y_entry;
  GtkObject *memo_y_entry_adj;
  GtkWidget *memo_y_entry;
  GtkWidget *label745;
  GtkWidget *label746;
  GtkWidget *label747;
  GtkWidget *label847676;
  GtkWidget *dialog_action_area6;
  GtkWidget *button21;
  GtkWidget *button22;
  GtkWidget *button23;

  Print_Check_Dialog = gnome_dialog_new (_("Print Check"), NULL);
  gtk_object_set_data (GTK_OBJECT (Print_Check_Dialog), "Print_Check_Dialog", Print_Check_Dialog);
  gtk_window_set_policy (GTK_WINDOW (Print_Check_Dialog), TRUE, TRUE, FALSE);

  dialog_vbox6 = GNOME_DIALOG (Print_Check_Dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (Print_Check_Dialog), "dialog_vbox6", dialog_vbox6);
  gtk_widget_show (dialog_vbox6);

  notebook4 = gtk_notebook_new ();
  gtk_widget_ref (notebook4);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "notebook4", notebook4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook4);
  gtk_box_pack_start (GTK_BOX (dialog_vbox6), notebook4, TRUE, TRUE, 0);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox10);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox10", vbox10,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox10);
  gtk_container_add (GTK_CONTAINER (notebook4), vbox10);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox15);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "hbox15", hbox15,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox10), hbox15, FALSE, FALSE, 0);

  vbox11 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox11);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox11", vbox11,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox11);
  gtk_box_pack_start (GTK_BOX (hbox15), vbox11, TRUE, TRUE, 5);

  label699 = gtk_label_new (_("Check format:"));
  gtk_widget_ref (label699);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label699", label699,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label699);
  gtk_box_pack_start (GTK_BOX (vbox11), label699, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label699), 1, 0.5);

  label700 = gtk_label_new (_("Check position:"));
  gtk_widget_ref (label700);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label700", label700,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label700);
  gtk_box_pack_start (GTK_BOX (vbox11), label700, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label700), 1, 0.5);

  label713 = gtk_label_new (_("Date format:"));
  gtk_widget_ref (label713);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label713", label713,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label713);
  gtk_box_pack_start (GTK_BOX (vbox11), label713, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label713), 1, 0.5);

  vbox12 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox12);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox12", vbox12,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox12);
  gtk_box_pack_start (GTK_BOX (hbox15), vbox12, TRUE, TRUE, 0);

  check_format_picker = gtk_option_menu_new ();
  gtk_widget_ref (check_format_picker);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "check_format_picker", check_format_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_format_picker);
  gtk_box_pack_start (GTK_BOX (vbox12), check_format_picker, FALSE, FALSE, 0);
  check_format_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Quicken/QuickBooks (tm) US-Letter"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (check_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Custom"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (check_format_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (check_format_picker), check_format_picker_menu);

  check_position_picker = gtk_option_menu_new ();
  gtk_widget_ref (check_position_picker);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "check_position_picker", check_position_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_position_picker);
  gtk_box_pack_start (GTK_BOX (vbox12), check_position_picker, FALSE, FALSE, 0);
  check_position_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Top"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (check_position_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Middle"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (check_position_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Bottom"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (check_position_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Custom"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (check_position_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (check_position_picker), check_position_picker_menu);

  date_format_picker = gtk_option_menu_new ();
  gtk_widget_ref (date_format_picker);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "date_format_picker", date_format_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_format_picker);
  gtk_box_pack_start (GTK_BOX (vbox12), date_format_picker, FALSE, FALSE, 0);
  date_format_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("December  31, 2000"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("31 December, 2000"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Dec 31, 2000"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("31 Dec, 2000"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("12/31/2000"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("12/31/00"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("31/12/2000"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("31/12/00"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Custom"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (date_format_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (date_format_picker), date_format_picker_menu);

  label847675 = gtk_label_new (_("Options"));
  gtk_widget_ref (label847675);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label847675", label847675,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label847675);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 0), label847675);

  frame5 = gtk_frame_new (_("Custom check format"));
  gtk_widget_ref (frame5);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "frame5", frame5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame5);
  gtk_container_add (GTK_CONTAINER (notebook4), frame5);

  vbox1x6 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1x6);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox1x6", vbox1x6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1x6);
  gtk_container_add (GTK_CONTAINER (frame5), vbox1x6);

  hbox16 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox16);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "hbox16", hbox16,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox1x6), hbox16, FALSE, FALSE, 0);

  vbox13 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox13);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox13", vbox13,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox16), vbox13, FALSE, FALSE, 2);

  label702 = gtk_label_new ("");
  gtk_widget_ref (label702);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label702", label702,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label702);
  gtk_box_pack_start (GTK_BOX (vbox13), label702, FALSE, FALSE, 0);

  label701 = gtk_label_new (_("Payee:"));
  gtk_widget_ref (label701);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label701", label701,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label701);
  gtk_box_pack_start (GTK_BOX (vbox13), label701, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label701), 1, 0.5);

  label705 = gtk_label_new (_("Date:"));
  gtk_widget_ref (label705);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label705", label705,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label705);
  gtk_box_pack_start (GTK_BOX (vbox13), label705, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label705), 1, 0.5);

  label706 = gtk_label_new (_("Amount (words):"));
  gtk_widget_ref (label706);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label706", label706,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label706);
  gtk_box_pack_start (GTK_BOX (vbox13), label706, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label706), 1, 0.5);

  label707 = gtk_label_new (_("Amount (numbers):"));
  gtk_widget_ref (label707);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label707", label707,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label707);
  gtk_box_pack_start (GTK_BOX (vbox13), label707, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label707), 1, 0.5);

  label708 = gtk_label_new (_("Memo:"));
  gtk_widget_ref (label708);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label708", label708,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label708);
  gtk_box_pack_start (GTK_BOX (vbox13), label708, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label708), 1, 0.5);

  label711 = gtk_label_new (_("Check position:"));
  gtk_widget_ref (label711);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label711", label711,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label711);
  gtk_box_pack_start (GTK_BOX (vbox13), label711, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label711), 1, 0.5);

  label714 = gtk_label_new (_("Date format:"));
  gtk_widget_ref (label714);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label714", label714,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label714);
  gtk_box_pack_start (GTK_BOX (vbox13), label714, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label714), 1, 0.5);

  label709 = gtk_label_new (_("Units:"));
  gtk_widget_ref (label709);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label709", label709,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label709);
  gtk_box_pack_start (GTK_BOX (vbox13), label709, FALSE, FALSE, 0);
  gtk_misc_set_alignment (GTK_MISC (label709), 1, 0.5);

  vbox14 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox14);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox14", vbox14,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox16), vbox14, FALSE, TRUE, 2);

  label703 = gtk_label_new (_("x"));
  gtk_widget_ref (label703);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label703", label703,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label703);
  gtk_box_pack_start (GTK_BOX (vbox14), label703, FALSE, FALSE, 0);

  payee_x_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  payee_x_entry = gtk_spin_button_new (GTK_ADJUSTMENT (payee_x_entry_adj), 1, 3);
  gtk_widget_ref (payee_x_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "payee_x_entry", payee_x_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (payee_x_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), payee_x_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (payee_x_entry), TRUE);

  date_x_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  date_x_entry = gtk_spin_button_new (GTK_ADJUSTMENT (date_x_entry_adj), 1, 3);
  gtk_widget_ref (date_x_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "date_x_entry", date_x_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_x_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), date_x_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (date_x_entry), TRUE);

  amount_words_x_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  amount_words_x_entry = gtk_spin_button_new (GTK_ADJUSTMENT (amount_words_x_entry_adj), 1, 3);
  gtk_widget_ref (amount_words_x_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "amount_words_x_entry", amount_words_x_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amount_words_x_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), amount_words_x_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (amount_words_x_entry), TRUE);

  amount_numbers_x_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  amount_numbers_x_entry = gtk_spin_button_new (GTK_ADJUSTMENT (amount_numbers_x_entry_adj), 1, 3);
  gtk_widget_ref (amount_numbers_x_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "amount_numbers_x_entry", amount_numbers_x_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amount_numbers_x_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), amount_numbers_x_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (amount_numbers_x_entry), TRUE);

  memo_x_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  memo_x_entry = gtk_spin_button_new (GTK_ADJUSTMENT (memo_x_entry_adj), 1, 3);
  gtk_widget_ref (memo_x_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "memo_x_entry", memo_x_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (memo_x_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), memo_x_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (memo_x_entry), TRUE);

  check_position_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  check_position_entry = gtk_spin_button_new (GTK_ADJUSTMENT (check_position_entry_adj), 1, 3);
  gtk_widget_ref (check_position_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "check_position_entry", check_position_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (check_position_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), check_position_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (check_position_entry), TRUE);

  date_format_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  date_format_entry = gtk_spin_button_new (GTK_ADJUSTMENT (date_format_entry_adj), 1, 3);
  gtk_widget_ref (date_format_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "date_format_entry", date_format_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_format_entry);
  gtk_box_pack_start (GTK_BOX (vbox14), date_format_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (date_format_entry), TRUE);

  units_picker = gtk_option_menu_new ();
  gtk_widget_ref (units_picker);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "units_picker", units_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (units_picker);
  gtk_box_pack_start (GTK_BOX (vbox14), units_picker, FALSE, FALSE, 0);
  units_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Inches"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (units_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Centimeters"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (units_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Millimeters"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (units_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Points"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (units_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (units_picker), units_picker_menu);
  gtk_option_menu_set_history (GTK_OPTION_MENU (units_picker), 1);

  vbox38 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox38);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "vbox38", vbox38,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox38);
  gtk_box_pack_start (GTK_BOX (hbox16), vbox38, FALSE, TRUE, 2);

  label744 = gtk_label_new (_("y"));
  gtk_widget_ref (label744);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label744", label744,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label744);
  gtk_box_pack_start (GTK_BOX (vbox38), label744, FALSE, FALSE, 0);

  payee_y_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  payee_y_entry = gtk_spin_button_new (GTK_ADJUSTMENT (payee_y_entry_adj), 1, 3);
  gtk_widget_ref (payee_y_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "payee_y_entry", payee_y_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (payee_y_entry);
  gtk_box_pack_start (GTK_BOX (vbox38), payee_y_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (payee_y_entry), TRUE);

  date_y_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  date_y_entry = gtk_spin_button_new (GTK_ADJUSTMENT (date_y_entry_adj), 1, 3);
  gtk_widget_ref (date_y_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "date_y_entry", date_y_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_y_entry);
  gtk_box_pack_start (GTK_BOX (vbox38), date_y_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (date_y_entry), TRUE);

  amount_words_y_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  amount_words_y_entry = gtk_spin_button_new (GTK_ADJUSTMENT (amount_words_y_entry_adj), 1, 3);
  gtk_widget_ref (amount_words_y_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "amount_words_y_entry", amount_words_y_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amount_words_y_entry);
  gtk_box_pack_start (GTK_BOX (vbox38), amount_words_y_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (amount_words_y_entry), TRUE);

  amount_numbers_y_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  amount_numbers_y_entry = gtk_spin_button_new (GTK_ADJUSTMENT (amount_numbers_y_entry_adj), 1, 3);
  gtk_widget_ref (amount_numbers_y_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "amount_numbers_y_entry", amount_numbers_y_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (amount_numbers_y_entry);
  gtk_box_pack_start (GTK_BOX (vbox38), amount_numbers_y_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (amount_numbers_y_entry), TRUE);

  memo_y_entry_adj = gtk_adjustment_new (0, 0, 100000, 0.1, 10, 10);
  memo_y_entry = gtk_spin_button_new (GTK_ADJUSTMENT (memo_y_entry_adj), 1, 3);
  gtk_widget_ref (memo_y_entry);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "memo_y_entry", memo_y_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (memo_y_entry);
  gtk_box_pack_start (GTK_BOX (vbox38), memo_y_entry, FALSE, FALSE, 0);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (memo_y_entry), TRUE);

  label745 = gtk_label_new ("");
  gtk_widget_ref (label745);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label745", label745,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label745);
  gtk_box_pack_start (GTK_BOX (vbox38), label745, FALSE, FALSE, 0);

  label746 = gtk_label_new (_("                                  "));
  gtk_widget_ref (label746);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label746", label746,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label746);
  gtk_box_pack_start (GTK_BOX (vbox38), label746, FALSE, FALSE, 0);

  label747 = gtk_label_new (_("                    "));
  gtk_widget_ref (label747);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label747", label747,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label747);
  gtk_box_pack_start (GTK_BOX (vbox38), label747, FALSE, FALSE, 0);

  label847676 = gtk_label_new (_("Custom format"));
  gtk_widget_ref (label847676);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "label847676", label847676,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label847676);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook4), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook4), 1), label847676);

  dialog_action_area6 = GNOME_DIALOG (Print_Check_Dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (Print_Check_Dialog), "dialog_action_area6", dialog_action_area6);
  gtk_widget_show (dialog_action_area6);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area6), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area6), 8);

  gnome_dialog_append_button (GNOME_DIALOG (Print_Check_Dialog), GNOME_STOCK_BUTTON_OK);
  button21 = g_list_last (GNOME_DIALOG (Print_Check_Dialog)->buttons)->data;
  gtk_widget_ref (button21);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "button21", button21,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button21);
  GTK_WIDGET_SET_FLAGS (button21, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Print_Check_Dialog), GNOME_STOCK_BUTTON_CANCEL);
  button22 = g_list_last (GNOME_DIALOG (Print_Check_Dialog)->buttons)->data;
  gtk_widget_ref (button22);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "button22", button22,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button22);
  GTK_WIDGET_SET_FLAGS (button22, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (Print_Check_Dialog), GNOME_STOCK_BUTTON_HELP);
  button23 = g_list_last (GNOME_DIALOG (Print_Check_Dialog)->buttons)->data;
  gtk_widget_ref (button23);
  gtk_object_set_data_full (GTK_OBJECT (Print_Check_Dialog), "button23", button23,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button23);
  GTK_WIDGET_SET_FLAGS (button23, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (button21), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_check_dialog_ok_cb),
                      Print_Check_Dialog);
  gtk_signal_connect (GTK_OBJECT (button22), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_check_dialog_cancel_cb),
                      Print_Check_Dialog);
  gtk_signal_connect (GTK_OBJECT (button23), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_print_check_dialog_help_cb),
                      Print_Check_Dialog);

  return Print_Check_Dialog;
}

