/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "glade-cb-qif-import.h"
#include "glade-qif-import.h"
#include "glade-support-qif-import.h"

GtkWidget*
create_QIF_File_Import_Dialog (void)
{
  GtkWidget *QIF_File_Import_Dialog;
  GtkWidget *dialog_vbox2;
  GtkWidget *notebook1;
  GtkWidget *hbox1;
  GtkWidget *frame2;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *selected_file_list;
  GtkWidget *frame1;
  GtkWidget *vbox1;
  GtkWidget *hbox5;
  GtkWidget *label1;
  GtkWidget *qif_filename_entry;
  GtkWidget *hbox8;
  GtkWidget *label679;
  GtkWidget *qif_account_auto_check;
  GtkWidget *qif_account_entry;
  GtkWidget *hbox2;
  GtkWidget *currency_label;
  GtkWidget *qif_currency_entry;
  GtkWidget *hbox3;
  GtkWidget *radix_format_label;
  GtkWidget *qif_radix_picker;
  GtkWidget *qif_radix_picker_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *hbox4;
  GtkWidget *date_format_label;
  GtkWidget *qif_date_picker;
  GtkWidget *qif_date_picker_menu;
  GtkWidget *hbox6;
  GtkWidget *file_select_btn;
  GtkWidget *add_file_button;
  GtkWidget *label69;
  GtkWidget *scrolledwindow2;
  GtkWidget *account_page_list;
  GtkWidget *label682;
  GtkWidget *label683;
  GtkWidget *label684;
  GtkWidget *label685;
  GtkWidget *label2;
  GtkWidget *scrolledwindow3;
  GtkWidget *category_page_list;
  GtkWidget *label686;
  GtkWidget *label687;
  GtkWidget *label688;
  GtkWidget *label689;
  GtkWidget *foo6868;
  GtkWidget *dialog_action_area2;
  GtkWidget *button2;
  GtkWidget *button3;
  GtkWidget *button4;

  QIF_File_Import_Dialog = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (QIF_File_Import_Dialog), "QIF_File_Import_Dialog", QIF_File_Import_Dialog);
  gtk_window_set_policy (GTK_WINDOW (QIF_File_Import_Dialog), TRUE, TRUE, FALSE);

  dialog_vbox2 = GNOME_DIALOG (QIF_File_Import_Dialog)->vbox;
  gtk_object_set_data (GTK_OBJECT (QIF_File_Import_Dialog), "dialog_vbox2", dialog_vbox2);
  gtk_widget_show (dialog_vbox2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), notebook1, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (notebook1), hbox1);

  frame2 = gtk_frame_new (_("Loaded Files"));
  gtk_widget_ref (frame2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "frame2", frame2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame2);
  gtk_box_pack_start (GTK_BOX (hbox1), frame2, TRUE, TRUE, 0);
  gtk_widget_set_usize (frame2, 200, -2);
  gtk_frame_set_label_align (GTK_FRAME (frame2), 0.05, 0.5);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame2), scrolledwindow1);
  gtk_widget_set_usize (scrolledwindow1, -2, 150);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  selected_file_list = gtk_list_new ();
  gtk_widget_ref (selected_file_list);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "selected_file_list", selected_file_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (selected_file_list);
  gtk_container_add (GTK_CONTAINER (viewport1), selected_file_list);

  frame1 = gtk_frame_new (_("File Info"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox1), frame1, FALSE, FALSE, 0);
  gtk_widget_set_usize (frame1, 325, -2);
  gtk_frame_set_label_align (GTK_FRAME (frame1), 0.01, 0.5);

  vbox1 = gtk_vbox_new (TRUE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (frame1), vbox1);

  hbox5 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox5);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox5", hbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox5);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox5, FALSE, FALSE, 0);

  label1 = gtk_label_new (_("QIF Filename"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox5), label1, FALSE, FALSE, 10);
  gtk_widget_set_usize (label1, 70, -2);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);

  qif_filename_entry = gtk_entry_new ();
  gtk_widget_ref (qif_filename_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_filename_entry", qif_filename_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_filename_entry);
  gtk_box_pack_start (GTK_BOX (hbox5), qif_filename_entry, TRUE, TRUE, 5);
  GTK_WIDGET_SET_FLAGS (qif_filename_entry, GTK_CAN_DEFAULT);

  hbox8 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox8);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox8", hbox8,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox8);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox8, TRUE, TRUE, 0);

  label679 = gtk_label_new (_("QIF Account"));
  gtk_widget_ref (label679);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label679", label679,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label679);
  gtk_box_pack_start (GTK_BOX (hbox8), label679, FALSE, FALSE, 10);
  gtk_widget_set_usize (label679, 70, -2);
  gtk_misc_set_alignment (GTK_MISC (label679), 1, 0.5);

  qif_account_auto_check = gtk_check_button_new_with_label (_("Auto"));
  gtk_widget_ref (qif_account_auto_check);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_account_auto_check", qif_account_auto_check,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_account_auto_check);
  gtk_box_pack_start (GTK_BOX (hbox8), qif_account_auto_check, FALSE, FALSE, 2);
  gtk_widget_set_usize (qif_account_auto_check, 45, 16);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (qif_account_auto_check), TRUE);

  qif_account_entry = gtk_entry_new ();
  gtk_widget_ref (qif_account_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_account_entry", qif_account_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_account_entry);
  gtk_box_pack_start (GTK_BOX (hbox8), qif_account_entry, TRUE, TRUE, 5);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, FALSE, FALSE, 0);

  currency_label = gtk_label_new (_("Currency"));
  gtk_widget_ref (currency_label);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "currency_label", currency_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (currency_label);
  gtk_box_pack_start (GTK_BOX (hbox2), currency_label, FALSE, FALSE, 10);
  gtk_widget_set_usize (currency_label, 70, -2);
  gtk_label_set_justify (GTK_LABEL (currency_label), GTK_JUSTIFY_LEFT);
  gtk_misc_set_alignment (GTK_MISC (currency_label), 1, 0.5);

  qif_currency_entry = gtk_entry_new ();
  gtk_widget_ref (qif_currency_entry);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_currency_entry", qif_currency_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_currency_entry);
  gtk_box_pack_start (GTK_BOX (hbox2), qif_currency_entry, FALSE, FALSE, 5);
  gtk_widget_set_usize (qif_currency_entry, 75, -2);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0);

  radix_format_label = gtk_label_new (_("Radix format"));
  gtk_widget_ref (radix_format_label);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "radix_format_label", radix_format_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (radix_format_label);
  gtk_box_pack_start (GTK_BOX (hbox3), radix_format_label, FALSE, FALSE, 10);
  gtk_widget_set_usize (radix_format_label, 70, -2);
  gtk_label_set_justify (GTK_LABEL (radix_format_label), GTK_JUSTIFY_RIGHT);
  gtk_misc_set_alignment (GTK_MISC (radix_format_label), 1, 0.5);

  qif_radix_picker = gtk_option_menu_new ();
  gtk_widget_ref (qif_radix_picker);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_radix_picker", qif_radix_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_radix_picker);
  gtk_box_pack_start (GTK_BOX (hbox3), qif_radix_picker, FALSE, FALSE, 5);
  gtk_widget_set_usize (qif_radix_picker, 140, -2);
  qif_radix_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Autodetect"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_radix_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Decimal (1,000.00)"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_radix_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Comma (1.000,00)"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_radix_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (qif_radix_picker), qif_radix_picker_menu);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, FALSE, FALSE, 0);

  date_format_label = gtk_label_new (_("Date format"));
  gtk_widget_ref (date_format_label);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "date_format_label", date_format_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (date_format_label);
  gtk_box_pack_start (GTK_BOX (hbox4), date_format_label, FALSE, FALSE, 10);
  gtk_widget_set_usize (date_format_label, 70, -2);
  gtk_misc_set_alignment (GTK_MISC (date_format_label), 1, 0.5);

  qif_date_picker = gtk_option_menu_new ();
  gtk_widget_ref (qif_date_picker);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "qif_date_picker", qif_date_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (qif_date_picker);
  gtk_box_pack_start (GTK_BOX (hbox4), qif_date_picker, FALSE, FALSE, 5);
  gtk_widget_set_usize (qif_date_picker, 140, -2);
  qif_date_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Autodetect           "));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("MM/DD/YYYY"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("DD/MM/YYYY"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("YYYY/MM/DD"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("YYYY/DD/MM"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (qif_date_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (qif_date_picker), qif_date_picker_menu);

  hbox6 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox6);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "hbox6", hbox6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox6);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox6, TRUE, TRUE, 5);

  file_select_btn = gtk_button_new_with_label (_("Select file"));
  gtk_widget_ref (file_select_btn);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "file_select_btn", file_select_btn,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_select_btn);
  gtk_box_pack_start (GTK_BOX (hbox6), file_select_btn, TRUE, FALSE, 3);
  gtk_widget_set_usize (file_select_btn, 125, -2);

  add_file_button = gtk_button_new_with_label (_("Load file"));
  gtk_widget_ref (add_file_button);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "add_file_button", add_file_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (add_file_button);
  gtk_box_pack_start (GTK_BOX (hbox6), add_file_button, TRUE, FALSE, 0);
  gtk_widget_set_usize (add_file_button, 125, -2);

  label69 = gtk_label_new (_("Files"));
  gtk_widget_ref (label69);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label69", label69,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label69);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label69);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow2);

  account_page_list = gtk_clist_new (4);
  gtk_widget_ref (account_page_list);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "account_page_list", account_page_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (account_page_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), account_page_list);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 0, 116);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 2, 204);
  gtk_clist_set_column_width (GTK_CLIST (account_page_list), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (account_page_list));

  label682 = gtk_label_new (_("QIF Account"));
  gtk_widget_ref (label682);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label682", label682,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label682);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 0, label682);

  label683 = gtk_label_new (_("Transactions"));
  gtk_widget_ref (label683);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label683", label683,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label683);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 1, label683);

  label684 = gtk_label_new (_("GNUCash Account Name"));
  gtk_widget_ref (label684);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label684", label684,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label684);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 2, label684);

  label685 = gtk_label_new (_("Type"));
  gtk_widget_ref (label685);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label685", label685,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label685);
  gtk_clist_set_column_widget (GTK_CLIST (account_page_list), 3, label685);

  label2 = gtk_label_new (_("Accounts"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label2);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow3);

  category_page_list = gtk_clist_new (4);
  gtk_widget_ref (category_page_list);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "category_page_list", category_page_list,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (category_page_list);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), category_page_list);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 0, 117);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 1, 80);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 2, 204);
  gtk_clist_set_column_width (GTK_CLIST (category_page_list), 3, 80);
  gtk_clist_column_titles_show (GTK_CLIST (category_page_list));

  label686 = gtk_label_new (_("QIF Category"));
  gtk_widget_ref (label686);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label686", label686,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label686);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 0, label686);

  label687 = gtk_label_new (_("Transactions"));
  gtk_widget_ref (label687);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label687", label687,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label687);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 1, label687);

  label688 = gtk_label_new (_("GNUCash Account Name"));
  gtk_widget_ref (label688);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label688", label688,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label688);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 2, label688);

  label689 = gtk_label_new (_("Type"));
  gtk_widget_ref (label689);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "label689", label689,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label689);
  gtk_clist_set_column_widget (GTK_CLIST (category_page_list), 3, label689);

  foo6868 = gtk_label_new (_("Categories"));
  gtk_widget_ref (foo6868);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "foo6868", foo6868,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (foo6868);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), foo6868);

  dialog_action_area2 = GNOME_DIALOG (QIF_File_Import_Dialog)->action_area;
  gtk_object_set_data (GTK_OBJECT (QIF_File_Import_Dialog), "dialog_action_area2", dialog_action_area2);
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area2), 8);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_File_Import_Dialog), GNOME_STOCK_BUTTON_OK);
  button2 = g_list_last (GNOME_DIALOG (QIF_File_Import_Dialog)->buttons)->data;
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_File_Import_Dialog), GNOME_STOCK_BUTTON_CANCEL);
  button3 = g_list_last (GNOME_DIALOG (QIF_File_Import_Dialog)->buttons)->data;
  gtk_widget_ref (button3);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "button3", button3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button3);
  GTK_WIDGET_SET_FLAGS (button3, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (QIF_File_Import_Dialog), GNOME_STOCK_BUTTON_HELP);
  button4 = g_list_last (GNOME_DIALOG (QIF_File_Import_Dialog)->buttons)->data;
  gtk_widget_ref (button4);
  gtk_object_set_data_full (GTK_OBJECT (QIF_File_Import_Dialog), "button4", button4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button4);
  GTK_WIDGET_SET_FLAGS (button4, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (selected_file_list), "select_child",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_select_loaded_file_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (file_select_btn), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_select_file_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (add_file_button), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_load_file_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (account_page_list), "select_row",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_account_line_select_cb),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (category_page_list), "select_row",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_category_line_select_cb),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_ok_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (button3), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_cancel_cb),
                      QIF_File_Import_Dialog);
  gtk_signal_connect (GTK_OBJECT (button4), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_qif_import_help_cb),
                      QIF_File_Import_Dialog);

  gtk_widget_grab_default (qif_filename_entry);
  return QIF_File_Import_Dialog;
}

