/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_QIF_Import_Account_Picker (void);
GtkWidget* create_Print_Check_Dialog (void);
GtkWidget* create_Find_Transactions (void);
GtkWidget* create_Budget_Dialog (void);
GtkWidget* create_Financial_Calculator_Dialog (void);
GtkWidget* create_Amortization_Schedule_Dialog (void);
GtkWidget* create_Commodity_Selector_Dialog (void);
GtkWidget* create_Commodity_Dialog (void);
GtkWidget* create_Account_Dialog (void);
GtkWidget* create_New_Commodity_Format_Druid (void);
GtkWidget* create_QIF_Import_Druid (void);
