/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "glade-cb-account-picker.h"
#include "glade-account-picker.h"
#include "glade-support-account-picker.h"

GtkWidget*
create_GNUcash_Account_Picker (void)
{
  GtkWidget *GNUcash_Account_Picker;
  GtkWidget *vbox1;
  GtkWidget *vbox2;
  GtkWidget *hbox1;
  GtkWidget *frame1;
  GtkWidget *scrolledwindow1;
  GtkWidget *viewport1;
  GtkWidget *account_tree;
  GtkWidget *hbox2;
  GtkWidget *label1;
  GtkWidget *acct_entry;
  GtkWidget *hbox3;
  GtkWidget *label2;
  GtkWidget *acct_description_entry;
  GtkWidget *hbox4;
  GtkWidget *label3;
  GtkWidget *acct_type_picker;
  GtkWidget *acct_type_picker_menu;
  GtkWidget *glade_menuitem;
  GtkWidget *hbuttonbox1;
  GtkWidget *button1;
  GtkWidget *button2;

  GNUcash_Account_Picker = gnome_dialog_new (NULL, NULL);
  gtk_object_set_data (GTK_OBJECT (GNUcash_Account_Picker), "GNUcash_Account_Picker", GNUcash_Account_Picker);
  gtk_window_set_policy (GTK_WINDOW (GNUcash_Account_Picker), TRUE, TRUE, FALSE);

  vbox1 = GNOME_DIALOG (GNUcash_Account_Picker)->vbox;
  gtk_object_set_data (GTK_OBJECT (GNUcash_Account_Picker), "vbox1", vbox1);
  gtk_widget_show (vbox1);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), vbox2, TRUE, TRUE, 0);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox1, TRUE, TRUE, 0);

  frame1 = gtk_frame_new (_("Accounts"));
  gtk_widget_ref (frame1);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "frame1", frame1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (frame1);
  gtk_box_pack_start (GTK_BOX (hbox1), frame1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (frame1), scrolledwindow1);
  gtk_widget_set_usize (scrolledwindow1, 250, 200);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), viewport1);

  account_tree = gtk_tree_new ();
  gtk_widget_ref (account_tree);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "account_tree", account_tree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (account_tree);
  gtk_container_add (GTK_CONTAINER (viewport1), account_tree);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox2, FALSE, FALSE, 6);

  label1 = gtk_label_new (_("Selected account"));
  gtk_widget_ref (label1);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "label1", label1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label1);
  gtk_box_pack_start (GTK_BOX (hbox2), label1, FALSE, FALSE, 8);
  gtk_widget_set_usize (label1, 90, -2);
  gtk_misc_set_alignment (GTK_MISC (label1), 1, 0.5);

  acct_entry = gtk_entry_new ();
  gtk_widget_ref (acct_entry);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "acct_entry", acct_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (acct_entry);
  gtk_box_pack_start (GTK_BOX (hbox2), acct_entry, TRUE, TRUE, 0);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, FALSE, FALSE, 0);

  label2 = gtk_label_new (_("Description"));
  gtk_widget_ref (label2);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "label2", label2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label2);
  gtk_box_pack_start (GTK_BOX (hbox3), label2, FALSE, FALSE, 8);
  gtk_widget_set_usize (label2, 90, -2);
  gtk_misc_set_alignment (GTK_MISC (label2), 1, 0.5);

  acct_description_entry = gtk_entry_new ();
  gtk_widget_ref (acct_description_entry);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "acct_description_entry", acct_description_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (acct_description_entry);
  gtk_box_pack_start (GTK_BOX (hbox3), acct_description_entry, TRUE, TRUE, 0);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox4, FALSE, FALSE, 0);

  label3 = gtk_label_new (_("Account type"));
  gtk_widget_ref (label3);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "label3", label3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox4), label3, FALSE, FALSE, 8);
  gtk_widget_set_usize (label3, 90, -2);
  gtk_misc_set_alignment (GTK_MISC (label3), 1, 0.5);

  acct_type_picker = gtk_option_menu_new ();
  gtk_widget_ref (acct_type_picker);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "acct_type_picker", acct_type_picker,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (acct_type_picker);
  gtk_box_pack_start (GTK_BOX (hbox4), acct_type_picker, FALSE, FALSE, 0);
  gtk_widget_set_usize (acct_type_picker, 150, 30);
  acct_type_picker_menu = gtk_menu_new ();
  glade_menuitem = gtk_menu_item_new_with_label (_("Bank"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Cash"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Asset"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Credit"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Liability"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Stock"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Mutual"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Currency"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Income"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Expense"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  glade_menuitem = gtk_menu_item_new_with_label (_("Equity"));
  gtk_widget_show (glade_menuitem);
  gtk_menu_append (GTK_MENU (acct_type_picker_menu), glade_menuitem);
  gtk_option_menu_set_menu (GTK_OPTION_MENU (acct_type_picker), acct_type_picker_menu);

  hbuttonbox1 = GNOME_DIALOG (GNUcash_Account_Picker)->action_area;
  gtk_object_set_data (GTK_OBJECT (GNUcash_Account_Picker), "hbuttonbox1", hbuttonbox1);
  gtk_widget_show (hbuttonbox1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (hbuttonbox1), GTK_BUTTONBOX_SPREAD);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (hbuttonbox1), 8);

  gnome_dialog_append_button (GNOME_DIALOG (GNUcash_Account_Picker), GNOME_STOCK_BUTTON_OK);
  button1 = g_list_last (GNOME_DIALOG (GNUcash_Account_Picker)->buttons)->data;
  gtk_widget_ref (button1);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "button1", button1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button1);
  GTK_WIDGET_SET_FLAGS (button1, GTK_CAN_DEFAULT);

  gnome_dialog_append_button (GNOME_DIALOG (GNUcash_Account_Picker), GNOME_STOCK_BUTTON_CANCEL);
  button2 = g_list_last (GNOME_DIALOG (GNUcash_Account_Picker)->buttons)->data;
  gtk_widget_ref (button2);
  gtk_object_set_data_full (GTK_OBJECT (GNUcash_Account_Picker), "button2", button2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (button2);
  GTK_WIDGET_SET_FLAGS (button2, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (account_tree), "select_child",
                      GTK_SIGNAL_FUNC (gnc_ui_account_picker_select_cb),
                      GNUcash_Account_Picker);
  gtk_signal_connect (GTK_OBJECT (button1), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_account_picker_ok_cb),
                      GNUcash_Account_Picker);
  gtk_signal_connect (GTK_OBJECT (button2), "clicked",
                      GTK_SIGNAL_FUNC (gnc_ui_account_picker_cancel_cb),
                      GNUcash_Account_Picker);

  return GNUcash_Account_Picker;
}

