/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gnome.h>

#include "new-user-callbacks.h"
#include "new-user-interface.h"
#include "glade-support.h"

GtkWidget*
create_newUserDialog (void)
{
  GtkWidget *newUserDialog;
  GtkWidget *accountChooseDruidPage;
  GtkWidget *newUserStartPage;
  GdkColor newUserStartPage_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor newUserStartPage_textbox_color = { 0, 65535, 65535, 65535 };
  GdkColor newUserStartPage_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor newUserStartPage_title_color = { 0, 65535, 65535, 65535 };
  GtkWidget *newAccountCurrencyChoosePage;
  GdkColor newAccountCurrencyChoosePage_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor newAccountCurrencyChoosePage_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor newAccountCurrencyChoosePage_title_color = { 0, 65535, 65535, 65535 };
  GtkWidget *newAccountCurrencyChooser_vbox2;
  GtkWidget *newUserChooseCurrencyDescrip;
  GtkWidget *newAccountCurrencyChooser_vbox;
  GtkWidget *chooseAccountTypesPage;
  GdkColor chooseAccountTypesPage_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor chooseAccountTypesPage_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor chooseAccountTypesPage_title_color = { 0, 65535, 65535, 65535 };
  GtkWidget *druid_vbox1;
  GtkWidget *pickAccountsDescriptionLabel;
  GtkWidget *scrolledwindow1;
  GtkWidget *newAccountTypesList;
  GtkWidget *newAccountTypesList_TypeLabel;
  GtkWidget *newAccountTypesList_DescriptionLabel;
  GtkWidget *hbox1;
  GtkWidget *scrolledwindow2;
  GtkWidget *accountTypesDescription;
  GtkWidget *scrolledwindow3;
  GtkWidget *viewport1;
  GtkWidget *newAccountListTree;
  GtkWidget *hbox3;
  GtkWidget *newAccountsTypeList_SelectAllButton;
  GtkWidget *newAccountsTypeList_ClearAllButton;
  GtkWidget *finalAccountDruidPage;
  GdkColor finalAccountDruidPage_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor finalAccountDruidPage_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor finalAccountDruidPage_title_color = { 0, 65535, 65535, 65535 };
  GtkWidget *druid_vbox3;
  GtkWidget *label6;
  GtkWidget *hbox4;
  GtkWidget *scrolledwindow4;
  GtkWidget *ctree1;
  GtkWidget *checkAccountList_AccountNameLabel;
  GtkWidget *checkAccountList_TypeLabel;
  GtkWidget *checkAccountList_StartBalanceLabel;
  GtkWidget *vbox5;
  GtkWidget *checkAccount_AccountLabel;
  GtkWidget *checkAccount_StartBalanceLabel;
  GtkWidget *checkAccount_StartBalanceEntry;
  GtkWidget *newUserDruidFinishPage;
  GdkColor newUserDruidFinishPage_bg_color = { 0, 6425, 6425, 28784 };
  GdkColor newUserDruidFinishPage_textbox_color = { 0, 65535, 65535, 65535 };
  GdkColor newUserDruidFinishPage_logo_bg_color = { 0, 65535, 65535, 65535 };
  GdkColor newUserDruidFinishPage_title_color = { 0, 65535, 65535, 65535 };

  newUserDialog = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (newUserDialog, "newUserDialog");
  gtk_object_set_data (GTK_OBJECT (newUserDialog), "newUserDialog", newUserDialog);
  gtk_widget_set_usize (newUserDialog, 540, 370);
  gtk_window_set_title (GTK_WINDOW (newUserDialog), _("New User Account setup"));
  gtk_window_set_default_size (GTK_WINDOW (newUserDialog), 640, 480);

  accountChooseDruidPage = gnome_druid_new ();
  gtk_widget_set_name (accountChooseDruidPage, "accountChooseDruidPage");
  gtk_widget_ref (accountChooseDruidPage);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "accountChooseDruidPage", accountChooseDruidPage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (accountChooseDruidPage);
  gtk_container_add (GTK_CONTAINER (newUserDialog), accountChooseDruidPage);

  newUserStartPage = gnome_druid_page_start_new ();
  gtk_widget_set_name (newUserStartPage, "newUserStartPage");
  gtk_widget_ref (newUserStartPage);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newUserStartPage", newUserStartPage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newUserStartPage);
  gnome_druid_append_page (GNOME_DRUID (accountChooseDruidPage), GNOME_DRUID_PAGE (newUserStartPage));
  gnome_druid_set_page (GNOME_DRUID (accountChooseDruidPage), GNOME_DRUID_PAGE (newUserStartPage));
  gnome_druid_page_start_set_bg_color (GNOME_DRUID_PAGE_START (newUserStartPage), &newUserStartPage_bg_color);
  gnome_druid_page_start_set_textbox_color (GNOME_DRUID_PAGE_START (newUserStartPage), &newUserStartPage_textbox_color);
  gnome_druid_page_start_set_logo_bg_color (GNOME_DRUID_PAGE_START (newUserStartPage), &newUserStartPage_logo_bg_color);
  gnome_druid_page_start_set_title_color (GNOME_DRUID_PAGE_START (newUserStartPage), &newUserStartPage_title_color);
  gnome_druid_page_start_set_title (GNOME_DRUID_PAGE_START (newUserStartPage), _("New User Account Setup"));
  gnome_druid_page_start_set_text (GNOME_DRUID_PAGE_START (newUserStartPage), _("This wizard will help you to set up a default set of accounts to use."));

  newAccountCurrencyChoosePage = gnome_druid_page_standard_new_with_vals ("", NULL);
  gtk_widget_set_name (newAccountCurrencyChoosePage, "newAccountCurrencyChoosePage");
  gtk_widget_ref (newAccountCurrencyChoosePage);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountCurrencyChoosePage", newAccountCurrencyChoosePage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show_all (newAccountCurrencyChoosePage);
  gnome_druid_append_page (GNOME_DRUID (accountChooseDruidPage), GNOME_DRUID_PAGE (newAccountCurrencyChoosePage));
  gnome_druid_page_standard_set_bg_color (GNOME_DRUID_PAGE_STANDARD (newAccountCurrencyChoosePage), &newAccountCurrencyChoosePage_bg_color);
  gnome_druid_page_standard_set_logo_bg_color (GNOME_DRUID_PAGE_STANDARD (newAccountCurrencyChoosePage), &newAccountCurrencyChoosePage_logo_bg_color);
  gnome_druid_page_standard_set_title_color (GNOME_DRUID_PAGE_STANDARD (newAccountCurrencyChoosePage), &newAccountCurrencyChoosePage_title_color);
  gnome_druid_page_standard_set_title (GNOME_DRUID_PAGE_STANDARD (newAccountCurrencyChoosePage), _("Choose Currency"));

  newAccountCurrencyChooser_vbox2 = GNOME_DRUID_PAGE_STANDARD (newAccountCurrencyChoosePage)->vbox;
  gtk_widget_set_name (newAccountCurrencyChooser_vbox2, "newAccountCurrencyChooser_vbox2");
  gtk_widget_ref (newAccountCurrencyChooser_vbox2);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountCurrencyChooser_vbox2", newAccountCurrencyChooser_vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountCurrencyChooser_vbox2);
  gtk_container_set_border_width (GTK_CONTAINER (newAccountCurrencyChooser_vbox2), 5);

  newUserChooseCurrencyDescrip = gtk_label_new (_("Please choose the currency to use for new accounts."));
  gtk_widget_set_name (newUserChooseCurrencyDescrip, "newUserChooseCurrencyDescrip");
  gtk_widget_ref (newUserChooseCurrencyDescrip);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newUserChooseCurrencyDescrip", newUserChooseCurrencyDescrip,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newUserChooseCurrencyDescrip);
  gtk_box_pack_start (GTK_BOX (newAccountCurrencyChooser_vbox2), newUserChooseCurrencyDescrip, FALSE, FALSE, 0);

  newAccountCurrencyChooser_vbox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (newAccountCurrencyChooser_vbox, "newAccountCurrencyChooser_vbox");
  gtk_widget_ref (newAccountCurrencyChooser_vbox);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountCurrencyChooser_vbox", newAccountCurrencyChooser_vbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountCurrencyChooser_vbox);
  gtk_box_pack_start (GTK_BOX (newAccountCurrencyChooser_vbox2), newAccountCurrencyChooser_vbox, FALSE, FALSE, 0);

  chooseAccountTypesPage = gnome_druid_page_standard_new_with_vals ("", NULL);
  gtk_widget_set_name (chooseAccountTypesPage, "chooseAccountTypesPage");
  gtk_widget_ref (chooseAccountTypesPage);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "chooseAccountTypesPage", chooseAccountTypesPage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show_all (chooseAccountTypesPage);
  gnome_druid_append_page (GNOME_DRUID (accountChooseDruidPage), GNOME_DRUID_PAGE (chooseAccountTypesPage));
  gnome_druid_page_standard_set_bg_color (GNOME_DRUID_PAGE_STANDARD (chooseAccountTypesPage), &chooseAccountTypesPage_bg_color);
  gnome_druid_page_standard_set_logo_bg_color (GNOME_DRUID_PAGE_STANDARD (chooseAccountTypesPage), &chooseAccountTypesPage_logo_bg_color);
  gnome_druid_page_standard_set_title_color (GNOME_DRUID_PAGE_STANDARD (chooseAccountTypesPage), &chooseAccountTypesPage_title_color);
  gnome_druid_page_standard_set_title (GNOME_DRUID_PAGE_STANDARD (chooseAccountTypesPage), _("Choose Account Types"));

  druid_vbox1 = GNOME_DRUID_PAGE_STANDARD (chooseAccountTypesPage)->vbox;
  gtk_widget_set_name (druid_vbox1, "druid_vbox1");
  gtk_widget_ref (druid_vbox1);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "druid_vbox1", druid_vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (druid_vbox1);
  gtk_container_set_border_width (GTK_CONTAINER (druid_vbox1), 5);

  pickAccountsDescriptionLabel = gtk_label_new (_("Please choose the account types you would like to have automatically setup in GnuCash."));
  gtk_widget_set_name (pickAccountsDescriptionLabel, "pickAccountsDescriptionLabel");
  gtk_widget_ref (pickAccountsDescriptionLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "pickAccountsDescriptionLabel", pickAccountsDescriptionLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (pickAccountsDescriptionLabel);
  gtk_box_pack_start (GTK_BOX (druid_vbox1), pickAccountsDescriptionLabel, FALSE, FALSE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow1, "scrolledwindow1");
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_box_pack_start (GTK_BOX (druid_vbox1), scrolledwindow1, TRUE, TRUE, 0);

  newAccountTypesList = gtk_clist_new (2);
  gtk_widget_set_name (newAccountTypesList, "newAccountTypesList");
  gtk_widget_ref (newAccountTypesList);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountTypesList", newAccountTypesList,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTypesList);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), newAccountTypesList);
  gtk_clist_set_column_width (GTK_CLIST (newAccountTypesList), 0, 144);
  gtk_clist_set_column_width (GTK_CLIST (newAccountTypesList), 1, 80);
  gtk_clist_set_selection_mode (GTK_CLIST (newAccountTypesList), GTK_SELECTION_MULTIPLE);
  gtk_clist_column_titles_show (GTK_CLIST (newAccountTypesList));

  newAccountTypesList_TypeLabel = gtk_label_new (_("Account List Type"));
  gtk_widget_set_name (newAccountTypesList_TypeLabel, "newAccountTypesList_TypeLabel");
  gtk_widget_ref (newAccountTypesList_TypeLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountTypesList_TypeLabel", newAccountTypesList_TypeLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTypesList_TypeLabel);
  gtk_clist_set_column_widget (GTK_CLIST (newAccountTypesList), 0, newAccountTypesList_TypeLabel);

  newAccountTypesList_DescriptionLabel = gtk_label_new (_("Description"));
  gtk_widget_set_name (newAccountTypesList_DescriptionLabel, "newAccountTypesList_DescriptionLabel");
  gtk_widget_ref (newAccountTypesList_DescriptionLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountTypesList_DescriptionLabel", newAccountTypesList_DescriptionLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTypesList_DescriptionLabel);
  gtk_clist_set_column_widget (GTK_CLIST (newAccountTypesList), 1, newAccountTypesList_DescriptionLabel);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox1, "hbox1");
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (druid_vbox1), hbox1, TRUE, TRUE, 0);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow2, "scrolledwindow2");
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  accountTypesDescription = gtk_text_new (NULL, NULL);
  gtk_widget_set_name (accountTypesDescription, "accountTypesDescription");
  gtk_widget_ref (accountTypesDescription);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "accountTypesDescription", accountTypesDescription,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (accountTypesDescription);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), accountTypesDescription);
  gtk_widget_set_sensitive (accountTypesDescription, FALSE);
  GTK_WIDGET_UNSET_FLAGS (accountTypesDescription, GTK_CAN_FOCUS);

  scrolledwindow3 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow3, "scrolledwindow3");
  gtk_widget_ref (scrolledwindow3);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "scrolledwindow3", scrolledwindow3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow3);
  gtk_box_pack_start (GTK_BOX (hbox1), scrolledwindow3, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow3), GTK_POLICY_NEVER, GTK_POLICY_ALWAYS);

  viewport1 = gtk_viewport_new (NULL, NULL);
  gtk_widget_set_name (viewport1, "viewport1");
  gtk_widget_ref (viewport1);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "viewport1", viewport1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (viewport1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow3), viewport1);

  newAccountListTree = gtk_tree_new ();
  gtk_widget_set_name (newAccountListTree, "newAccountListTree");
  gtk_widget_ref (newAccountListTree);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountListTree", newAccountListTree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountListTree);
  gtk_container_add (GTK_CONTAINER (viewport1), newAccountListTree);
  gtk_widget_set_sensitive (newAccountListTree, FALSE);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox3, "hbox3");
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (druid_vbox1), hbox3, FALSE, TRUE, 0);

  newAccountsTypeList_SelectAllButton = gtk_button_new_with_label (_("Select All"));
  gtk_widget_set_name (newAccountsTypeList_SelectAllButton, "newAccountsTypeList_SelectAllButton");
  gtk_widget_ref (newAccountsTypeList_SelectAllButton);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountsTypeList_SelectAllButton", newAccountsTypeList_SelectAllButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountsTypeList_SelectAllButton);
  gtk_box_pack_start (GTK_BOX (hbox3), newAccountsTypeList_SelectAllButton, TRUE, FALSE, 0);

  newAccountsTypeList_ClearAllButton = gtk_button_new_with_label (_("Clear All"));
  gtk_widget_set_name (newAccountsTypeList_ClearAllButton, "newAccountsTypeList_ClearAllButton");
  gtk_widget_ref (newAccountsTypeList_ClearAllButton);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newAccountsTypeList_ClearAllButton", newAccountsTypeList_ClearAllButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountsTypeList_ClearAllButton);
  gtk_box_pack_start (GTK_BOX (hbox3), newAccountsTypeList_ClearAllButton, TRUE, FALSE, 0);

  finalAccountDruidPage = gnome_druid_page_standard_new_with_vals ("", NULL);
  gtk_widget_set_name (finalAccountDruidPage, "finalAccountDruidPage");
  gtk_widget_ref (finalAccountDruidPage);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "finalAccountDruidPage", finalAccountDruidPage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show_all (finalAccountDruidPage);
  gnome_druid_append_page (GNOME_DRUID (accountChooseDruidPage), GNOME_DRUID_PAGE (finalAccountDruidPage));
  gnome_druid_page_standard_set_bg_color (GNOME_DRUID_PAGE_STANDARD (finalAccountDruidPage), &finalAccountDruidPage_bg_color);
  gnome_druid_page_standard_set_logo_bg_color (GNOME_DRUID_PAGE_STANDARD (finalAccountDruidPage), &finalAccountDruidPage_logo_bg_color);
  gnome_druid_page_standard_set_title_color (GNOME_DRUID_PAGE_STANDARD (finalAccountDruidPage), &finalAccountDruidPage_title_color);
  gnome_druid_page_standard_set_title (GNOME_DRUID_PAGE_STANDARD (finalAccountDruidPage), _("Check and Enter Final Account Info"));

  druid_vbox3 = GNOME_DRUID_PAGE_STANDARD (finalAccountDruidPage)->vbox;
  gtk_widget_set_name (druid_vbox3, "druid_vbox3");
  gtk_widget_ref (druid_vbox3);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "druid_vbox3", druid_vbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (druid_vbox3);

  label6 = gtk_label_new (_("If you would like the accounts to have a starting balance click on the account line and enter the starting balance in the text entry box on the right."));
  gtk_widget_set_name (label6, "label6");
  gtk_widget_ref (label6);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "label6", label6,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (druid_vbox3), label6, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label6), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (label6), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label6), 0.0800003, 0.08);
  gtk_misc_set_padding (GTK_MISC (label6), 1, 1);

  hbox4 = gtk_hbox_new (FALSE, 0);
  gtk_widget_set_name (hbox4, "hbox4");
  gtk_widget_ref (hbox4);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "hbox4", hbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox4);
  gtk_box_pack_start (GTK_BOX (druid_vbox3), hbox4, TRUE, TRUE, 0);

  scrolledwindow4 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (scrolledwindow4, "scrolledwindow4");
  gtk_widget_ref (scrolledwindow4);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "scrolledwindow4", scrolledwindow4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow4);
  gtk_box_pack_start (GTK_BOX (hbox4), scrolledwindow4, TRUE, TRUE, 0);

  ctree1 = gtk_ctree_new (3, 0);
  gtk_widget_set_name (ctree1, "ctree1");
  gtk_widget_ref (ctree1);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "ctree1", ctree1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (ctree1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow4), ctree1);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 0, 285);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 1, 118);
  gtk_clist_set_column_width (GTK_CLIST (ctree1), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (ctree1));

  checkAccountList_AccountNameLabel = gtk_label_new (_("Account Name"));
  gtk_widget_set_name (checkAccountList_AccountNameLabel, "checkAccountList_AccountNameLabel");
  gtk_widget_ref (checkAccountList_AccountNameLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "checkAccountList_AccountNameLabel", checkAccountList_AccountNameLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkAccountList_AccountNameLabel);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 0, checkAccountList_AccountNameLabel);

  checkAccountList_TypeLabel = gtk_label_new (_("Type"));
  gtk_widget_set_name (checkAccountList_TypeLabel, "checkAccountList_TypeLabel");
  gtk_widget_ref (checkAccountList_TypeLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "checkAccountList_TypeLabel", checkAccountList_TypeLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkAccountList_TypeLabel);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 1, checkAccountList_TypeLabel);

  checkAccountList_StartBalanceLabel = gtk_label_new (_("Starting Balance"));
  gtk_widget_set_name (checkAccountList_StartBalanceLabel, "checkAccountList_StartBalanceLabel");
  gtk_widget_ref (checkAccountList_StartBalanceLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "checkAccountList_StartBalanceLabel", checkAccountList_StartBalanceLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkAccountList_StartBalanceLabel);
  gtk_clist_set_column_widget (GTK_CLIST (ctree1), 2, checkAccountList_StartBalanceLabel);

  vbox5 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox5, "vbox5");
  gtk_widget_ref (vbox5);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "vbox5", vbox5,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox5);
  gtk_box_pack_start (GTK_BOX (hbox4), vbox5, FALSE, TRUE, 0);

  checkAccount_AccountLabel = gtk_label_new (_("Account:"));
  gtk_widget_set_name (checkAccount_AccountLabel, "checkAccount_AccountLabel");
  gtk_widget_ref (checkAccount_AccountLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "checkAccount_AccountLabel", checkAccount_AccountLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkAccount_AccountLabel);
  gtk_box_pack_start (GTK_BOX (vbox5), checkAccount_AccountLabel, FALSE, FALSE, 0);

  checkAccount_StartBalanceLabel = gtk_label_new (_("Enter Starting Balance"));
  gtk_widget_set_name (checkAccount_StartBalanceLabel, "checkAccount_StartBalanceLabel");
  gtk_widget_ref (checkAccount_StartBalanceLabel);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "checkAccount_StartBalanceLabel", checkAccount_StartBalanceLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkAccount_StartBalanceLabel);
  gtk_box_pack_start (GTK_BOX (vbox5), checkAccount_StartBalanceLabel, FALSE, FALSE, 0);

  checkAccount_StartBalanceEntry = gtk_entry_new_with_max_length (20);
  gtk_widget_set_name (checkAccount_StartBalanceEntry, "checkAccount_StartBalanceEntry");
  gtk_widget_ref (checkAccount_StartBalanceEntry);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "checkAccount_StartBalanceEntry", checkAccount_StartBalanceEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (checkAccount_StartBalanceEntry);
  gtk_box_pack_start (GTK_BOX (vbox5), checkAccount_StartBalanceEntry, FALSE, FALSE, 0);

  newUserDruidFinishPage = gnome_druid_page_finish_new ();
  gtk_widget_set_name (newUserDruidFinishPage, "newUserDruidFinishPage");
  gtk_widget_ref (newUserDruidFinishPage);
  gtk_object_set_data_full (GTK_OBJECT (newUserDialog), "newUserDruidFinishPage", newUserDruidFinishPage,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newUserDruidFinishPage);
  gnome_druid_append_page (GNOME_DRUID (accountChooseDruidPage), GNOME_DRUID_PAGE (newUserDruidFinishPage));
  gnome_druid_page_finish_set_bg_color (GNOME_DRUID_PAGE_FINISH (newUserDruidFinishPage), &newUserDruidFinishPage_bg_color);
  gnome_druid_page_finish_set_textbox_color (GNOME_DRUID_PAGE_FINISH (newUserDruidFinishPage), &newUserDruidFinishPage_textbox_color);
  gnome_druid_page_finish_set_logo_bg_color (GNOME_DRUID_PAGE_FINISH (newUserDruidFinishPage), &newUserDruidFinishPage_logo_bg_color);
  gnome_druid_page_finish_set_title_color (GNOME_DRUID_PAGE_FINISH (newUserDruidFinishPage), &newUserDruidFinishPage_title_color);
  gnome_druid_page_finish_set_title (GNOME_DRUID_PAGE_FINISH (newUserDruidFinishPage), _("Finish Account Setup"));
  gnome_druid_page_finish_set_text (GNOME_DRUID_PAGE_FINISH (newUserDruidFinishPage), _("Press `Finish' if everything is OK."));

  gtk_signal_connect (GTK_OBJECT (accountChooseDruidPage), "cancel",
                      GTK_SIGNAL_FUNC (on_accountChooseDruidPage_cancel),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newUserStartPage), "next",
                      GTK_SIGNAL_FUNC (on_newUserStartPage_next),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newAccountCurrencyChoosePage), "prepare",
                      GTK_SIGNAL_FUNC (on_newAccountCurrencyChoosePage_prepare),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newAccountCurrencyChoosePage), "next",
                      GTK_SIGNAL_FUNC (on_newAccountCurrencyChoosePage_next),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (chooseAccountTypesPage), "next",
                      GTK_SIGNAL_FUNC (on_chooseAccountTypesPage_next),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (chooseAccountTypesPage), "prepare",
                      GTK_SIGNAL_FUNC (on_chooseAccountTypesPage_prepare),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newAccountTypesList), "select_row",
                      GTK_SIGNAL_FUNC (on_newAccountTypesList_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newAccountsTypeList_SelectAllButton), "clicked",
                      GTK_SIGNAL_FUNC (on_newAccountsTypeList_SelectAllButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (finalAccountDruidPage), "prepare",
                      GTK_SIGNAL_FUNC (on_finalAccountDruidPage_prepare),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (ctree1), "select_row",
                      GTK_SIGNAL_FUNC (on_ctree1_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newUserDruidFinishPage), "finish",
                      GTK_SIGNAL_FUNC (on_newUserDruidFinishPage_finish),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newUserDruidFinishPage), "prepare",
                      GTK_SIGNAL_FUNC (on_newUserDruidFinishPage_prepare),
                      NULL);

  return newUserDialog;
}

GtkWidget*
create_newAccountList (void)
{
  GtkWidget *newAccountList;
  GtkWidget *newAccountTopVBox;
  GtkWidget *newAccountLable;
  GtkWidget *newAccountHPaned;
  GtkWidget *newAccountTreeScrolledWindow;
  GtkWidget *newAccountTree;
  GtkWidget *newAccountTreeAccountLabel;
  GtkWidget *newAccountTreeDestriptionLabel;
  GtkWidget *newAccountTreeStartingBalanceLabel;
  GtkWidget *vbox4;
  GtkWidget *newAccountAccountNameLabel;
  GtkWidget *newAccountEnterStartingBalanceLabel;
  GtkWidget *newAccountStartingBalanceEntry;
  GtkWidget *hbox2;
  GtkWidget *newAccountSelectAllButton;
  GtkWidget *newAccountOKButton;

  newAccountList = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_name (newAccountList, "newAccountList");
  gtk_object_set_data (GTK_OBJECT (newAccountList), "newAccountList", newAccountList);
  gtk_widget_set_usize (newAccountList, 200, 400);
  gtk_window_set_title (GTK_WINDOW (newAccountList), _("New Account List"));
  gtk_window_set_default_size (GTK_WINDOW (newAccountList), 640, 480);

  newAccountTopVBox = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (newAccountTopVBox, "newAccountTopVBox");
  gtk_widget_ref (newAccountTopVBox);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountTopVBox", newAccountTopVBox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTopVBox);
  gtk_container_add (GTK_CONTAINER (newAccountList), newAccountTopVBox);

  newAccountLable = gtk_label_new (_("If you would like the accounts to have a starting balance click on the account line and enter the starting balance in the text entry box on the right."));
  gtk_widget_set_name (newAccountLable, "newAccountLable");
  gtk_widget_ref (newAccountLable);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountLable", newAccountLable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountLable);
  gtk_box_pack_start (GTK_BOX (newAccountTopVBox), newAccountLable, FALSE, TRUE, 0);
  gtk_label_set_justify (GTK_LABEL (newAccountLable), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (newAccountLable), TRUE);
  gtk_misc_set_alignment (GTK_MISC (newAccountLable), 0.0800003, 0.08);
  gtk_misc_set_padding (GTK_MISC (newAccountLable), 1, 1);

  newAccountHPaned = gtk_hpaned_new ();
  gtk_widget_set_name (newAccountHPaned, "newAccountHPaned");
  gtk_widget_ref (newAccountHPaned);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountHPaned", newAccountHPaned,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountHPaned);
  gtk_box_pack_start (GTK_BOX (newAccountTopVBox), newAccountHPaned, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (newAccountHPaned), 1);

  newAccountTreeScrolledWindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_set_name (newAccountTreeScrolledWindow, "newAccountTreeScrolledWindow");
  gtk_widget_ref (newAccountTreeScrolledWindow);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountTreeScrolledWindow", newAccountTreeScrolledWindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTreeScrolledWindow);
  gtk_paned_pack1 (GTK_PANED (newAccountHPaned), newAccountTreeScrolledWindow, FALSE, FALSE);

  newAccountTree = gtk_ctree_new (3, 0);
  gtk_widget_set_name (newAccountTree, "newAccountTree");
  gtk_widget_ref (newAccountTree);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountTree", newAccountTree,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTree);
  gtk_container_add (GTK_CONTAINER (newAccountTreeScrolledWindow), newAccountTree);
  gtk_clist_set_column_width (GTK_CLIST (newAccountTree), 0, 86);
  gtk_clist_set_column_width (GTK_CLIST (newAccountTree), 1, 233);
  gtk_clist_set_column_width (GTK_CLIST (newAccountTree), 2, 80);
  gtk_clist_column_titles_show (GTK_CLIST (newAccountTree));

  newAccountTreeAccountLabel = gtk_label_new (_("Account Name"));
  gtk_widget_set_name (newAccountTreeAccountLabel, "newAccountTreeAccountLabel");
  gtk_widget_ref (newAccountTreeAccountLabel);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountTreeAccountLabel", newAccountTreeAccountLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTreeAccountLabel);
  gtk_clist_set_column_widget (GTK_CLIST (newAccountTree), 0, newAccountTreeAccountLabel);

  newAccountTreeDestriptionLabel = gtk_label_new (_("Description"));
  gtk_widget_set_name (newAccountTreeDestriptionLabel, "newAccountTreeDestriptionLabel");
  gtk_widget_ref (newAccountTreeDestriptionLabel);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountTreeDestriptionLabel", newAccountTreeDestriptionLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTreeDestriptionLabel);
  gtk_clist_set_column_widget (GTK_CLIST (newAccountTree), 1, newAccountTreeDestriptionLabel);

  newAccountTreeStartingBalanceLabel = gtk_label_new (_("Starting Balance"));
  gtk_widget_set_name (newAccountTreeStartingBalanceLabel, "newAccountTreeStartingBalanceLabel");
  gtk_widget_ref (newAccountTreeStartingBalanceLabel);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountTreeStartingBalanceLabel", newAccountTreeStartingBalanceLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountTreeStartingBalanceLabel);
  gtk_clist_set_column_widget (GTK_CLIST (newAccountTree), 2, newAccountTreeStartingBalanceLabel);

  vbox4 = gtk_vbox_new (FALSE, 0);
  gtk_widget_set_name (vbox4, "vbox4");
  gtk_widget_ref (vbox4);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "vbox4", vbox4,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox4);
  gtk_paned_pack2 (GTK_PANED (newAccountHPaned), vbox4, TRUE, TRUE);

  newAccountAccountNameLabel = gtk_label_new (_("Account: "));
  gtk_widget_set_name (newAccountAccountNameLabel, "newAccountAccountNameLabel");
  gtk_widget_ref (newAccountAccountNameLabel);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountAccountNameLabel", newAccountAccountNameLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountAccountNameLabel);
  gtk_box_pack_start (GTK_BOX (vbox4), newAccountAccountNameLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (newAccountAccountNameLabel), GTK_JUSTIFY_RIGHT);
  gtk_label_set_line_wrap (GTK_LABEL (newAccountAccountNameLabel), TRUE);
  gtk_misc_set_alignment (GTK_MISC (newAccountAccountNameLabel), 0.49, 0.5);

  newAccountEnterStartingBalanceLabel = gtk_label_new (_("Enter Starting Balance"));
  gtk_widget_set_name (newAccountEnterStartingBalanceLabel, "newAccountEnterStartingBalanceLabel");
  gtk_widget_ref (newAccountEnterStartingBalanceLabel);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountEnterStartingBalanceLabel", newAccountEnterStartingBalanceLabel,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountEnterStartingBalanceLabel);
  gtk_box_pack_start (GTK_BOX (vbox4), newAccountEnterStartingBalanceLabel, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (newAccountEnterStartingBalanceLabel), GTK_JUSTIFY_RIGHT);

  newAccountStartingBalanceEntry = gtk_entry_new ();
  gtk_widget_set_name (newAccountStartingBalanceEntry, "newAccountStartingBalanceEntry");
  gtk_widget_ref (newAccountStartingBalanceEntry);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountStartingBalanceEntry", newAccountStartingBalanceEntry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountStartingBalanceEntry);
  gtk_box_pack_start (GTK_BOX (vbox4), newAccountStartingBalanceEntry, FALSE, FALSE, 0);
  gtk_widget_set_usize (newAccountStartingBalanceEntry, 100, -2);

  hbox2 = gtk_hbox_new (FALSE, 5);
  gtk_widget_set_name (hbox2, "hbox2");
  gtk_widget_ref (hbox2);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "hbox2", hbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (newAccountTopVBox), hbox2, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox2), 5);

  newAccountSelectAllButton = gtk_button_new_with_label (_("Select All"));
  gtk_widget_set_name (newAccountSelectAllButton, "newAccountSelectAllButton");
  gtk_widget_ref (newAccountSelectAllButton);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountSelectAllButton", newAccountSelectAllButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountSelectAllButton);
  gtk_box_pack_start (GTK_BOX (hbox2), newAccountSelectAllButton, FALSE, FALSE, 5);

  newAccountOKButton = gtk_button_new_with_label (_("OK"));
  gtk_widget_set_name (newAccountOKButton, "newAccountOKButton");
  gtk_widget_ref (newAccountOKButton);
  gtk_object_set_data_full (GTK_OBJECT (newAccountList), "newAccountOKButton", newAccountOKButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountOKButton);
  gtk_box_pack_start (GTK_BOX (hbox2), newAccountOKButton, FALSE, FALSE, 5);

  gtk_signal_connect (GTK_OBJECT (newAccountTree), "select_row",
                      GTK_SIGNAL_FUNC (on_newAccountTree_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newAccountSelectAllButton), "clicked",
                      GTK_SIGNAL_FUNC (on_newAccountSelectAllButton_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (newAccountOKButton), "clicked",
                      GTK_SIGNAL_FUNC (on_newAccountOKButton_clicked),
                      NULL);

  return newAccountList;
}

GtkWidget*
create_addAccountCancelDialog (void)
{
  GtkWidget *addAccountCancelDialog;
  GtkWidget *newAccountCancelDialog;
  GtkWidget *vbox1;
  GtkWidget *newAccountCancelDialog_ShouldRunAgainLable;
  GtkWidget *newAccountCancelDialog_RunAgainToggle;
  GtkWidget *dialog_action_area1;
  GtkWidget *newAccountCancelDialog_OKButton;

  addAccountCancelDialog = gnome_dialog_new (_("Canceling"), NULL);
  gtk_widget_set_name (addAccountCancelDialog, "addAccountCancelDialog");
  gtk_object_set_data (GTK_OBJECT (addAccountCancelDialog), "addAccountCancelDialog", addAccountCancelDialog);
  GTK_WINDOW (addAccountCancelDialog)->type = GTK_WINDOW_DIALOG;
  gtk_window_set_position (GTK_WINDOW (addAccountCancelDialog), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (addAccountCancelDialog), TRUE);
  gtk_window_set_policy (GTK_WINDOW (addAccountCancelDialog), FALSE, FALSE, FALSE);

  newAccountCancelDialog = GNOME_DIALOG (addAccountCancelDialog)->vbox;
  gtk_widget_set_name (newAccountCancelDialog, "newAccountCancelDialog");
  gtk_object_set_data (GTK_OBJECT (addAccountCancelDialog), "newAccountCancelDialog", newAccountCancelDialog);
  gtk_widget_show (newAccountCancelDialog);

  vbox1 = gtk_vbox_new (FALSE, 5);
  gtk_widget_set_name (vbox1, "vbox1");
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (addAccountCancelDialog), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_box_pack_start (GTK_BOX (newAccountCancelDialog), vbox1, TRUE, TRUE, 0);

  newAccountCancelDialog_ShouldRunAgainLable = gtk_label_new (_("Uncheck if you do not want this new user dialog to run again."));
  gtk_widget_set_name (newAccountCancelDialog_ShouldRunAgainLable, "newAccountCancelDialog_ShouldRunAgainLable");
  gtk_widget_ref (newAccountCancelDialog_ShouldRunAgainLable);
  gtk_object_set_data_full (GTK_OBJECT (addAccountCancelDialog), "newAccountCancelDialog_ShouldRunAgainLable", newAccountCancelDialog_ShouldRunAgainLable,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountCancelDialog_ShouldRunAgainLable);
  gtk_box_pack_start (GTK_BOX (vbox1), newAccountCancelDialog_ShouldRunAgainLable, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (newAccountCancelDialog_ShouldRunAgainLable), GTK_JUSTIFY_FILL);
  gtk_label_set_line_wrap (GTK_LABEL (newAccountCancelDialog_ShouldRunAgainLable), TRUE);

  newAccountCancelDialog_RunAgainToggle = gtk_check_button_new_with_label (_("Run New User Account Setup again?"));
  gtk_widget_set_name (newAccountCancelDialog_RunAgainToggle, "newAccountCancelDialog_RunAgainToggle");
  gtk_widget_ref (newAccountCancelDialog_RunAgainToggle);
  gtk_object_set_data_full (GTK_OBJECT (addAccountCancelDialog), "newAccountCancelDialog_RunAgainToggle", newAccountCancelDialog_RunAgainToggle,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountCancelDialog_RunAgainToggle);
  gtk_box_pack_start (GTK_BOX (vbox1), newAccountCancelDialog_RunAgainToggle, FALSE, FALSE, 0);
  gtk_toggle_button_set_active (GTK_TOGGLE_BUTTON (newAccountCancelDialog_RunAgainToggle), TRUE);

  dialog_action_area1 = GNOME_DIALOG (addAccountCancelDialog)->action_area;
  gtk_widget_set_name (dialog_action_area1, "dialog_action_area1");
  gtk_object_set_data (GTK_OBJECT (addAccountCancelDialog), "dialog_action_area1", dialog_action_area1);
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_spacing (GTK_BUTTON_BOX (dialog_action_area1), 8);

  gnome_dialog_append_button (GNOME_DIALOG (addAccountCancelDialog), GNOME_STOCK_BUTTON_OK);
  newAccountCancelDialog_OKButton = GTK_WIDGET (g_list_last (GNOME_DIALOG (addAccountCancelDialog)->buttons)->data);
  gtk_widget_set_name (newAccountCancelDialog_OKButton, "newAccountCancelDialog_OKButton");
  gtk_widget_ref (newAccountCancelDialog_OKButton);
  gtk_object_set_data_full (GTK_OBJECT (addAccountCancelDialog), "newAccountCancelDialog_OKButton", newAccountCancelDialog_OKButton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (newAccountCancelDialog_OKButton);
  GTK_WIDGET_SET_FLAGS (newAccountCancelDialog_OKButton, GTK_CAN_DEFAULT);

  gtk_signal_connect (GTK_OBJECT (newAccountCancelDialog_OKButton), "clicked",
                      GTK_SIGNAL_FUNC (on_newAccountCancelDialog_OKButton_clicked),
                      NULL);

  return addAccountCancelDialog;
}

