#! /bin/sh 
exec guile -s "$0"
!#

(display "  testing stylesheet module load ... ")
(use-modules (gnucash gnc-module))
(gnc:module-system-init)

(if (gnc:module-load "gnucash/report/stylesheets" 0)
    (begin 
      (display "ok\n")
      (exit 0))
    (begin 
      (display "failed\n")
      (exit -1)))


 

