#!/bin/bash

if [[ "$BUILDTYPE" == "cmake-make" ]] || [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
    echo "########################";
    echo "##### LastTest.log #####";
    echo "########################";
    cat /build/Testing/Temporary/LastTest.log;
else
    echo "Unknown BUILDTYPE: \"$BUILDTYPE\", cannot create failure information.";
fi
# This script should fail so that the entire script will fail.
exit 1;
