#!/bin/bash

if [[ -d "/build/Testing" ]] ; then
    echo	
    echo "##################################################"
    echo "##### Rerunning failed tests in verbose mode #####"
    echo "##################################################"
    ctest -V --rerun-failed
else
    echo "Not rerunning tests. ctest hasn't run yet."
fi
# This script should fail so that the entire script will fail.
exit 1
