#!/bin/bash -e

mkdir -p "$HOME"/.local/share

mkdir build
cd build
export TZ="America/Los_Angeles"

if [[ "$BUILDTYPE" == "cmake-make" ]]; then
    cmake ../gnucash
    make -j 4
    make check || ../afterfailure
elif [[ "$BUILDTYPE" == "cmake-ninja" ]]; then
    cmake ../gnucash -DWITH_PYTHON=ON -DCMAKE_BUILD_TYPE=debug -G Ninja
    ninja
    ninja check || ../afterfailure;
elif [[ "$BUILDTYPE" == "autotools" ]]; then
    ../gnucash/autogen.sh;
    ../gnucash/configure --enable-python
    make;
    make check || ../afterfailure
else
    echo "Unknown buildtype: \"$BUILDTYPE\". Not building."
fi

