(debug-set! stack 50000)
(use-modules (gnucash report report-system list-extras))
(use-modules (gnucash report report-system test test-extras))

(define (run-test)
    (test test-list-min-max))

(define (test-list-min-max)
  (and (equal? (cons 1 1) (list-min-max (list 1) <))
       (equal? (cons 1 2) (list-min-max (list 1 2) <))       
       (equal? (cons 1 2) (list-min-max (list 2 1) <))       
       (equal? (cons 1 2) (list-min-max (list 1 1 2) <))
       (equal? (cons 1 2) (list-min-max (list 1 2 1) <))
       (equal? (cons 1 2) (list-min-max (list 1 2 2) <))
       (equal? (cons 1 2) (list-min-max (list 2 1 1) <))
       (equal? (cons 1 2) (list-min-max (list 2 2 1) <))
       (equal? (cons 1 3) (list-min-max (list 1 1 3) <))
       (equal? (cons 1 3) (list-min-max (list 1 2 3) <))
       (equal? (cons 1 3) (list-min-max (list 1 3 2) <))
       (equal? (cons 1 3) (list-min-max (list 2 3 1) <))
       (equal? (cons 1 3) (list-min-max (list 3 2 1) <))))
