print("Ah! The reviewer was right! Look at lines 573-575!")
print("paymentToAccts = g_list_append( paymentToAccts, GINT_TO_POINTER( paymentFroms[i] ) );")
print("This is EXACTLY the issue described! The issue description said:")
print("Issue: O(N^2) List Append in assistant-loan (ToAccts)")
print("Current Code:")
print("        for ( i = 0; i < toLen; i++ )")
print("        {")
print("            paymentToAccts = g_list_append( paymentToAccts,")
print("                                            GINT_TO_POINTER( paymentTos[i] ) );")
print("        }")
