#! /bin/sh

export GNC_BOOTSTRAP_SCM=./share/scm/bootstrap.scm
export GNC_SCM_LOAD_PATH='("./share/scm")'
export GNC_DEBUG=t

# Run whichever one was built last.
exec ./gnucash.bin \
 --debug \
 --share-dir ./share \
 --config-dir ./etc \
 --doc-path '("./Docs" "./Reports")' \
 "$@"
