"-- \n"
"-- FILE: \n"
"-- table-drop.sql \n"
"-- \n"
"-- FUNCTION: \n"
"-- Drop the tables needed to run GnuCash database \n"
" \n"
" \n"
"DROP TABLE gncCommodity; \n"
"DROP TABLE gncAccount; \n"
"DROP TABLE gncTransaction; \n"
"DROP TABLE gncEntry; \n"
"DROP TABLE gncCheckpoint; \n"
"DROP TABLE gncSession; \n"
"-- \n"
"DROP TABLE gncPathCache; \n"
"DROP TABLE gncGUIDCache; \n"
"DROP TABLE gncKVPvalue; \n"
"DROP TABLE gncKVPvalue_int64; \n"
"DROP TABLE gncKVPvalue_dbl; \n"
"DROP TABLE gncKVPvalue_numeric; \n"
"DROP TABLE gncKVPvalue_str; \n"
"DROP TABLE gncKVPvalue_guid; \n"
"DROP TABLE gncKVPvalue_timespec; \n"
"DROP TABLE gncKVPvalue_list; \n"
"DROP TABLE gncKVPvalue_frame;";
