#! /bin/sh
exec ${GUILE} -s "$0" 
!#

(define exit-code 0)
(setenv "GNC_UNINSTALLED" "1")
(use-modules (gnucash gnc-module))
(gnc:module-system-init)

(if (gnc:module-load "gnucash/app-utils" 0)
    (display "Module gnucash/app-utils loaded successfully\n")
    (begin
      (display "Failed - module gnucash/app-utils not loaded successfully\n")
      (set! exit-code -1)))

(if (procedure? gnc:error->string)
    (display "Procedure gnc:error->string found\n")
    (begin
      (display "Failed - procedure gnc:error->string not found\n")
      (set! exit-code -1)))

(if (procedure? gnc-default-currency)
    (display "Procedure gnc-default-currency found\n")
    (begin
      (display "Failed - procedure gnc-default-currency not found\n")
      (set! exit-code -1)))

(if (macro? (module-ref the-root-module 'N_))
    (display "Macro N_ defined\n")
    (begin
      (display "Failed - macro N_ not defined\n")
      (set! exit-code -1)))

(if (string=? (N_ "foobar") "foobar")
    (display "Macro N_ works properly\n")
    (begin
      (display "Failed - macro N_ doesn't work\n")
      (set! exit-code -1)))

(exit exit-code)
