# Generated automatically from Makefile.in by configure.
# Makefile -- makefile for xacc/src/engine/sql
# Copyright (C) 1997 Robin Clark                                   
# Copyright (C) 1998 Linas Vepstas                                 
# Copyright (C) 1998 Rob Browning <rlb@cs.utexas.edu>
#                                                                  
# This program is free software; you can redistribute it and/or    
# modify it under the terms of the GNU General Public License as   
# published by the Free Software Foundation; either version 2 of   
# the License, or (at your option) any later version.              
#                                                                  
# This program is distributed in the hope that it will be useful,  
# but WITHOUT ANY WARRANTY; without even the implied warranty of   
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the    
# GNU General Public License for more details.                     
#                                                                  
# You should have received a copy of the GNU General Public License
# along with this program; if not, contact:
#
# Free Software Foundation           Voice:  +1-617-542-5942
# 59 Temple Place - Suite 330        Fax:    +1-617-542-2652
# Boston, MA  02111-1307,  USA       gnu@gnu.org

INCLPATH = -I.		\
           -I..		\
           -I../..	\
           -I../../..	\
           -I../guid    \
           -I/usr/include

# add the -fpic flag to generate relocatable position independent code
# for the engine so that in can be used in a shared module (e.g. a perl module)
CFLAGS   = -g -O2 ${INCLPATH} -fpic
LIBS     = -lpq

######################################################################
# See Makefile.common for information about these variables.
INDEP_SRCS := PostgresBackend.c

######################################################################

all: default

# This inclusion must come after the first target, and after the
# definitions of *_SRCS, etc., but before the usage of *_OBJS.

default: ${OBJS}


.PHONY: all default


demo:	demo.c
	cc -o demo demo.c -lpq
