#! /bin/sh
echo "  test-scm-init: testing Scheme-only module system init. ";
exec ${GUILE} -s $0 "$@"
!#

(use-modules (gnucash unittest-support))
(define log-domain "gnc.module")
(define check (new-TestErrorStruct))
(define log-level (G-LOG-LEVEL-WARNING))
(define msg "Module '../../../src/gnc-module/test/misc-mods/.libs/libgncmod_futuremodsys.so' requires newer module system\n")
(TestErrorStruct-log-domain-set check log-domain)
(TestErrorStruct-log-level-set check log-level)
(TestErrorStruct-msg-set check msg)
(define handler (test-set-checked-handler log-domain log-level check))

(use-modules (gnucash gnc-module))
(gnc:module-system-init)

(g-log-remove-handler log-domain handler)

;; LocalVariables:
;; mode: scheme
;; End:
