#! /bin/sh
echo "  test-scm-dynload: testing dynamic-link of libgncmodule from Scheme.";
exec guile -s $0 "$@"
!#

(if (or (string=? (version) "1.3")
        (string=? (version) "1.3.4"))
    (dynamic-link "libgncmodule.so")
    (dynamic-link "libgncmodule"))

;; LocalVariables:
;; mode: scheme
;; End:


