#! /bin/sh
echo "  test-scm-dynload: testing dynamic-link of libgnc-module from Scheme.";
exec guile -s $0 "$@"
!#

(if (or (string=? (version) "1.3")
        (string=? (version) "1.3.4"))
    (dynamic-link "libgnc-module.so")
    (dynamic-link "libgnc-module"))

;; LocalVariables:
;; mode: scheme
;; End:


