.TH GSF-OFFICE-THUMBNAILER 1 "August 17, 2005" gsf "GNOME"
.SH NAME
gsf-office-thumbnailer \- office files thumbnailer for the GNOME desktop

.SH SYNOPSIS
\fBgsf-office-thumbnailer\fR [\fIOPTIONS\fR] \fIinfile\fR \fIoutfile\fR

.SH DESCRIPTION
This manual page briefly documents the \fBgsf-office-thumbnailer\fR command.

\fBgsf-office-thumbnailer\fR is used internally by GNOME applications such
as \fBnautilus\fR to generate thumbnails of several types of office
application files. While it is possible to invoke it manually, it is usually
invoked automatically by \fBnautilus\fR.

.\".SH "RETURN VALUE"
.\".SH "EXIT STATUS"
.\".SH "ERROR HANDLING"
.\".SH ERRORS
.SH OPTIONS
This program follows the usual GNU command line syntax, with single
letter options starting with a single dash (`-') and longer options
starting with two dashes (`--').

.SS "Main options"
.TP
.B \-i, \-\-input=\fIfilename\fR
Name of file for which to create a thumbnail
.TP
.B \-o, \-\-output=\fIfilename\fR
Name of the file in which to store the thumbnail
.TP
.B \-s, \-\-size=\fIN\fR
Size of thumbnail in pixels; the thumbnail will be at most N*N pixels large.

.SS "Help options"
.TP
.B \-?, \-\-help
Display a brief usage message

.\".SH USAGE
.\".SH EXAMPLES
.\".SH FILES
.\".SH ENVIRONMENT
.\".SH DIAGNOSTICS
.\".SH SECURITY
.\".SH CONFORMING TO
.\".SH NOTES
.\".SH BUGS

.SH LICENSE

\fBgsf-office-thumbnailer\fR is licensed under the terms of version 2.1 of
the GNU Lesser General Public License (LGPL) as published by the Free
Software Foundation. For information on this license look at the source code
that came with the software or see the 
.UR http://www.gnu.org
GNU project page
.UE
at http://www.gnu.org/.

.SH AUTHOR

\fBgsf-office-thumbnailer\fR's primary author is Federico Mena-Quintero
<federico@novell.com>.

The initial version of this manpage was written by J.H.M. Dassen (Ray)
<jdassen@debian.org>.

\".SH SEE ALSO
