# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.10
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_unittest_support')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_unittest_support')
    _unittest_support = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_unittest_support', [dirname(__file__)])
        except ImportError:
            import _unittest_support
            return _unittest_support
        if fp is not None:
            try:
                _mod = imp.load_module('_unittest_support', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _unittest_support = swig_import_helper()
    del swig_import_helper
else:
    import _unittest_support
del _swig_python_version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

class TestErrorStruct(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, TestErrorStruct, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, TestErrorStruct, name)
    __repr__ = _swig_repr
    __swig_setmethods__["log_level"] = _unittest_support.TestErrorStruct_log_level_set
    __swig_getmethods__["log_level"] = _unittest_support.TestErrorStruct_log_level_get
    if _newclass:
        log_level = _swig_property(_unittest_support.TestErrorStruct_log_level_get, _unittest_support.TestErrorStruct_log_level_set)
    __swig_setmethods__["log_domain"] = _unittest_support.TestErrorStruct_log_domain_set
    __swig_getmethods__["log_domain"] = _unittest_support.TestErrorStruct_log_domain_get
    if _newclass:
        log_domain = _swig_property(_unittest_support.TestErrorStruct_log_domain_get, _unittest_support.TestErrorStruct_log_domain_set)
    __swig_setmethods__["msg"] = _unittest_support.TestErrorStruct_msg_set
    __swig_getmethods__["msg"] = _unittest_support.TestErrorStruct_msg_get
    if _newclass:
        msg = _swig_property(_unittest_support.TestErrorStruct_msg_get, _unittest_support.TestErrorStruct_msg_set)

    def __init__(self):
        this = _unittest_support.new_TestErrorStruct()
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _unittest_support.delete_TestErrorStruct
    __del__ = lambda self: None
TestErrorStruct_swigregister = _unittest_support.TestErrorStruct_swigregister
TestErrorStruct_swigregister(TestErrorStruct)

G_LOG_FLAG_RECURSION = _unittest_support.G_LOG_FLAG_RECURSION
G_LOG_FLAG_FATAL = _unittest_support.G_LOG_FLAG_FATAL
G_LOG_LEVEL_ERROR = _unittest_support.G_LOG_LEVEL_ERROR
G_LOG_LEVEL_CRITICAL = _unittest_support.G_LOG_LEVEL_CRITICAL
G_LOG_LEVEL_WARNING = _unittest_support.G_LOG_LEVEL_WARNING
G_LOG_LEVEL_MESSAGE = _unittest_support.G_LOG_LEVEL_MESSAGE
G_LOG_LEVEL_INFO = _unittest_support.G_LOG_LEVEL_INFO
G_LOG_LEVEL_DEBUG = _unittest_support.G_LOG_LEVEL_DEBUG
G_LOG_LEVEL_MASK = _unittest_support.G_LOG_LEVEL_MASK

def test_add_error(error):
    return _unittest_support.test_add_error(error)
test_add_error = _unittest_support.test_add_error

def test_clear_error_list():
    return _unittest_support.test_clear_error_list()
test_clear_error_list = _unittest_support.test_clear_error_list

def test_set_checked_handler(domain, level, data):
    return _unittest_support.test_set_checked_handler(domain, level, data)
test_set_checked_handler = _unittest_support.test_set_checked_handler

def test_set_list_handler(domain, level, data):
    return _unittest_support.test_set_list_handler(domain, level, data)
test_set_list_handler = _unittest_support.test_set_list_handler

def test_set_null_handler(domain, level, data):
    return _unittest_support.test_set_null_handler(domain, level, data)
test_set_null_handler = _unittest_support.test_set_null_handler

def g_log_remove_handler(log_domain, handler):
    return _unittest_support.g_log_remove_handler(log_domain, handler)
g_log_remove_handler = _unittest_support.g_log_remove_handler
# This file is compatible with both classic and new-style classes.


