(((N_ "GnuCash Tutorial and Concepts Guide") 
  "gnc-help:gnucash-guide/index.html" #f)

((N_ "GnuCash Help") 
 "gnc-help:gnucash-help/help.html"
 
 (((N_ "Introduction to GnuCash") 
   "gnc-help:gnucash-help/intro-to-gnucash.html"
   (((N_ "What is GnuCash?") 
     "gnc-help:gnucash-help/intro-to-gnucash.html#what-is-gnucash" #f)
    )
   )

  ((N_ "Getting Started") 
   "gnc-help:gnucash-help/getting-started.html"
   (((N_ "Running GnuCash for the First Time") 
     "gnc-help:gnucash-help/getting-started.html#first-time"
     (((N_ "New Account Hierarchy Setup") 
       "gnc-help:gnucash-help/getting-started.html#acct-hierarchy" #f)
      ((N_ "Import QIF Files")
       "gnc-help:gnucash-help/getting-started.html#import-qif" #f)
      ((N_ "GnuCash Tutorial and Concepts Guide")
       "gnc-help:gnucash-help/getting-started.html#tutorial" #f)
      )
     )
    ((N_ "Tip of the Day")
     "gnc-help:gnucash-help/getting-started.html#tip-of-the-day" #f)
    )
   )

  ((N_ "Usage") ""
   (((N_ "GnuCash Windows")
     "gnc-help:gnucash-help/usage.html#windows"
     (((N_ "Account Tree Window")
       "gnc-help:gnucash-help/usage.html#account-tree"
      (((N_ "Menus")
	"gnc-help:gnucash-help/usage.html#tree-menus" #f)
       ((N_ "Tool Bar Buttons")
	"gnc-help:gnucash-help/usage.html#tree-toolbar" #f)
       ((N_ "Summary Bar")
	"gnc-help:gnucash-help/usage.html#tree-summary" #f)
       ((N_ "Account Tree")
	"gnc-help:gnucash-help/usage.html#tree-main" #f)
       ((N_ "Status Bar")
	"gnc-help:gnucash-help/usage.html#tree-status" #f)
       )
      )
      ((N_ "Account Register Window")
       "gnc-help:gnucash-help/usage.html#account-register"
       (((N_ "Menus")
	"gnc-help:gnucash-help/usage.html#reg-menus" #f)
       ((N_ "Tool Bar Buttons")
	"gnc-help:gnucash-help/usage.html#reg-toolbar" #f)
       ((N_ "Summary Bar")
	"gnc-help:gnucash-help/usage.html#reg-summary" #f)
       ((N_ "List of Transactions")
	"gnc-help:gnucash-help/usage.html#reg-main" #f)
       ((N_ "Status Bar")
	"gnc-help:gnucash-help/usage.html#reg-status" #f)
       ((N_ "General Ledger")
	"gnc-help:gnucash-help/usage.html#reg-gl" #f)
       )
      )
      ((N_ "Report Window")
       "gnc-help:gnucash-help/usage.html#report-win"
       (((N_ "Tool Bar Buttons")
	"gnc-help:gnucash-help/usage.html#report-toolbar" #f)
       ((N_ "Report")
	"gnc-help:gnucash-help/usage.html#report-main" #f)
       )
      )
      ((N_ "Tool Windows")
       "gnc-help:gnucash-help/usage.html#tool-win"
       (((N_ "Scheduled Transactions Window")
	"gnc-help:gnucash-help/usage.html#tool-sched" #f)
       ((N_ "Reconcile Window")
	"gnc-help:gnucash-help/usage.html#tool-reconcile" #f)
       ((N_ "Price Editor")
	"gnc-help:gnucash-help/usage.html#tool-price" #f)
       ((N_ "Commodity Editor")
	"gnc-help:gnucash-help/usage.html#tool-commodity" #f)
       ((N_ "Financial Calculator")
	"gnc-help:gnucash-help/usage.html#tool-calc" #f)
       ((N_ "Find Transactions")
	"gnc-help:gnucash-help/usage.html#tool-find" #f)
       )
      )
      ((N_ "Help Window")
       "gnc-help:gnucash-help/usage.html#help-win" #f)
      )
     )
    ((N_ "Setting Up and Editing Accounts")
     "gnc-help:gnucash-help/usage.html#setup-accounts"
     (((N_ "Types of GnuCash Accounts")
       "gnc-help:gnucash-help/usage.html#acct-types" #f)
      ((N_ "To Create a Chart of Accounts")
       "gnc-help:gnucash-help/usage.html#chart-create" #f)
      ((N_ "To Create a New Account")
       "gnc-help:gnucash-help/usage.html#acct-create"
       (((N_ "General Information")
	 "gnc-help:gnucash-help/usage.html#gen-info" #f)
	((N_ "Opening Balance")
	 "gnc-help:gnucash-help/usage.html#open-balance" #f)
	)
       )
      ((N_ "To Edit an Account")
       "gnc-help:gnucash-help/usage.html#acct-edit" #f)
      ((N_ "To Edit a Chart of Accounts")
       "gnc-help:gnucash-help/usage.html#chart-edit" #f)
      ((N_ "To Delete an Account")
       "gnc-help:gnucash-help/usage.html#acct-delete" #f)
      ((N_ "To Jump to Another Account")
       "gnc-help:gnucash-help/usage.html#acct-jump" #f)
      ((N_ "To Reconcile an Account to a Statement")
       "gnc-help:gnucash-help/usage.html#acct-reconcile"
       (((N_ "Reconcile Information")
	 "gnc-help:gnucash-help/usage.html#rec-info" #f)
	((N_ "Reconcile Window")
	 "gnc-help:gnucash-help/usage.html#rec-win" #f)
	)
       )
      ((N_ "To Perform a Stock Split")
       "gnc-help:gnucash-help/usage.html#stock-split"
       (((N_ "Stock Split Druid")
	 "gnc-help:gnucash-help/usage.html#stock-split-druid" #f)
	)
       )
      )
     )
    ((N_ "Using the Register to Record Transactions")
     "gnc-help:gnucash-help/usage.html#transactions"
     (((N_ "Changing the Register View")
       "gnc-help:gnucash-help/usage.html#reg-views" #f)
      ((N_ "To Enter a Transaction")
       "gnc-help:gnucash-help/usage.html#trans-enter"
       (((N_ "Enter Directly in the Register Window")
	 "gnc-help:gnucash-help/usage.html#trans-reg-enter" #f)
	((N_ "Enter in the Transfer Funds Window")
	 "gnc-help:gnucash-help/usage.html#trans-win-enter" #f)
	)
       )
      ((N_ "To Enter Multiple Split Transactions")
       "gnc-help:gnucash-help/usage.html#trans-multi-enter" #f)
      ((N_ "To Enter Multiple Currency Transactions")
       "gnc-help:gnucash-help/usage.html#trans-currency-enter" #f)
      ((N_ "To Edit a Transaction")
       "gnc-help:gnucash-help/usage.html#trans-edit" #f)
      ((N_ "To Delete a Transaction")
       "gnc-help:gnucash-help/usage.html#trans-delete" #f)
      ((N_ "To Remove Transaction Splits")
       "gnc-help:gnucash-help/usage.html#trans-split-remove" #f)
      ((N_ "To Copy a Transaction")
       "gnc-help:gnucash-help/usage.html#trans-copy" #f)
      ((N_ "To Schedule Transactions")
       "gnc-help:gnucash-help/usage.html#tran-sched"
       (((N_ "Scheduled Transaction Editor")
	 "gnc-help:gnucash-help/usage.html#trans-sched-editor" #f)
	((N_ "Since Last Run Druid")
	 "gnc-help:gnucash-help/usage.html#trans-sched-slr" #f)
	((N_ "Mortgage & Loan Repayment Druid")
	 "gnc-help:gnucash-help/usage.html#trans-sched-loans" #f)
	)
       )
      ((N_ "To Print Checks")
       "gnc-help:gnucash-help/usage.html#print-check" #f)
      )
     )
    ((N_ "Using GnuCash Reports and Charts")
     "gnc-help:gnucash-help/usage.html#reports"
       (((N_ "Types of Reports and Graphs")
	 "gnc-help:gnucash-help/usage.html#report-types"
	 (((N_ "General Reports")
	   "gnc-help:gnucash-help/usage.html#report-general" #f)
	  ((N_ "Assets & Liabilities")
	   "gnc-help:gnucash-help/usage.html#report-assets" #f)
	  ((N_ "Income & Expense")
	   "gnc-help:gnucash-help/usage.html#report-income" #f)
	  ((N_ "Business Reports")
	   "gnc-help:gnucash-help/usage.html#report-biz" #f)
	  )
	 )
	((N_ "To Create Reports and Graphs")
	 "gnc-help:gnucash-help/usage.html#report-create" #f)
	((N_ "To Customize Reports and Graphs")
	 "gnc-help:gnucash-help/usage.html#report-custom" #f)
	((N_ "To Print or Export Reports and Graphs")
	 "gnc-help:gnucash-help/usage.html#report-print" #f)
	)
       )
    )
   )
  ((N_ "Customizing GnuCash")
   "gnc-help:gnucash-help/custom-gnucash.html"
   (((N_ "Account Options")
     "gnc-help:gnucash-help/custom-gnucash.html#account-options" #f)
    ((N_ "Setting Your Preferences")
     "gnc-help:gnucash-help/custom-gnucash.html#set-prefs"
     (((N_ "Accounts")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-accounts" #f)
      ((N_ "Business")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-biz" #f)
      ((N_ "General")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-general" #f)
      ((N_ "International")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-inter" #f)
      ((N_ "Online Banking & Importing")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-online" #f)
      ((N_ "Reconcile")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-rec" #f)
      ((N_ "Register")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-reg" #f)
      ((N_ "Register Colors")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-reg-color" #f)
      ((N_ "Scheduled Transactions")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-sched" #f)
      ((N_ "User Info")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-user" #f)
      ((N_ "Advanced")
       "gnc-help:gnucash-help/custom-gnucash.html#prefs-advanced" #f)
      )
     )
    ((N_ "Changing Style Sheets")
     "gnc-help:gnucash-help/custom-gnucash.html#change-style"
     (((N_ "Default")
       "gnc-help:gnucash-help/custom-gnucash.html#style-default"
       (((N_ "General")
	 "gnc-help:gnucash-help/custom-gnucash.html#style-def-general" #f)
	((N_ "Tables")
	 "gnc-help:gnucash-help/custom-gnucash.html#style-def-tables" #f)
	)
       )
      ((N_ "Technicolor")
       "gnc-help:gnucash-help/custom-gnucash.html#style-technicolor"
       (((N_ "Colors")
	 "gnc-help:gnucash-help/custom-gnucash.html#style-tech-colors" #f)
	((N_ "General")
	 "gnc-help:gnucash-help/custom-gnucash.html#style-tech-general" #f)
	((N_ "Images")
	 "gnc-help:gnucash-help/custom-gnucash.html#style-tech-images" #f)
	((N_ "Tables")
	 "gnc-help:gnucash-help/custom-gnucash.html#style-tech-tables" #f)
	)
       )
      )
     )
    ((N_ "Setting Tax Options")
     "gnc-help:gnucash-help/custom-gnucash.html#set-tax-options"
     (((N_ "TXF Export - Known Anomalies and Limitations")
       "gnc-help:gnucash-help/custom-gnucash.html#txf-probs" #f)
      ((N_ "Detailed TXF Category Descriptions")
       "gnc-help:gnucash-help/custom-gnucash.html#txf-defs" #f)
      )
     )
     )
    )
   )
  )
((N_ "Report a bug") "http://bugzilla.gnome.org" #f)
)
