#!/bin/ksh
# $ID$
# If you have Dave Raggett's "tidy" utility, this will tidy up
# the HTML files here.
for i in *.html ; do
   tidy -m -i $i
donediff -u 'pristine/gnucash/Docs/En/xacc-about.html' 'working/gnucash/Docs/En/xacc-about.html'
