.\" Written by Robert Merkel (rgmerk@mira.net)
.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH GNC-PRICES 1 "MARCH 2000" Version "1.3.x"
.SH NAME
gnc-prices \- update stock prices from online sources for gnucash
.SH SYNOPSIS
.B gnc-prices
.I xacc-data.xac
.SH DESCRIPTION
.B gnc-prices 
is a perl script to gather stock quotes to allow stock
and mutual fund price quotes directly into 
.B gnucash.
See 
.B gnucash's
online help for more details.

.SH BUGS
This (useful) hack should be rewritten in guile and rolled into gnucash proper.

.SH "SEE ALSO"
.BR gnucash (1)

.B gnucash 
has extensive on-line help available from the "help" menu.

Additional information and the latest version is available 
at the web site:
.B http://gnucash.org

.SH AUTHOR
Robert Merkel <rgmerk@mira.net> wrote this manpage.

.B gnucash
was written by Robin Clark, Linas Vepstas, and a cast of thousands.
