.\" Written by Robert Merkel (rgmerk@mira.net)
.\" Process this file with
.\" groff -man -Tascii foo.1
.\"
.TH GNC-PRICES 1 "January 2002" Version "1.6.6"
.SH NAME
gnc-prices \- update stock prices from online sources for gnucash
.SH SYNOPSIS
.B gnc-prices
.I xacc-data.xac
.SH DESCRIPTION
.B gnc-prices 
is a perl script to gather stock quotes to allow stock
and mutual fund price quotes directly into 
.B GnuCash.
See the 
.B GnuCash
online help for more details.

.SH "SEE ALSO"
.BR gnucash (1)

.B GnuCash 
has extensive on-line help available from the "help" menu.

Additional information and the latest version is available 
at the web site:
.B http://gnucash.org

.SH AUTHOR
Robert Merkel <rgmerk@mira.net> wrote this manpage.

.B GnuCash
was written by Robin Clark, Linas Vepstas, and a cast of thousands.
