#!/bin/sh
#
# Remove entries that are for post-gtk2.6 attributes.  Glade on a
# gtk2.6 system will complain when unknown attributes are present on a
# widget.
#
# This script should be run from the top-level source directory before
# committing changed glade files.
#

if test -d src ; then
    SEARCHDIRS=src
else
    SEARCHDIRS=.
fi

find ${SEARCHDIRS} -name \*.glade | xargs \
  sed -i -e '/name="urgency_hint"/d' \
         -e '/name="pack_direction"/d' \
         -e '/name="child_pack_direction"/d'

# GTK 2.6 (now allowed)
#	add_tearoffs
#	angle
#	ellipsize
#	focus_on_map
#	hover_expand
#	hover_selection
#	single_line_mode
#	width_chars
#
# GTK 2.8
#	child_pack_direction
#	pack_direction
#	urgency_hint
#
# GTK 2.10
#	(none)
#
