#!/bin/sh
#
# Remove entries that are for post-gtk2.8 attributes.  Glade on a
# gtk2.8 system will complain when unknown attributes are present on a
# widget.
#
# This script should be run from the top-level source directory before
# committing changed glade files.
#

if test -d src ; then
    SEARCHDIRS=src
else
    SEARCHDIRS=.
fi

find ${SEARCHDIRS} -name \*.glade | xargs \
  sed -i -e '/name="image_position"/d' \
         -e '/name="inner_border"/d'

# GTK 2.6 (now allowed)
#	add_tearoffs
#	angle
#	ellipsize
#	focus_on_map
#	hover_expand
#	hover_selection
#	single_line_mode
#	width_chars
#
# GTK 2.8 (now allowed)
#	child_pack_direction
#	pack_direction
#	urgency_hint
#
# GTK 2.10
#	image_position
#   inner_border
