#! /bin/sh 
exec guile -s "$0"
!#

(display "  testing US locale-specific report module load ... ")
(use-modules (gnucash gnc-module))
(gnc:module-system-init)

(if (gnc:module-load "gnucash/report/locale-specific/us" 0)
    (begin 
      (display "ok\n")
      (exit 0))
    (begin 
      (display "failed\n")
      (exit -1)))

