_("String Option")
_("Second Option")
_("Cost")
_("Mutual Fund")
_("Status")
_("Date")
_("Account Name")
_("Equity")
_("Last Year")
_("'Enter' moves to blank transaction")
_("Other Account")
_("Account Separator")
_("Auto-Raise Lists")
_("Balance")
_("Secondary Sort Order")
_("Stock Portfolio Valuation")
_("Stock Portfolio")
_("Select Accounts (none = all)")
_("The types of accounts for which balances are sign-reversed")
_("Rebate")
_("The Good")
_("The current time is %s.")
_("Alternate Period")
_("Headers")
_("One Month Ago")
_("Double Line")
_("Report's currency")
_("End of the Previous Year")
_("Use a 24 hour (instead of a 12 hour) time format.")
_("Income:Salary:Taxable")
_("Type of budget report")
_("Test progress dialog")
_("Balancing")
_("Date (subtotal monthly)")
_("Split color")
_("Time")
_("Single Column Display")
_("Account (w/subtotal)")
_("Memo")
_("International")
_("Relative Date Option")
_("This is a string option")
_("The beginning of the previous month")
_("Locale")
_("Main Window")
_("Set Selected & sub-accounts as Tax Related")
_("Debit")
_("This page shows your Taxable Income and Deductable Expenses.")
_("The date option is %s.")
_("Set Tax Related")
_("UK")
_("Sort by date")
_("Start of previous month")
_("Display the shares price?")
_("Report for %s and all subaccounts.")
_("Account types to display")
_("Gain And Loss")
_("The start of the latest quarterly accounting period")
_("Double click expands parent accounts")
_("The start of the previous financial year/accounting period")
_("If selected, move to the blank transaction after the user presses 'Enter'. Otherwise, move down one row.")
_("Boolean Option")
_("Income-Salary-Taxable")
_("End of previous month")
_("Display the Tax report.")
_("Spend")
_("_Stock Portfolio")
_("Testing")
_("Other currencies' total")
_("US-style: mm/dd/yyyy")
_("Only positive Entries")
_("Period From: ")
_("You have not selected an account.")
_("By default, show every transaction in an account.")
_("Amount")
_("Multi Line")
_("No amount display")
_("Withdrawal")
_("View")
_("Report on these account(s)")
_("UK-style dd/mm/yyyy")
_("Show all columns")
_("Last Yr 3rd Est Tax Qtr")
_("Account")
_("Value")
_("Sorting")
_("Show icons only")
_("Auto Single")
_("Print all Parent account names")
_("Register hint font")
_("Reset Selected accounts as not Tax Related")
_("Display the Hello, World report.")
_("Gain")
_("Last Yr 4th Est Tax Qtr")
_("Current Financial Year Start")
_("Reset Selected & sub-accounts as not Tax Related")
_("Hello Again")
_("1st Est Tax Quarter")
_("Previous Year Start")
_("This page shows your profits and losses.")
_("Show Vertical Borders")
_("The relative date option is %s.")
_("This is a boolean option.")
_("You should back up your files regularly.  Just copy""\n"
  "the GnuCash .xac file to a floppy or other backup device.""\n"
  "")
_("_Profit and Loss")
_("Display 1 line")
_("This is a combination date option")
_("Background Color")
_("The number option formatted as currency is %s.")
_("Income/Salary/Taxable")
_("There are no selected accounts in the account list option.")
_("The background color for the current register row")
_("Funds Out")
_("This page shows your net worth.")
_("_Budget")
_("Set/Reset Selected Account Tax Status")
_("Test the budget dialog")
_("Continental Europe: dd.mm.yyyy")
_("Confirm before changing reconciled")
_("The font used to show hints in the register")
_("Auto Decimal Places")
_("Display the Account Summary report.")
_("Single")
_("Warning!! This is a DEVELOPMENT version of GnuCash.""\n"
  "It probably has lots of bugs and unstable features!""\n"
  "If you are looking for a stable personal finance application,""\n"
  "you should use the latest release of GnuCash 1.4.""\n"
  "")
_("Show Horizontal Borders")
_("Sort by check/transaction number")
_("Start of current quarter")
_("Register Colors")
_("The boolean option is %s.")
_("Display the memo?")
_("(subaccounts)")
_("Header color")
_("The default secondary background color for register rows")
_("Double clicking on an account with children expands the account instead of opening a register.")
_("Loss")
_("Credit Accounts")
_("Sort by description")
_("largest to smallest, latest to earliest")
_("Acc_ount Balance Tracker")
_("Use From - To")
_("Secondary Key")
_("Display the description?")
_("GnuCash does not use categories like Quicken does.""\n"
  "Instead, you should use Income and Expense accounts.""\n"
  "")
_("(Sub ")
_("Save window sizes and positions.")
_("Bank")
_("Number Option")
_("Set/Reset Tax Status")
_("Report for %s.")
_("Reverse Income and Expense Accounts")
_("Europe")
_("Split active color")
_("Display the account type?")
_("Opening Balance")
_("Payment")
_("Day")
_("This is for testing. Your reports probably shouldn't have an option like this.")
_("Foreign Currency")
_("Set Selected accounts as Tax Related")
_("Display the headers?")
_("Do transaction report on these accounts")
_("Six Months Ago")
_("Sort and subtotal by account transferred from/to's name")
_("Double line mode with a multi-line cursor")
_("Single line mode with a multi-line cursor")
_("Print Full account names")
_("The items selected in the list option are:")
_("Average")
_("From")
_("Start of reporting period")
_("How many automatic decimal places will be filled in.")
_("Sort by exact entry time")
_("Use accounting labels")
_("Full")
_("Price")
_("The font to use in the register")
_("Display the account's foreign currency amount?")
_("The amount of time between data points")
_("Upper Limit")
_("Account Summary")
_("Previous Financial Year Start")
_("Currency")
_("Week")
_("Crash the report")
_("Start of this month")
_("Beginning of the previous calendar year")
_("Taxable / Deductable")
_("Cash")
_("Step Size")
_("Hello, World!")
_("ISO")
_("Choose exchange rate for above currency")
_("A report useful for balancing the budget")
_("Display the amount?")
_("Multi-Line")
_("Two Column Display")
_("Date Format Display")
_("Ending")
_("The start of the previous quarterly accounting period")
_("Reversed-balance account types")
_("Show transactions on two lines with more information")
_("Account fields to display")
_("Date: %s<br>Report for %s and all Sub-Accounts.<br>Accounts Total: %s")
_("Sell")
_("Account Balance Tracker")
_("If selected, use a dialog to confirm a change to a reconciled transaction.")
_("Report Options")
_("Show transactions on single lines")
_("Description")
_("Calculate balance sheet up to this date")
_("Transaction Report")
_("Sep 1 - Dec 31, Last year")
_("Jun 1 - Aug 31, Last year")
_("Apr 1 - May 31, Last year")
_("Jan 1 - Mar 31, Last year")
_("Gain/Loss")
_("Transfer from/to")
_("Text only")
_("Start of previous quarter")
_("Previous Year End")
_("Depreciation")
_("Toolbar Buttons")
_("Report Items from this date")
_("Period")
_("Fourth Options")
_("Sort by this criterion first")
_("Double")
_("Ugly option")
_("End of previous quarter")
_("How are you doing on your budget?")
_("Reset Tax Related & sub-accounts")
_("Combo Date Option")
_("Save Translatable Strings")
_("Start of the current month")
_("Save strings that need to be translated")
_("Automatic credit card payments")
_("Number of Rows")
_("A_ccount Summary")
_("/ (Slash)")
_("Asset")
_("Reset Tax Related")
_("Use 24-hour time format")
_("Num")
_("Date Format")
_("A list option")
_("ISO Standard: yyyy-mm-dd")
_("Default Currency")
_("Today")
_("Primary active color")
_("Do transaction report on this account")
_("Recent Price")
_("Please choose appropriate dates - the \"To\" date should be *after* the \"From\" date.")
_("The multi-choice option is %s.")
_("Double mode colors alternate with transactions")
_("General")
_("Security")
_("Automatically insert a decimal point into values that are entered without one.")
_("Single Line")
_("Receive")
_("Sub-Accounts")
_("T_ax")
_("The date and time option is %s.")
_("Liability")
_("End of reporting period")
_("Don't reverse any accounts")
_("Good option")
_("The GnuCash online manual has lots of helpful information.""\n"
  "You can access the manual under the Help menu.""\n"
  "")
_("US")
_("_Transaction Report")
_("One Week Ago")
_("Deposit")
_("Ba_lance sheet")
_("3rd Est Tax Quarter")
_("Help for first option")
_("  To: ")
_("In the reconcile window, you can press the spacebar""\n"
  "to mark transactions as reconciled.""\n"
  "You can also press Tab and Shift-Tab to move between""\n"
  "deposits and withdrawals.""\n"
  "")
_("Number")
_("Show both icons and text")
_("No Tax Related accounts were found. Click \"Parameters\" to set some  with the \"Set/Reset Tax Status:\" parameter.")
_("Charge")
_("Transfer from/to (w/subtotal)")
_("Total")
_("Report")
_("Notes")
_("The number option is %s.")
_("The string option is %s.")
_("Report style")
_("_Reports")
_("Register")
_("Year")
_("Automatic Decimal Point")
_("Show the total amount of other currencies?")
_("Profit and Loss")
_("Month")
_("Use From - To period")
_("Current Year Start")
_(". (Period)")
_("Primary Sort Order")
_("Name")
_("When entering check numbers in the register, you can""\n"
  "press '+' to enter the next number. You can use '+'""\n"
  "and '-' to increment and decrement the number, respectively.""\n"
  "")
_("Descending")
_("Display the date?")
_("This is a date option")
_("Two Week")
_("Last Yr 2nd Est Tax Qtr")
_("The default background color for split rows in the register")
_("Save Window Geometry")
_("Income\\Salary\\Taxable")
_("Code")
_("After reconciling a credit card statement, prompt the user to enter a credit card payment")
_("Balance sheet")
_("Export data as text.")
_("Balance Sheet")
_("- (Dash)")
_("Funds In")
_("End of previous quarterly accounting period")
_("Register font")
_("Order of primary sorting")
_("Default currency for new accounts")
_("Sort by this criterion second")
_("Tax")
_("true")
_("Appreciation")
_("Alternate the primary and secondary colors with each transaction, not each row")
_("Do not sort")
_("Display only positive Entries?")
_("Date: %s<br>Report for %s.<br>Accounts Total: %s")
_("Period Ending")
_("Income.Salary.Taxable")
_("Only use 'debit' and 'credit' instead of informal synonyms")
_("Income")
_("Include sub-accounts of all selected accounts")
_("Style")
_("The Ugly")
_("Max")
_("Include Sub-Accounts of each selected Account")
_("No Change")
_("Choose foreign currency to specify an exchange rate for")
_("Budget (Testing, Unfinished)")
_("By default, show horizontal borders on the cells.")
_("Display the totals?")
_(": (Colon)")
_("By default, show vertical borders on the cells.")
_("Credit")
_("Tax Report Options")
_("Actual")
_("Enable EURO support")
_("Ascending")
_("Display the number of shares?")
_("The Bad")
_("Just a Date Option")
_("Start of the current financial year/accounting period")
_("The accounts selected in the account list option are:")
_("Reconcile")
_("This is a sample GnuCash report. See the guile (scheme) source code in %s for details on writing your own reports, or extending existing reports.")
_("Enables support for the European Union EURO currency")
_("The secondary background color for the current register row")
_("Display the Budget report.")
_("Display the account?")
_("Display the cheque number?")
_("Display N lines")
_("_Hello, World")
_("First Option")
_("Display the Stock Portfolio report.")
_("All other currencies will get converted to this currency.")
_("Show transactions on multiple lines with one line for each split in the transaction")
_("Currency 1")
_("Currency 2")
_("Currency 3")
_("Currency 4")
_("Currency 5")
_("Plot Type")
_("Budget")
_("Choose whether to display icons, text, or both for toolbar buttons")
_("Sort by date & subtotal each year")
_("4th Est Tax Quarter")
_("Show text only")
_("Icons and Text")
_("The type of graph to generate")
_("$0.00 valued Accounts won't be printed.")
_("Automatically raise the list of accounts or actions during input.")
_("Select accounts")
_("Sort by account transferred from/to's name")
_("Net Gain")
_("The fourth option rules!")
_("This is a date option with time")
_("End of the previous Financial year/Accounting Period")
_("The header background color")
_("Display \"Tip of the Day\"")
_("Sort by memo")
_("Third Option")
_("Choose the default mode for register windows")
_("Default number of register rows to display.")
_("The current date")
_("Secondary color")
_("Report end date")
_("None")
_("Export data as text (Danger: Unfinished)")
_("The combination date option is %s.")
_("Last Yr 1st Est Tax Qtr")
_("Primary Key")
_("Ticker")
_("Secondary active color")
_("Suppress $0.00 values")
_("Display the other account?  (if this is a split transaction, this parameter is guessed).")
_("Time and Date Option")
_("The character used to separate fully-qualified account names")
_("Report start date")
_("2nd Est Tax Quarter")
_("To")
_("smallest to largest, earliest to latest")
_("Type")
_("Display the Transaction Report report.")
_("\\ (Backslash)")
_("Last day of previous month")
_("End Previous Financial Year")
_("Icons only")
_("Help for third option")
_("Default system locale format")
_("Default Register Mode")
_("Auto Double")
_("Lower Limit")
_("One Year Ago")
_("To transfer funds between accounts with different currencies,""\n"
  "you need an intermediate currency trading account.""\n"
  "Please see the GnuCash online manual for details""\n"
  "")
_("Sort by amount")
_("This is an account list option")
_("This is a relative date option")
_("Average Balance")
_("Totals")
_("Profit/Loss")
_("Start of the current calendar year")
_("Shares")
_("Show All Transactions")
_("Display the Profit and Loss report.")
_("Date (subtotal yearly)")
_("Display the Account Balance Tracker report.")
_("2Week")
_("Nothing")
_("The background color for the current split row in the register")
_("You have selected no values in the list option.")
_("false")
_("The default background color for register rows")
_("Sep 1 - Dec 31")
_("Jun 1 - Aug 31")
_("Apr 1 - May 31")
_("Jan 1 - Mar 31")
_("Expense")
_("An account list option")
_("Multi Choice Option")
_("This is a color option")
_("Report up to and including this date")
_("Currencies")
_("Make No Plot")
_("Bad option")
_("Display the Balance sheet report.")
_("Sort by date & subtotal each month")
_("Three Months Ago")
_("Net")
_("Have a nice day!")
_("Primary color")
_("This is a list option")
_("Exchange rate for Currency 1")
_("Exchange rate for Currency 2")
_("Exchange rate for Currency 3")
_("Exchange rate for Currency 4")
_("Exchange rate for Currency 5")
_("Min")
_("Display hints for using GnuCash at startup")
_("Order of Secondary sorting")
_("Help for second option")
_("Overide or modify From: & To:")
_("Set Tax Related & sub-accounts")
_("Report items up to and including this date")
_("Display")
_("Nominal")
_("Beginning")
_("For help on writing reports, or to contribute your brand new, totally cool report, consult the mailing list %s. For details on subscribing to that list, see %s.")
_("This is a multi choice option.")
_("Income & Expense")
_("Display negative amounts in red")
_("Hello, World")
_("Buy")
_("Sort & subtotal by account")
_("Reverse Credit Card, Liability, Equity, and Income Accounts")
_("Stock")
_("This is a number option.")
_("Extensions")
