#! /bin/sh 
exec guile -s $0
!#

(use-modules (gnucash gnc-module))
(gnc:module-system-init)

(display "  testing gnome-utils module load ... ")
(gnc:module-load "gnucash/gnome-utils" 0)

(display "  ok\n")
