/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Select currency/security ");
gchar *s = N_("New...");
gchar *s = N_("Type:");
gchar *s = N_("Currency/security:");
gchar *s = N_("New Currency/Security");
gchar *s = N_("Full name:");
gchar *s = N_("Symbol/abbreviation:");
gchar *s = N_("Type:");
gchar *s = N_("CUSIP or other code:");
gchar *s = N_("Fraction traded:");
gchar *s = N_("Enter the full name of the commodity. Example: US Dollars");
gchar *s = N_("Enter the ticker symbol or currency code for the commodity. Example: USD");
gchar *s = N_("Enter the type of commodity. For stocks, this is often an exchange on which the stock is traded. You can choose an existing type from the list or enter a new type with the keyboard.");
gchar *s = N_("Enter a unique code used to identify the commodity. Or, you may safely leave this field blank.");
gchar *s = N_("1 /");
gchar *s = N_("Enter the smallest fraction of the commodity which can be traded. For stocks which can only be traded in whole numbers, enter 1.");
gchar *s = N_("Import currency and stock information");
gchar *s = N_("Import currency and stock information ");
gchar *s = N_("The file you are loading is from an older version of GnuCash. \n"
              "Information about currencies, stocks, and mutual funds needs to\n"
              "be updated for the new version. \n"
              "\n"
              "This dialog will prompt you for some additional information about \n"
              "each currency, stock, and mutual fund that appear in your\n"
              "accounts.  After you have entered this information, you can\n"
              "update your accounts for the new version of GnuCash.\n"
              "\n"
              "Hit \"Cancel\" now to stop loading the file. ");
gchar *s = N_("Update your accounts with the new information");
gchar *s = N_("Click \"Finish\" to update your accounts to use the new \n"
              "information you have entered.\n"
              "\n"
              "Click \"Cancel\" to cancel the file-loading process.  \n"
              "\n"
              "Click \"Back\" to review your currency selections.");
gchar *s = N_("Commodities");
gchar *s = N_("Commodities");
gchar *s = N_("Show National Currencies");
gchar *s = N_("Type");
gchar *s = N_("Symbol");
gchar *s = N_("Name");
gchar *s = N_("Code");
gchar *s = N_("Fraction");
gchar *s = N_("Add a new price.");
gchar *s = N_("Add");
gchar *s = N_("Remove the current price");
gchar *s = N_("Remove");
gchar *s = N_("Edit");
