/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Find Transactions");
gchar *s = N_("Find");
gchar *s = N_("Match Accounts");
gchar *s = N_("Find transactions affecting");
gchar *s = N_("All\n"
              "Any\n"
              "None\n"
              "");
gchar *s = N_("selected accounts:");
gchar *s = N_("Account");
gchar *s = N_("Match Date");
gchar *s = N_("Find transactions occurring in the date range:");
gchar *s = N_("Starting ");
gchar *s = N_("Ending ");
gchar *s = N_("Date");
gchar *s = N_("Match Description");
gchar *s = N_("Find transactions whose Description contains:");
gchar *s = N_("Case sensitive");
gchar *s = N_("Regular expression");
gchar *s = N_("Description");
gchar *s = N_("Match Description");
gchar *s = N_("Find transactions whose Number contains:");
gchar *s = N_("Case sensitive");
gchar *s = N_("Regular expression");
gchar *s = N_("Number");
gchar *s = N_("Match Amount");
gchar *s = N_("Find ");
gchar *s = N_("Credit or Debit\n"
              "Credit\n"
              "Debit\n"
              "");
gchar *s = N_("splits having amounts of:");
gchar *s = N_("At least\n"
              "At most \n"
              "Exactly\n"
              "");
gchar *s = N_("Amount");
gchar *s = N_("Match Memo");
gchar *s = N_("Find splits whose Memo contains:");
gchar *s = N_("Case sensitive");
gchar *s = N_("Regular expression");
gchar *s = N_("Memo");
gchar *s = N_("Match number of shares");
gchar *s = N_("Find securities transactions of:");
gchar *s = N_("At least\n"
              "At most\n"
              "Exactly\n"
              "");
gchar *s = N_("shares");
gchar *s = N_("Shares");
gchar *s = N_("Match share price");
gchar *s = N_("Find securities transactions with share price of:");
gchar *s = N_("At least\n"
              "At most\n"
              "Exactly\n"
              "");
gchar *s = N_("Price");
gchar *s = N_("Match Action");
gchar *s = N_("Find transactions whose Action contains:");
gchar *s = N_("Case sensitive");
gchar *s = N_("Regular expression");
gchar *s = N_("Action");
gchar *s = N_("Match Cleared state");
gchar *s = N_("Find transactions whose Cleared status is:");
gchar *s = N_("Not cleared (n)");
gchar *s = N_("Cleared (c)");
gchar *s = N_("Reconciled (y)");
gchar *s = N_("Cleared");
gchar *s = N_("Match Balance state");
gchar *s = N_("Find transactions whose Balance status is:");
gchar *s = N_("Balanced");
gchar *s = N_("Not Balanced");
gchar *s = N_("Balance");
gchar *s = N_("Match transaction tags (CURRENTLY INOPERABLE)");
gchar *s = N_("Find transactions with the tag:");
gchar *s = N_("Case sensitive");
gchar *s = N_("Regular expression");
gchar *s = N_("Tags");
gchar *s = N_("Type of search");
gchar *s = N_("New search");
gchar *s = N_("Refine current search");
gchar *s = N_("Add results to current search");
gchar *s = N_("Delete results from current search");
