/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("GnuCash Help");
gchar *s = N_("Help Topics");
gchar *s = N_("Topics");
gchar *s = N_("Search GnuCash Help");
gchar *s = N_("Search Term:");
gchar *s = N_("Type a single term into the box and hit 'search'. At the moment, this search engine does not support complex searches, just single words.");
gchar *s = N_("Search");
gchar *s = N_("Help");
gchar *s = N_("Search results");
gchar *s = N_("Search");
