/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Welcome to GnuCash 1.6!");
gchar *s = N_("Create a new set of accounts");
gchar *s = N_("Import my QIF files");
gchar *s = N_("Open the new user tutorial");
gchar *s = N_("Canceling");
gchar *s = N_("Uncheck if you do not want this dialog to run if you start GnuCash up again. ");
gchar *s = N_("Run dialog for new user again?");
