/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Select Account");
gchar *s = N_("Select or add a GnuCash account");
gchar *s = N_("Account");
gchar *s = N_("New?");
gchar *s = N_("New Account (child of selected) ...");
gchar *s = N_("QIF Import");
gchar *s = N_("Import QIF files");
gchar *s = N_("GnuCash can import financial data from QIF (Quicken \n"
              "Interchange Format) files written by Quicken/QuickBooks,\n"
              "MS Money, Moneydance, and many other programs. \n"
              "\n"
              "The import process has several steps. Your GnuCash\n"
              "accounts will not be changed until you click \"Finish\"\n"
              "at the end of the process. \n"
              "\n"
              "Click \"Next\" to start loading your QIF data, or \"Cancel\"\n"
              "to abort the process. ");
gchar *s = N_("Select a QIF file to load");
gchar *s = N_("Please select a file to load. When you click \"Next\", the file will be loaded\n"
              "and analyzed. You may need to answer some questions about the account(s)\n"
              "in the file.\n"
              "\n"
              "You will have the opportunity to load as many files as you wish, so don't \n"
              "worry if your data is in multiple files. \n"
              "");
gchar *s = N_("QIF Filename:");
gchar *s = N_("Select...");
gchar *s = N_("Set a date format for this QIF file");
gchar *s = N_("The QIF file format does not specify which order the day, month, and \n"
              "year components of a date are printed.  In most cases, it is possible \n"
              "to automatically determine which format is in use in a particular file.\n"
              "However, in the file you have just imported there exist more than one\n"
              "possible format that fits the data.  \n"
              "\n"
              "Please select a date format for the file.  QIF files created by European\n"
              "software are likely  to be in \"d-m-y\" or day-month-year format, where\n"
              "US QIF files are likely to be \"m-d-y\" or month-year-day.    \n"
              "");
gchar *s = N_("Set the default QIF account name");
gchar *s = N_("The QIF file that you just loaded appears to contain transactions for just \n"
              "one account, but the file does not specify a name for that account.  \n"
              "\n"
              "Please enter a name for the account. If the file was exported from another\n"
              "accounting program, you should use the same account name that was used \n"
              "in that program.\n"
              "");
gchar *s = N_("Account name:");
gchar *s = N_("QIF files you have loaded");
gchar *s = N_("QIF Files");
gchar *s = N_("label827");
gchar *s = N_("Click \"Load another file\" if you have more data to import at this time.\n"
              "Do this if you have saved your accounts to separate QIF files.\n"
              "\n"
              "Click \"Next\" to finish loading files and move to the next step \n"
              "of the QIF import process. ");
gchar *s = N_("Load another file");
gchar *s = N_("Unload selected file");
gchar *s = N_("Accounts and stock holdings");
gchar *s = N_("On the next page, the accounts in your QIF files and any stocks or mutual funds\n"
              "you own will be matched with GnuCash accounts. If a GnuCash account already\n"
              "exists with the same name, or a similar name and compatible type, that account\n"
              "will be used as a match; otherwise, GnuCash will create a new account with the\n"
              "same name and type as the QIF account. If you do not like the suggested\n"
              "GnuCash account, click to change it.\n"
              "\n"
              "Note that GnuCash will be creating many accounts that did not exist on your\n"
              "other personal finance program, including a separate account for each stock\n"
              "you own, separate accounts for the brokerage commissions, special \"Equity\"\n"
              "accounts (subaccounts of Retained Earnings, by default) which are the source\n"
              "of your opening balances, etc. All of these accounts will appear on the next \n"
              "page so you can change them if you want to, but it is safe to leave them alone.\n"
              "");
gchar *s = N_("Match QIF accounts with GnuCash accounts");
gchar *s = N_("QIF account name");
gchar *s = N_("GnuCash account name");
gchar *s = N_("New?");
gchar *s = N_("Click \"Next\" to check matchings for QIF categories. ");
gchar *s = N_("Income and Expense categories");
gchar *s = N_("GnuCash uses separate Income and Expense accounts rather than categories\n"
              "to classify your transactions. Each of the categories in your QIF file will be \n"
              "converted to a GnuCash account. \n"
              "\n"
              "On the next page, you will have an opportunity to look at the suggested matches\n"
              "between QIF categories and GnuCash accounts. You may change matches \n"
              "that you do not like by clicking on the line containing the category name.\n"
              "\n"
              "If you change your mind later, you can reorganize the account structure safely\n"
              "within GnuCash.");
gchar *s = N_("Match QIF categories with GnuCash accounts");
gchar *s = N_("QIF category name");
gchar *s = N_("GnuCash account name");
gchar *s = N_("New?");
gchar *s = N_("Click \"Next\" to enter information about the currency used in your QIF files.");
gchar *s = N_("Payees and memos");
gchar *s = N_("QIF files downloaded from banks and other financial institutions may not have\n"
              "information about Accounts and Categories which would allow them to be\n"
              "correctly assigned to GnuCash accounts.  \n"
              "\n"
              "In the following page, you will see the text that appears in the Payee and \n"
              "Memo fields of transactions with no QIF Account or Category. By default\n"
              "these transactions are assigned to the 'Unspecified' account in GnuCash.\n"
              "If you select a different account, it will be remembered for future QIF \n"
              "files. ");
gchar *s = N_("Match payees/memos to GnuCash accounts");
gchar *s = N_("QIF payee/memo");
gchar *s = N_("GnuCash account name");
gchar *s = N_("New?");
gchar *s = N_("Enter the currency used for new accounts");
gchar *s = N_("The QIF importer cannot currently handle multi-currency QIF files. All the \n"
              "accounts in the QIF file(s) you are importing must be denominated in the\n"
              "same currency. This limitation should be removed soon.\n"
              "\n"
              "Select the currency to use for transactions imported from your QIF files:\n"
              "");
gchar *s = N_("Click \"Next\" to enter information about stocks and\n"
              "mutual funds in the imported data.");
gchar *s = N_("Tradable commodities");
gchar *s = N_("In the next pages, you will be asked to provide information about stocks, \n"
              "mutual funds, and other tradable commodities that appear in the QIF file(s)\n"
              "you are importing. GnuCash requires more information about tradable \n"
              "commodities than the QIF format can represent. \n"
              "\n"
              "Each stock, mutual fund, or other commodity must have a type, which is the \n"
              "exchange or listing that it is found on (NASDAQ, NYSE, US Mutual Funds, \n"
              "etc), a full name, and an abbreviation.\n"
              "\n"
              "Check to see if there is an existing Type that is appropriate; if not, you can\n"
              "enter a new Type name by hand in the box. Make sure that the abbreviation\n"
              "you enter matches the ticker symbol used for the commodity on the exchange\n"
              "or listing for its type.");
gchar *s = N_("Match duplicate transactions");
gchar *s = N_("If you are importing a QIF file downloaded from a bank or other financial\n"
              "institution, some of the information in the QIF file may duplicate information\n"
              "already in your GnuCash accounts.  GnuCash will try to detect duplicates \n"
              "of existing transactions.  \n"
              "\n"
              "On the next page, you will be asked to confirm that an existing transaction\n"
              "matches an imported transaction.  Imported transactions are shown on the\n"
              "left side of the page, and possible  matches for the selected left-hand\n"
              "transaction are shown  to the right.  There may be several old transactions \n"
              "that could match an imported transaction; you will be able to select the \n"
              "correct one by clicking in the \"Dup?\" column of the correct transaction.\n"
              "\n"
              "You can control the rules used by GnuCash to find duplicate transactions \n"
              "in the \"QIF Import\" section of the GnuCash Preferences dialog.\n"
              "\n"
              "Click \"Next\" to find duplicate transactions. ");
gchar *s = N_("Select possible duplicates");
gchar *s = N_("Imported transactions with duplicates");
gchar *s = N_("Date");
gchar *s = N_("Description");
gchar *s = N_("Amount");
gchar *s = N_("Possible duplicates for selected new transaction");
gchar *s = N_("Date");
gchar *s = N_("Description");
gchar *s = N_("Amount");
gchar *s = N_("Dup?");
gchar *s = N_("Update your GnuCash accounts");
gchar *s = N_("Click \"Finish\" to import data from the staging area and update\n"
              "your GnuCash accounts. The account and category matching\n"
              "information you have entered will be saved and used for\n"
              "defaults the next time you use the QIF import  facility. \n"
              "\n"
              "Click \"Back\" to review your account and category matchings,\n"
              "to change currency and security settings for new accounts, \n"
              "or to add more files to the staging area.\n"
              "\n"
              "Click \"Cancel\" to abort the QIF import process.");
