/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("New Style Sheet");
gchar *s = N_("New style sheet info");
gchar *s = N_("Name:");
gchar *s = N_("Style sheet template:");
gchar *s = N_("HTML Style Sheets");
gchar *s = N_("Style sheets");
gchar *s = N_("label847668");
gchar *s = N_("New...");
gchar *s = N_("Delete");
gchar *s = N_("Style sheet options");
gchar *s = N_("Available reports");
gchar *s = N_("                       ");
gchar *s = N_("Add  >>");
gchar *s = N_("<< Remove");
gchar *s = N_("Move up");
gchar *s = N_("Move down");
gchar *s = N_("Size...");
gchar *s = N_("Report");
gchar *s = N_("Cols");
gchar *s = N_("Rows");
gchar *s = N_("Report Size");
gchar *s = N_("Enter report row/column span");
gchar *s = N_("Row span:");
gchar *s = N_("Column span:");
