/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Stock Split");
gchar *s = N_("This druid will help you record a stock split or stock merger.");
gchar *s = N_("Stock Account");
gchar *s = N_("Select the account for which you want to record a stock split or merger.");
gchar *s = N_("Account");
gchar *s = N_("Symbol");
gchar *s = N_("Shares");
gchar *s = N_("Stock Split Details");
gchar *s = N_("Enter the date and the number of shares you gained or lost from the stock split or merger.\n"
              "For stock mergers (negative splits) use a negative value for the share distribution.\n"
              "You can also enter a description of the transaction, or accept the default one.");
gchar *s = N_("Date:");
gchar *s = N_("Share Distribution:");
gchar *s = N_("Description:");
gchar *s = N_("Stock Split");
gchar *s = N_("If you want to record a stock price for the split, enter it below.\n"
              "You may safely leave it blank.");
gchar *s = N_("New Price:");
gchar *s = N_("Currency:");
gchar *s = N_("Cash In Lieu");
gchar *s = N_("If you received a cash disbursement as a result of the stock split,\n"
              "enter the details of that payment here. Otherwise, just click `Next'.");
gchar *s = N_("Cash Amount:");
gchar *s = N_("Memo:");
gchar *s = N_("Cash In Lieu");
gchar *s = N_("Income Account");
gchar *s = N_("Asset Account");
gchar *s = N_("If you are finished creating the stock split or merger, press `Finish'.\n"
              "You may also press `Back' to review your choices, or `Cancel' to\n"
              "quit without making any changes.");
