/*
 * Translatable strings file generated by Glade.
 * Add this file to your project's POTFILES.in.
 * DO NOT compile it as part of your application.
 */

gchar *s = N_("Tax Information");
gchar *s = N_("Accounts");
gchar *s = N_("Income");
gchar *s = N_("Expense");
gchar *s = N_("Accounts Selected:");
gchar *s = N_("0");
gchar *s = N_("Select Subaccounts");
gchar *s = N_("Tax Information");
gchar *s = N_("Tax Related");
gchar *s = N_("TXF Categories");
gchar *s = N_("Form");
gchar *s = N_("Description");
gchar *s = N_("Payer Name Source");
gchar *s = N_("Current Account");
gchar *s = N_("Parent Account");
