# Regression guard: product code must not pump the process-wide GTK/GLib
# context or introduce nested main loops.

if (NOT DEFINED SOURCE_ROOT)
  message(FATAL_ERROR "SOURCE_ROOT is required")
endif()

set(SOURCE_DIRECTORIES common gnucash libgnucash bindings)
set(SOURCE_EXTENSIONS c cc cpp cxx h hh hpp hxx)
# Gwen needs a synchronous foreign-ABI progress drain.
set(ALLOWED_FILES
  "gnucash/import-export/aqb/gnc-gwen-gui.c"
)
# Gwen has one progress drain and two synchronous foreign-ABI response waits.
set(ALLOWED_PUMP_COUNTS 3)
set(VIOLATIONS)

foreach(DIRECTORY IN LISTS SOURCE_DIRECTORIES)
  foreach(EXTENSION IN LISTS SOURCE_EXTENSIONS)
    file(GLOB_RECURSE FILES "${SOURCE_ROOT}/${DIRECTORY}/*.${EXTENSION}")
    foreach(FILE_PATH IN LISTS FILES)
      file(RELATIVE_PATH RELATIVE_FILE "${SOURCE_ROOT}" "${FILE_PATH}")
      string(REPLACE "\\" "/" RELATIVE_FILE "${RELATIVE_FILE}")
      list(FIND ALLOWED_FILES "${RELATIVE_FILE}" ALLOWED_INDEX)
      if (RELATIVE_FILE MATCHES "(^|/)tests?(/|$)" OR
          RELATIVE_FILE MATCHES "(^|/)test-[^/]+(/|$)" OR
          RELATIVE_FILE MATCHES "(^|/).*_test\\.[^.]+$")
        continue()
      endif()

      file(READ "${FILE_PATH}" CONTENT)
      string(REPLACE "\r\n" "\n" CONTENT "${CONTENT}")
      string(REPLACE "\r" "\n" CONTENT "${CONTENT}")
      set(BLOCK_COMMENT FALSE)
      set(LINE_NUMBER 0)
      set(ACTIVE_PUMP_COUNT 0)
      # Keep physical lines out of CMake list variables: semicolons are valid
      # source characters and list expansion can otherwise alter line data.
      set(REMAINING "${CONTENT}")
      while(TRUE)
        string(FIND "${REMAINING}" "\n" NEWLINE)
        if (NEWLINE EQUAL -1)
          set(LINE "${REMAINING}")
        else()
          string(SUBSTRING "${REMAINING}" 0 ${NEWLINE} LINE)
          math(EXPR AFTER_NEWLINE "${NEWLINE} + 1")
          string(SUBSTRING "${REMAINING}" ${AFTER_NEWLINE} -1 REMAINING)
        endif()
        math(EXPR LINE_NUMBER "${LINE_NUMBER} + 1")
        set(CODE "${LINE}")

        # Remove /* ... */ comments, including multiple same-line and
        # multi-line forms.
        while (TRUE)
          if (BLOCK_COMMENT)
            string(FIND "${CODE}" "*/" CLOSE)
            if (CLOSE EQUAL -1)
              set(CODE "")
              break()
            endif()
            math(EXPR AFTER "${CLOSE} + 2")
            string(SUBSTRING "${CODE}" ${AFTER} -1 CODE)
            set(BLOCK_COMMENT FALSE)
          endif()

          string(FIND "${CODE}" "/*" OPEN)
          if (OPEN EQUAL -1)
            break()
          endif()
          math(EXPR AFTER_OPEN "${OPEN} + 2")
          string(SUBSTRING "${CODE}" ${AFTER_OPEN} -1 AFTER_OPEN_CODE)
          string(FIND "${AFTER_OPEN_CODE}" "*/" CLOSE_OFFSET)
          if (CLOSE_OFFSET EQUAL -1)
            string(SUBSTRING "${CODE}" 0 ${OPEN} CODE)
            set(BLOCK_COMMENT TRUE)
          else()
            math(EXPR CLOSE "${CLOSE_OFFSET} + ${AFTER_OPEN}")
            math(EXPR AFTER "${CLOSE} + 2")
            string(SUBSTRING "${CODE}" 0 ${OPEN} PREFIX)
            string(SUBSTRING "${CODE}" ${AFTER} -1 SUFFIX)
            set(CODE "${PREFIX}${SUFFIX}")
          endif()
        endwhile()
        string(FIND "${CODE}" "//" LINE_COMMENT)
        if (NOT LINE_COMMENT EQUAL -1)
          string(SUBSTRING "${CODE}" 0 ${LINE_COMMENT} CODE)
        endif()

        string(REGEX MATCHALL "g_main_context_iteration" GLIB_PUMPS "${CODE}")
        string(REGEX MATCHALL "gtk_main_iteration" GTK_PUMPS "${CODE}")
        string(REGEX MATCHALL "g_main_loop_run" NESTED_LOOPS "${CODE}")
        list(LENGTH GLIB_PUMPS GLIB_PUMP_COUNT)
        list(LENGTH GTK_PUMPS GTK_PUMP_COUNT)
        list(LENGTH NESTED_LOOPS NESTED_LOOP_COUNT)
        math(EXPR LINE_PUMP_COUNT
          "${GLIB_PUMP_COUNT} + ${GTK_PUMP_COUNT} + ${NESTED_LOOP_COUNT}")
        if (LINE_PUMP_COUNT GREATER 0)
          math(EXPR ACTIVE_PUMP_COUNT "${ACTIVE_PUMP_COUNT} + ${LINE_PUMP_COUNT}")
          if (ALLOWED_INDEX EQUAL -1)
            list(APPEND VIOLATIONS "${RELATIVE_FILE}:${LINE_NUMBER}")
          endif()
        endif()
        if (NEWLINE EQUAL -1)
          break()
        endif()
      endwhile()
      if (ALLOWED_INDEX GREATER -1)
        list(GET ALLOWED_PUMP_COUNTS ${ALLOWED_INDEX} EXPECTED_PUMP_COUNT)
        if (NOT ACTIVE_PUMP_COUNT EQUAL EXPECTED_PUMP_COUNT)
          list(APPEND VIOLATIONS
            "${RELATIVE_FILE}: expected ${EXPECTED_PUMP_COUNT} active pump token(s), found ${ACTIVE_PUMP_COUNT}")
        endif()
      endif()
    endforeach()
  endforeach()
endforeach()

if (VIOLATIONS)
  string(JOIN ", " VIOLATION_TEXT ${VIOLATIONS})
  message(FATAL_ERROR "Unexpected local main-loop pump(s): ${VIOLATION_TEXT}")
endif()
message(STATUS "No unexpected local GTK/GLib main-loop pumps found")
