# A MinGW target may be configured from an MSYS or POSIX host, but target
# inputs must not come from the host's include, library, or runtime trees.

include_guard(GLOBAL)

function(gnc_append_flags_once variable)
  if("${variable}" STREQUAL "" OR "${ARGN}" STREQUAL "")
    message(FATAL_ERROR
      "gnc_append_flags_once requires a variable and at least one flag")
  endif()

  set(value "${${variable}}")
  separate_arguments(existing_flags NATIVE_COMMAND "${value}")
  foreach(flag IN LISTS ARGN)
    list(FIND existing_flags "${flag}" flag_index)
    if(flag_index EQUAL -1)
      if(NOT value STREQUAL "")
        string(APPEND value " ")
      endif()
      string(APPEND value "${flag}")
      list(APPEND existing_flags "${flag}")
    endif()
  endforeach()
  set(${variable} "${value}" PARENT_SCOPE)
endfunction()

function(_gnc_normalize_target_path input output)
  string(REPLACE "\\" "/" normalized "${input}")
  cmake_path(SET normalized NORMALIZE "${normalized}")
  set(${output} "${normalized}" PARENT_SCOPE)
endfunction()

function(_gnc_target_path_is_absolute input output)
  # cmake_path() follows host semantics, but this validator also inspects
  # paths for a different target platform.
  if(input MATCHES "^([A-Za-z]:)?/")
    set(is_absolute TRUE)
  else()
    cmake_path(IS_ABSOLUTE input is_absolute)
  endif()
  set(${output} "${is_absolute}" PARENT_SCOPE)
endfunction()

function(_gnc_path_is_within path root output)
  if(CMAKE_HOST_WIN32)
    string(TOLOWER "${path}" path_key)
    string(TOLOWER "${root}" root_key)
  else()
    set(path_key "${path}")
    set(root_key "${root}")
  endif()
  if(path_key STREQUAL root_key)
    set(is_within TRUE)
  else()
    string(APPEND root_key "/")
    string(FIND "${path_key}" "${root_key}" prefix_index)
    if(prefix_index EQUAL 0)
      set(is_within TRUE)
    else()
      set(is_within FALSE)
    endif()
  endif()
  set(${output} "${is_within}" PARENT_SCOPE)
endfunction()

function(_gnc_mingw_target_roots output)
  set(target_roots)
  foreach(target_root IN LISTS CMAKE_SYSROOT CMAKE_FIND_ROOT_PATH)
    if(NOT target_root)
      continue()
    endif()
    _gnc_normalize_target_path("${target_root}" normalized_target_root)
    _gnc_target_path_is_absolute("${normalized_target_root}" is_absolute)
    if(NOT is_absolute)
      continue()
    endif()
    # An empty value or a filesystem root must never authorize every path.
    if(normalized_target_root MATCHES "^/+$"
        OR normalized_target_root MATCHES "^[A-Za-z]:/+$")
      continue()
    endif()
    list(APPEND target_roots "${normalized_target_root}")
  endforeach()
  list(REMOVE_DUPLICATES target_roots)
  set(${output} "${target_roots}" PARENT_SCOPE)
endfunction()

function(_gnc_mingw_host_input_dirs output)
  set(host_usr_roots)
  if((DEFINED ENV{MSYSTEM} AND NOT "$ENV{MSYSTEM}" STREQUAL "")
      OR (CMAKE_HOST_UNIX AND CMAKE_CROSSCOMPILING))
    list(APPEND host_usr_roots /usr)
  endif()

  foreach(shell_path IN ITEMS "${SHELL}" "${BASH}")
    if(NOT shell_path)
      continue()
    endif()
    _gnc_normalize_target_path("${shell_path}" normalized_shell)
    if(normalized_shell MATCHES "^(.+)/usr/bin/(ba)?sh(\\.exe)?$")
      list(APPEND host_usr_roots "${CMAKE_MATCH_1}/usr")
    elseif(DEFINED ENV{MSYSTEM}
        AND normalized_shell MATCHES "^(/usr)/bin/(ba)?sh(\\.exe)?$")
      list(APPEND host_usr_roots "${CMAKE_MATCH_1}")
    endif()
  endforeach()

  foreach(root_environment MSYS2_ROOT MSYS2ROOT)
    if(DEFINED ENV{${root_environment}}
        AND NOT "$ENV{${root_environment}}" STREQUAL "")
      _gnc_normalize_target_path(
        "$ENV{${root_environment}}" normalized_environment_root)
      if(normalized_environment_root MATCHES "/usr$")
        list(APPEND host_usr_roots "${normalized_environment_root}")
      else()
        list(APPEND host_usr_roots "${normalized_environment_root}/usr")
      endif()
    endif()
  endforeach()

  foreach(system_prefix IN LISTS CMAKE_SYSTEM_PREFIX_PATH)
    _gnc_normalize_target_path("${system_prefix}" normalized_prefix)
    if(CMAKE_HOST_WIN32)
      string(TOLOWER "${normalized_prefix}" normalized_prefix_key)
    else()
      set(normalized_prefix_key "${normalized_prefix}")
    endif()
    if(normalized_prefix_key MATCHES "(^|/)(msys[^/]*)/usr/?$")
      list(APPEND host_usr_roots "${normalized_prefix}")
    elseif(normalized_prefix_key MATCHES "(^|/)(msys[^/]*)/?$")
      list(APPEND host_usr_roots "${normalized_prefix}/usr")
    endif()
  endforeach()

  list(REMOVE_DUPLICATES host_usr_roots)
  set(host_input_dirs)
  foreach(host_usr IN LISTS host_usr_roots)
    list(APPEND host_input_dirs
      "${host_usr}/bin"
      "${host_usr}/include" "${host_usr}/lib"
      "${host_usr}/local/bin"
      "${host_usr}/local/include" "${host_usr}/local/lib")
  endforeach()
  set(${output} "${host_input_dirs}" PARENT_SCOPE)
endfunction()

function(_gnc_mingw_input_paths values output)
  set(paths)
  set(expect_path FALSE)
  foreach(value IN LISTS values)
    if(value MATCHES "^SHELL:(.*)$")
      set(value "${CMAKE_MATCH_1}")
      separate_arguments(arguments NATIVE_COMMAND "${value}")
    elseif(value MATCHES "^-")
      separate_arguments(arguments NATIVE_COMMAND "${value}")
    else()
      set(arguments "${value}")
    endif()

    foreach(argument IN LISTS arguments)
      if(expect_path)
        set(candidate "${argument}")
        set(expect_path FALSE)
      elseif(argument MATCHES "^-Wl,-L,([^,]+)")
        set(candidate "${CMAKE_MATCH_1}")
      elseif(argument MATCHES "^-Wl,-L([^,]+)")
        set(candidate "${CMAKE_MATCH_1}")
      elseif(argument MATCHES "^-Wl,")
        continue()
      elseif(argument MATCHES "^(-I|-L|-isystem=?)(.+)$")
        set(candidate "${CMAKE_MATCH_2}")
      elseif(argument MATCHES "^/LIBPATH:(.+)$")
        set(candidate "${CMAKE_MATCH_1}")
      elseif(argument MATCHES "^(-I|-L|-isystem|/LIBPATH:)$")
        set(expect_path TRUE)
        continue()
      elseif(argument MATCHES "^-" AND NOT argument MATCHES "\\$<")
        continue()
      else()
        set(candidate "${argument}")
      endif()

      string(REGEX REPLACE "^['\"]|['\"]$" "" candidate "${candidate}")
      _gnc_normalize_target_path("${candidate}" normalized_candidate)
      _gnc_target_path_is_absolute("${normalized_candidate}" is_absolute)
      if(is_absolute)
        list(APPEND paths "${normalized_candidate}")
        continue()
      endif()

      # Generator expressions aren't evaluated while configuring. Extract
      # their absolute path operands so that BUILD_INTERFACE, SHELL_PATH, and
      # conditional expressions can't hide a host path.
      string(REGEX MATCHALL
        "([A-Za-z]:[/\\\\][^>,;\"]+|/[^>,;\"]+)"
        embedded_paths "${candidate}")
      foreach(embedded_path IN LISTS embedded_paths)
        string(STRIP "${embedded_path}" embedded_path)
        _gnc_normalize_target_path("${embedded_path}" embedded_path)
        _gnc_target_path_is_absolute("${embedded_path}" is_absolute)
        if(is_absolute)
          list(APPEND paths "${embedded_path}")
        endif()
      endforeach()
    endforeach()
  endforeach()
  list(REMOVE_DUPLICATES paths)
  set(${output} "${paths}" PARENT_SCOPE)
endfunction()

function(gnc_validate_mingw_target_paths)
  if(NOT MINGW)
    return()
  endif()

  cmake_parse_arguments(PARSE_ARGV 0 arg "" "" "VARIABLES")
  if(arg_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR
      "Unknown arguments to gnc_validate_mingw_target_paths: ${arg_UNPARSED_ARGUMENTS}")
  endif()

  _gnc_mingw_target_roots(target_roots)
  _gnc_mingw_host_input_dirs(host_input_dirs)
  foreach(variable IN LISTS arg_VARIABLES)
    if(NOT DEFINED ${variable})
      continue()
    endif()
    _gnc_mingw_input_paths("${${variable}}" input_paths)
    foreach(input_path IN LISTS input_paths)
      set(is_target_input FALSE)
      foreach(target_root IN LISTS target_roots)
        _gnc_path_is_within("${input_path}" "${target_root}" is_target_input)
        if(is_target_input)
          break()
        endif()
      endforeach()
      if(is_target_input)
        continue()
      endif()
      foreach(host_input_dir IN LISTS host_input_dirs)
        _gnc_path_is_within("${input_path}" "${host_input_dir}" is_host_input)
        if(is_host_input)
          message(FATAL_ERROR
            "MinGW target input ${variable} resolves to the host path "
            "\"${input_path}\". Target headers, libraries, and runtime "
            "artifacts must come from a MinGW target prefix. Configure the "
            "target search roots in the toolchain file with CMAKE_SYSROOT or "
            "CMAKE_FIND_ROOT_PATH, or set ${variable} explicitly to a target "
            "path.")
        endif()
      endforeach()
    endforeach()
  endforeach()
endfunction()
