#! /bin/sh
exec guile -s "$0"
!#

(display "  testing file backend load ... ")
(use-modules (gnucash gnc-module))
(gnc:module-system-init)

(gnc:module-load "gnucash/engine" 0)

(if (gnc:module-load "gnucash/backend/file" 0)
    (begin 
      (display "ok\n")
      (exit 0))
    (begin 
      (display "failed\n")
      (exit -1)))
