name: ci-tests-docker
on: [push, pull_request]
permissions: {}
jobs:
  ci_tests_archlinux:
    runs-on: ubuntu-latest
    name: Arch Linux (via Docker) CI
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Test Action
      uses: ./util/ci/actions/archlinux-test
    - uses: actions/upload-artifact@v2
      with:
        name: TestLog
        path: ${{ github.workspace }}/LastTest.log
