name: coverage
on: push
permissions: {}
jobs:
  coverage:
    runs-on: ubuntu-26.04
    name: C++ Code coverage analysis
    timeout-minutes: 120
    continue-on-error: true
    env:
      TZ: America/Los_Angeles
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: sudo apt-get update
      - name: Install additional dependencies
        run: sudo apt-get install -y gettext cmake libxslt-dev xsltproc ninja-build libboost-all-dev libgtk-4-dev guile-2.2-dev libofx-dev libdbi-dev libdbd-sqlite3 libwebkitgtk-6.0-dev googletest lcov python3-dev swig xvfb
      - name: Install language packs.
        run: sudo apt-get --reinstall install -y language-pack-en language-pack-fr
      - run: |
          echo "ROOT_DIR=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
      - name: Create Directories
        run: |
          pwd
          mkdir $ROOT_DIR/inst
          mkdir build
      - name: Configure GnuCash without AqBanking
        run: |
          cd build
          # Ubuntu doesn't yet provide the required gwengui-gtk4 package.
          cmake -G Ninja -DWITH_PYTHON=ON -DWITH_AQBANKING=OFF -DCMAKE_INSTALL_PREFIX=$ROOT_DIR/inst $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=Debug -DCOVERAGE=ON
      - name: Validate GTK4 builder resources
        run: xvfb-run -a bash "$GITHUB_WORKSPACE/util/ci/validate-gtk4-builder-resources.sh" "$GITHUB_WORKSPACE/gnucash"
      - name: Build and test GnuCash with coverage analysis
        run: |
          cd build
          ninja
          ninja lcov-initialize
          ninja check
          ninja -k 0 lcov-collect
          ninja lcov-generate-html
        env:
          CTEST_OUTPUT_ON_FAILURE: Off
      - name: prepare_upload
        if: success()
        run: |
          mkdir build/github-pages
          mv build/Coverage-HTML build/github-pages/Coverage
          chmod -v -R +rX "build/github-pages" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload pages
        uses: actions/upload-artifact@v7
        if: success()
        with:
          name: coverage-build
          path: ${{ github.workspace }}/build/github-pages/Coverage


  programming-docs:
    runs-on: ubuntu-26.04
    name: Build Programming Documentation
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - run: sudo apt-get update
      - name: Install additional dependencies
        run: sudo apt-get install -y gettext cmake libxslt-dev xsltproc ninja-build libboost-all-dev libgtk-4-dev guile-2.2-dev libofx-dev libdbi-dev libdbd-sqlite3 libwebkitgtk-6.0-dev googletest doxygen swig
      - name: Install language packs.
        run: sudo apt-get --reinstall install -y language-pack-en language-pack-fr
      - run: |
          echo "ROOT_DIR=$GITHUB_WORKSPACE/.." >> $GITHUB_ENV
      - name: Create Directories
        run: |
          pwd
          mkdir $ROOT_DIR/inst
          mkdir build
      - name: Configure GnuCash without AqBanking
        run: |
          cd build
          # Ubuntu doesn't yet provide the required gwengui-gtk4 package.
          cmake -G Ninja -DWITH_AQBANKING=OFF $GITHUB_WORKSPACE
      - name: Run Doxygen
        run: |
          cd build
          ninja doc
      - name: prepare_upload
        if: success()
        run: |
          mkdir build/github-pages
          mv build/doxygen/html build/github-pages/Documentation
          chmod -v -R +rX "build/github-pages" | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done
      - name: Upload pages
        uses: actions/upload-artifact@v7
        if: success()
        with:
          name: documentation-build
          path: ${{ github.workspace }}/build/github-pages/Documentation

  deploy-docs:
    needs: [
           coverage,
           programming-docs
           ]
    if: github.repository == 'gnucash/gnucash'  && github.ref == 'refs/heads/stable'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/configure-pages@v6
      - name: download-coverage
        uses: actions/download-artifact@v8
        with:
           name: coverage-build
           path: github-pages/Coverage
      - name: download-documentation
        uses: actions/download-artifact@v8
        with:
           name: documentation-build
           path: github-pages/Documentation
      - name: upload pages
        uses: actions/upload-pages-artifact@v5
        with:
           path: github-pages
      - name: Publish
        id: deployment
        uses: actions/deploy-pages@v5
