name: mac-tests
on: [push, pull_request]
permissions: {}
jobs:
  ci_tests_mac:
    runs-on: macos-26
    name: macOS CI Tests
    env:
      TZ: America/Los_Angeles
    steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: configure Environment
      run: |
        echo "PATH=$HOME/gnucash/inst/bin:$PATH" >> $GITHUB_ENV
        echo "PREFIX=$HOME/gnucash/inst" >> $GITHUB_ENV
        echo "SRCROOT=$HOME/gnucash/source" >> $GITHUB_ENV
        echo "BUILD_DIR=$HOME/gnucash/build" >> $GITHUB_ENV
        echo "XDG_DATA_DIRS=$HOME/gnucash/inst/share:/usr/local/share:/usr/share" >> $GITHUB_ENV
        brew install ninja
    - name: download dependency tarball
      uses: carlosperate/download-file-action@v2
      id: dependencies
      with:
        file-url: 'https://downloads.sourceforge.net/gnucash/Dependencies/gnucash-future-mac-dependencies.tar.xz'
        file-name: gnucash-future-mac-dependencies.tar.xz
        sha256: 'defd09caf5f5198be0892fb0709cf39dddbc407a3d5e2363c0d91cdbd6ad042f'
    - name: download googletest
      uses: carlosperate/download-file-action@v2

      id: googletest
      with:
        file-url: 'https://github.com/google/googletest/releases/download/v1.17.0/googletest-1.17.0.tar.gz'
        file-name: googletest-1.17.0.tar.gz
        sha256: '65fab701d9829d38cb77c14acdc431d2108bfdbf8979e40eb8ae567edf10b27c'
    - name: Extract Dependencies
      run: |
        mkdir -p $HOME/gnucash/inst
        cd $HOME/gnucash/inst
        tar -xf $GITHUB_WORKSPACE/gnucash-future-mac-dependencies.tar.xz
        mkdir $HOME/gnucash/source
        cd $HOME/gnucash/source
        tar -xf $GITHUB_WORKSPACE/googletest-1.17.0.tar.gz
        mv googletest-* googletest
    - name: Verify runtime dependencies
      run: sh "$GITHUB_WORKSPACE/util/ci/macos-ci-deps/verify-macos-deps.sh" "$PREFIX"
    - name: Configure GnuCash
      run: |
        mkdir $HOME/gnucash/build
        cd $HOME/gnucash/build
        cmake -GNinja -DPKG_CONFIG_EXECUTABLE=$PREFIX/bin/pkgconf -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_PREFIX_PATH=$PREFIX -DWITH_PYTHON=ON -DGTEST_ROOT=$SRCROOT/googletest $GITHUB_WORKSPACE
    - name: Build and Test GnuCash
      run: |
        cd $HOME/gnucash/build
        ninja
        ninja check
      env:
        CTEST_OUTPUT_ON_FAILURE: On
    - uses: actions/upload-artifact@v7
      if: failure()
      with:
        name: TestLog
        path: ${{ env.BUILD_DIR }}/Testing/Temporary/LastTest.log
        if-no-files-found: ignore
